export const modelCategories = [
  'Analytics',
  'App Definition and Development',
  'Cloud Native Network',
  'Cloud Native Storage',
  'Database',
  'Machine Learning',
  'Observability and Analysis',
  'Orchestration & Management',
  'Platform',
  'Provisioning',
  'Runtime',
  'Security & Compliance',
  'Serverless',
  'Tools',
  'Uncategorized',
];

export const modelSubCategories = [
  'API Gateway',
  'API Integration',
  'Application Definition & Image Build',
  'Automation & Configuration',
  'Certified Kubernetes - Distribution',
  'Chaos Engineering',
  'Cloud Native Storage',
  'Cloud Provider',
  'CNI',
  'Compute',
  'Container Registry',
  'Container Runtime',
  'Container Security',
  'Container',
  'Content Delivery Network',
  'Continuous Integration & Delivery',
  'Coordination & Service Discovery',
  'Database',
  'Flowchart',
  'Framework',
  'Installable Platform',
  'Key Management',
  'Key Management Service',
  'Kubernetes',
  'Logging',
  'Machine Learning',
  'Management Governance',
  'Metrics',
  'Monitoring',
  'Networking Content Delivery',
  'Operating System',
  'Query',
  'Remote Procedure Call',
  'Scheduling & Orchestration',
  'Secrets Management',
  'Security Identity & Compliance',
  'Service Mesh',
  'Service Proxy',
  'Source Version Control',
  'Storage',
  'Specifications',
  'Streaming & Messaging',
  'Tools',
  'Tracing',
  'Uncategorized',
  'Video Conferencing',
];

export const modelShapes = [
  'rectangle',
  'round-rectangle',
  'bottom-round-rectangle',
  'cut-rectangle',
  'shape',
  'circle',
  'diamond',
  'round-rectang',
  'hexagon',
  'rhomboid',
  'triangle',
  'cilinder',
  'round-triangle',
  'round-pentagon',
  'sheild',
  'vee',
  'cylinder',
  'round-heptagon',
  'concave-hexagon',
  'right-rhomboid',
  'barrel',
  'round-diamond',
];

export const CSV_TEMPLATE_BASE_URL =
  'https://raw.githubusercontent.com/meshery/meshery/a514f8689260791077bde8171646933cff15dd08/mesheryctl/templates/template-csvs/';
