import React from 'react';
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { renderHook, act } from '@testing-library/react';
import { mesheryApiPath } from '../index';

// The schemas client reads its baseUrl from the environment once, at module
// evaluation - which the static import above triggers. Hoisting the assignment
// above the imports is what makes it absolute; vitest's `Request` rejects the
// relative URL an empty prefix produces.
vi.hoisted(() => {
  process.env.RTK_MESHERY_ENDPOINT_PREFIX = 'http://localhost';
});

const {
  schemasGetUserCredentials,
  schemasGetCredentialById,
  schemasSaveTrigger,
  schemasUpdateTrigger,
} = vi.hoisted(() => ({
  schemasGetUserCredentials: vi.fn(),
  schemasGetCredentialById: vi.fn(),
  schemasSaveTrigger: vi.fn(),
  schemasUpdateTrigger: vi.fn(),
}));

vi.mock('@meshery/schemas/mesheryApi', async () => {
  const actual = await vi.importActual<Record<string, unknown>>('@meshery/schemas/mesheryApi');
  return {
    ...actual,
    useGetUserCredentialsQuery: (...args: unknown[]) => schemasGetUserCredentials(...args),
    useGetCredentialByIdQuery: (...args: unknown[]) => schemasGetCredentialById(...args),
    useSaveUserCredentialMutation: () => [schemasSaveTrigger, { isLoading: false }],
    useUpdateUserCredentialMutation: () => [schemasUpdateTrigger, { isLoading: false }],
  };
});

// ---------------------------------------------------------------------------
// Unit tests for the credentials RTK-query endpoints.
//
// The SaveUserCredential fix (returning the created credential instead of nil)
// means the POST /api/integrations/credentials endpoint now responds with the
// full credential object. These tests assert:
//   1. The mutation targets the correct URL and HTTP method.
//   2. When the server returns the credential object the caller receives it.
//   3. When the server returns an error the caller receives the error.
// ---------------------------------------------------------------------------

describe('mesheryApiPath – credentials path', () => {
  it('builds the integrations/credentials URL', () => {
    expect(mesheryApiPath('integrations/credentials')).toBe('/api/integrations/credentials');
  });

  it('builds a per-credential URL for reads and deletes', () => {
    const id = 'abc-123';
    expect(mesheryApiPath(`integrations/credentials/${id}`)).toBe(
      `/api/integrations/credentials/${id}`,
    );
  });
});

describe('createCredential – HTTP contract', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    global.fetch = vi.fn();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('sends a POST with the credential body and returns the created credential', async () => {
    const input = { name: 'my-api-key', type: 'token', secret: { token: 'secret-value' } };
    // The server now returns the full credential object (including the assigned ID)
    // after the SaveUserCredential nil-return fix.
    const serverResponse = { ...input, id: 'server-assigned-uuid' };

    (global.fetch as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: true,
      status: 201,
      redirected: false,
      text: () => Promise.resolve(JSON.stringify(serverResponse)),
    });

    const url = mesheryApiPath('integrations/credentials');
    const resp = await fetch(url, { method: 'POST', body: JSON.stringify(input) });
    const body = JSON.parse(await resp.text());

    expect(global.fetch).toHaveBeenCalledWith(
      '/api/integrations/credentials',
      expect.objectContaining({ method: 'POST' }),
    );
    expect(body).toEqual(serverResponse);
    expect(body.id).toBe('server-assigned-uuid');
  });

  it('surfaces an error response when credential creation fails', async () => {
    (global.fetch as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: false,
      status: 500,
      redirected: false,
      text: () => Promise.resolve('error saving user credentials: duplicate key'),
    });

    const url = mesheryApiPath('integrations/credentials');
    const resp = await fetch(url, { method: 'POST', body: '{}' });

    expect(resp.ok).toBe(false);
    expect(resp.status).toBe(500);
    const text = await resp.text();
    expect(text).toContain('error saving user credentials');
  });
});

// The read/create/update endpoints are generated by @meshery/schemas, so this
// module adapts the call signatures rather than re-declaring the endpoints.
describe('credentials hooks delegate to schemas', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('reads the list through the schemas getUserCredentials query', async () => {
    const { useGetCredentialsQuery } = await import('../credentials');
    useGetCredentialsQuery();
    // Forwarded as-is rather than defaulted to `{}`, so this shares a cache key
    // with connection.ts's wrapper over the same schemas endpoint.
    expect(schemasGetUserCredentials).toHaveBeenCalledWith(undefined, undefined);
  });

  it('accepts a bare id and hands schemas the { credentialId } it expects', async () => {
    const { useGetCredentialByIdQuery } = await import('../credentials');
    useGetCredentialByIdQuery('abc-123');
    expect(schemasGetCredentialById).toHaveBeenCalledWith({ credentialId: 'abc-123' }, undefined);
  });

  it('accepts a bare credential and hands schemas the { body } it expects', async () => {
    const { useCreateCredentialMutation, useUpdateCredentialMutation } =
      await import('../credentials');
    const credential = { name: 'my-api-key', type: 'token' };

    const [create] = useCreateCredentialMutation();
    create(credential);
    expect(schemasSaveTrigger).toHaveBeenCalledWith({ body: credential });

    const [update] = useUpdateCredentialMutation();
    update(credential);
    expect(schemasUpdateTrigger).toHaveBeenCalledWith({ body: credential });
  });
});

// ---------------------------------------------------------------------------
// Nothing about `deleteCredential` is local any more. `useDeleteCredentialMutation`
// wraps the schemas-generated `useDeleteUserCredentialMutation` and only adapts a
// bare id to the `{ credentialId }` that endpoint takes.
//
// It used to be re-declared here because the generated request sends
// `?credentialId=` while DeleteUserCredential in
// server/handlers/credentials_handlers.go read only `credential_id`. That was
// fixed on the server, not by forking the request: the handler now reads the
// canonical camelCase param and keeps `credential_id` only as a legacy fallback.
//
// The bare-id -> `{ credentialId }` mapping is the part that can regress
// silently, so this drives the exported hook through a real store and asserts the
// request that ACTUALLY goes over the wire. Dispatching the generated endpoint
// directly would assert the schemas contract and never touch the wrapper.
// ---------------------------------------------------------------------------

const okResponse = (body: unknown = {}) => ({
  ok: true,
  status: 200,
  redirected: false,
  headers: new Headers({ 'content-type': 'application/json' }),
  url: '',
  text: () => Promise.resolve(JSON.stringify(body)),
  json: () => Promise.resolve(body),
  clone() {
    return this;
  },
});

const setupDeleteStore = async () => {
  vi.resetModules();
  const apiMod = await import('../index');
  const credentialsMod = await import('../credentials');
  const { configureStore } = await import('@reduxjs/toolkit');
  const { Provider } = await import('react-redux');

  const store = configureStore({
    reducer: { [apiMod.api.reducerPath]: apiMod.api.reducer },
    middleware: (g) => g().concat(apiMod.api.middleware),
  });

  const wrapper = ({ children }: { children: React.ReactNode }) =>
    React.createElement(Provider, { store }, children);

  return { credentialsMod, wrapper };
};

describe('deleteCredential effective endpoint', () => {
  let fetchMock: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    // spyOn (not direct assignment) so `vi.restoreAllMocks()` below actually
    // reverts it - a raw `global.fetch = ...` would outlive this file.
    fetchMock = vi.spyOn(globalThis, 'fetch') as unknown as ReturnType<typeof vi.fn>;
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('DELETEs /api/integrations/credentials with the id as ?credentialId=', async () => {
    fetchMock.mockResolvedValue(okResponse({}));
    const { credentialsMod, wrapper } = await setupDeleteStore();

    const { result } = renderHook(() => credentialsMod.useDeleteCredentialMutation(), { wrapper });
    await act(async () => {
      await result.current[0]('abc-123');
    });

    expect(fetchMock).toHaveBeenCalledTimes(1);
    const req = fetchMock.mock.calls[0][0] as Request;
    expect(req.method).toBe('DELETE');
    expect(req.url).toContain('/api/integrations/credentials');
    expect(new URL(req.url).searchParams.get('credentialId')).toBe('abc-123');
    expect(req.url).not.toContain('undefined');
  });
});
