// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cluster struct {
	ID           *string        `json:"id"`
	Name         *string        `json:"name"`
	ClusterNodes []*ClusterNode `json:"clusterNodes"`
	Namespaces   []*Namespace   `json:"namespaces"`
}

type ClusterNode struct {
	ID       string `json:"id"`
	Parentid string `json:"parentid"`
	Name     string `json:"name"`
	Pods     []*Pod `json:"pods"`
}

type Deployment struct {
	ID       string `json:"id"`
	Parentid string `json:"parentid"`
	Name     string `json:"name"`
	Pods     []*Pod `json:"pods"`
}

type Namespace struct {
	ID          string        `json:"id"`
	Parentid    string        `json:"parentid"`
	Name        string        `json:"name"`
	Deployments []*Deployment `json:"deployments"`
	Services    []*Service    `json:"services"`
}

type Pod struct {
	ID       string `json:"id"`
	Parentid string `json:"parentid"`
	Name     string `json:"name"`
}

type Service struct {
	ID          string    `json:"id"`
	Parentid    string    `json:"parentid"`
	Name        *string   `json:"name"`
	Deployments []*string `json:"deployments"`
}
