// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Deployment struct {
	Name        string `json:"name"`
	ID          string `json:"id"`
	Namespaceid string `json:"namespaceid"`
}

type DeploymentFilter struct {
	Namespaceid *string `json:"namespaceid"`
}

type Namespace struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

type Node struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

type Pod struct {
	Name         string `json:"name"`
	ID           string `json:"id"`
	Nodeid       string `json:"nodeid"`
	Namespaceid  string `json:"namespaceid"`
	Deploymentid string `json:"deploymentid"`
}

type PodFilter struct {
	Nodeid       *string `json:"nodeid"`
	Namespaceid  *string `json:"namespaceid"`
	Deploymentid *string `json:"deploymentid"`
}
