package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"time"

	"github.com/gofrs/uuid"
	"github.com/meshery/meshery/server/handlers"
	"github.com/meshery/meshery/server/internal/graphql/generated"
	"github.com/meshery/meshery/server/internal/graphql/model"
	"github.com/meshery/meshery/server/machines/kubernetes"
	"github.com/meshery/meshery/server/models"
	"github.com/meshery/meshkit/utils"
)

// ChangeOperatorStatus is the resolver for the changeOperatorStatus field.
func (r *mutationResolver) ChangeOperatorStatus(ctx context.Context, input *model.OperatorStatusInput) (model.Status, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.changeOperatorStatus(ctx, provider, input.TargetStatus, input.ContextID)
}

// ChangeAdapterStatus is the resolver for the changeAdapterStatus field.
func (r *mutationResolver) ChangeAdapterStatus(ctx context.Context, input *model.AdapterStatusInput) (model.Status, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.changeAdapterStatus(ctx, provider, input.TargetStatus, input.Adapter, input.TargetPort)
}

// GetAvailableAddons is the resolver for the getAvailableAddons field.
func (r *queryResolver) GetAvailableAddons(ctx context.Context, filter *model.ServiceMeshFilter) ([]*model.AddonList, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	if filter != nil {
		return r.getAvailableAddons(ctx, provider, filter)
	}

	return nil, ErrInvalidRequest
}

// GetControlPlanes is the resolver for the getControlPlanes field.
func (r *queryResolver) GetControlPlanes(ctx context.Context, filter *model.ServiceMeshFilter) ([]*model.ControlPlane, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	if filter != nil {
		return r.getControlPlanes(ctx, provider, filter)
	}

	return nil, ErrInvalidRequest
}

// GetDataPlanes is the resolver for the getDataPlanes field.
func (r *queryResolver) GetDataPlanes(ctx context.Context, filter *model.ServiceMeshFilter) ([]*model.DataPlane, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	if filter != nil {
		return r.getDataPlanes(ctx, provider, filter)
	}

	return nil, ErrInvalidRequest
}

// GetOperatorStatus is the resolver for the getOperatorStatus field.
func (r *queryResolver) GetOperatorStatus(ctx context.Context, connectionID string) (*model.MesheryControllersStatusListItem, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.getOperatorStatus(ctx, provider, connectionID)
}

// ResyncCluster is the resolver for the resyncCluster field.
func (r *queryResolver) ResyncCluster(ctx context.Context, selector *model.ReSyncActions, k8scontextID string) (model.Status, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.resyncCluster(ctx, provider, selector, k8scontextID)
}

// GetMeshsyncStatus is the resolver for the getMeshsyncStatus field.
func (r *queryResolver) GetMeshsyncStatus(ctx context.Context, connectionID string) (*model.OperatorControllerStatus, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.getMeshsyncStatus(ctx, provider, connectionID)
}

// GetNatsStatus is the resolver for the getNatsStatus field.
func (r *queryResolver) GetNatsStatus(ctx context.Context, connectionID string) (*model.OperatorControllerStatus, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.getNatsStatus(ctx, provider, connectionID)
}

// GetAvailableNamespaces is the resolver for the getAvailableNamespaces field.
func (r *queryResolver) GetAvailableNamespaces(ctx context.Context, k8sClusterIDs []string) ([]*model.NameSpace, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.getAvailableNamespaces(ctx, provider, k8sClusterIDs)
}

// GetPerfResult is the resolver for the getPerfResult field.
func (r *queryResolver) GetPerfResult(ctx context.Context, id string) (*model.MesheryResult, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.getPerfResult(ctx, provider, id)
}

// FetchResults is the resolver for the fetchResults field.
func (r *queryResolver) FetchResults(ctx context.Context, selector model.PageFilter, profileID string) (*model.PerfPageResult, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.fetchResults(ctx, provider, selector, profileID)
}

// GetPerformanceProfiles is the resolver for the getPerformanceProfiles field.
func (r *queryResolver) GetPerformanceProfiles(ctx context.Context, selector model.PageFilter) (*model.PerfPageProfiles, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.getPerformanceProfiles(ctx, provider, selector)
}

// FetchAllResults is the resolver for the fetchAllResults field.
func (r *queryResolver) FetchAllResults(ctx context.Context, selector model.PageFilter) (*model.PerfPageResult, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.fetchAllResults(ctx, provider, selector)
}

// FetchPatterns is the resolver for the fetchPatterns field.
func (r *queryResolver) FetchPatterns(ctx context.Context, selector model.PageFilter) (*model.PatternPageResult, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.fetchPatterns(ctx, provider, selector)
}

// GetKubectlDescribe is the resolver for the getKubectlDescribe field.
func (r *queryResolver) GetKubectlDescribe(ctx context.Context, name string, kind string, namespace string) (*model.KctlDescribeDetails, error) {
	return r.getKubectlDescribe(ctx, name, kind, namespace)
}

// FetchPatternCatalogContent is the resolver for the fetchPatternCatalogContent field.
func (r *queryResolver) FetchPatternCatalogContent(ctx context.Context, selector *model.CatalogSelector) ([]*model.CatalogPattern, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.fetchCatalogPattern(ctx, provider, selector)
}

// FetchFilterCatalogContent is the resolver for the fetchFilterCatalogContent field.
func (r *queryResolver) FetchFilterCatalogContent(ctx context.Context, selector *model.CatalogSelector) ([]*model.CatalogFilter, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.fetchCatalogFilter(ctx, provider, selector)
}

// GetMeshModelSummary is the resolver for the getMeshModelSummary field.
func (r *queryResolver) GetMeshModelSummary(ctx context.Context, selector model.MeshModelSummarySelector) (*model.MeshModelSummary, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.getMeshModelSummary(ctx, provider, selector)
}

// FetchTelemetryComponents is the resolver for the fetchTelemetryComponents field.
func (r *queryResolver) FetchTelemetryComponents(ctx context.Context, contexts []string) ([]*model.TelemetryComp, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.getTelemetryComps(ctx, provider, contexts)
}

// SubscribePerfProfiles is the resolver for the subscribePerfProfiles field.
func (r *subscriptionResolver) SubscribePerfProfiles(ctx context.Context, selector model.PageFilter) (<-chan *model.PerfPageProfiles, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.subscribePerfProfiles(ctx, provider, selector)
}

// SubscribePerfResults is the resolver for the subscribePerfResults field.
func (r *subscriptionResolver) SubscribePerfResults(ctx context.Context, selector model.PageFilter, profileID string) (<-chan *model.PerfPageResult, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.subscribePerfResults(ctx, provider, selector, profileID)
}

// SubscribeMesheryControllersStatus is the resolver for the subscribeMesheryControllersStatus field.
func (r *subscriptionResolver) SubscribeMesheryControllersStatus(ctx context.Context, connectionIDs []string) (<-chan []*model.MesheryControllersStatusListItem, error) {
	resChan := make(chan []*model.MesheryControllersStatusListItem)
	handler, ok := ctx.Value(models.HandlerKey).(*handlers.Handler)

	if !ok {
		er := model.ErrMesheryControllersStatusSubscription(fmt.Errorf("controller handlers are not configured for any of the contexts"))
		r.Log.Error(er)
		return nil, er
	}

	statusMapPerConnection := make(map[string]map[models.MesheryController]models.MesheryControllerStatusAndVersion)
	// initialize the map

	for _, connectionID := range connectionIDs {
		inst, ok := handler.ConnectionToStateMachineInstanceTracker.Get(uuid.FromStringOrNil(connectionID))
		if ok && inst != nil {
			machinectx, err := utils.Cast[*kubernetes.MachineCtx](inst.Context)
			if err != nil {
				r.Log.Error(model.ErrMesheryControllersStatusSubscription(err))
				continue
			}
			ctrlHandlers := machinectx.MesheryCtrlsHelper.GetControllerHandlersForEachContext()
			for controller, handler := range ctrlHandlers {
				if _, ok := statusMapPerConnection[connectionID]; !ok {
					statusMapPerConnection[connectionID] = make(map[models.MesheryController]models.MesheryControllerStatusAndVersion)
				}
				version, err := handler.GetVersion()
				if err != nil {
					er := model.ErrMesheryControllersStatusSubscription(err)
					r.Log.Error(er)
				}

				statusMapPerConnection[connectionID][controller] = models.MesheryControllerStatusAndVersion{
					Status:  handler.GetStatus(),
					Version: version,
				}
			}

		}
	}
	go func() {
		defer close(resChan)

		ctrlsStatusList := make([]*model.MesheryControllersStatusListItem, 0)
		// first send the initial status of the controllers
		for connectionID, controllerMap := range statusMapPerConnection {
			for controller, statusAndVersion := range controllerMap {
				ctrlsStatusList = append(ctrlsStatusList, &model.MesheryControllersStatusListItem{
					ConnectionID: connectionID,
					Controller:   model.GetInternalController(controller),
					Status:       model.GetInternalControllerStatus(statusAndVersion.Status),
					Version:      statusAndVersion.Version,
				})
			}
		}
		select {
		case resChan <- ctrlsStatusList:
		case <-ctx.Done():
			return
		}

		ticker := time.NewTicker(5 * time.Second)
		defer ticker.Stop()

		for {
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
			}

			for _, connectionID := range connectionIDs {
				inst, ok := handler.ConnectionToStateMachineInstanceTracker.Get(uuid.FromStringOrNil(connectionID))
				if !ok || inst == nil {
					continue
				}

				machinectx, err := utils.Cast[*kubernetes.MachineCtx](inst.Context)
				if err != nil {
					r.Log.Error(model.ErrMesheryControllersStatusSubscription(err))
					continue
				}

				ctrlHandlers := machinectx.MesheryCtrlsHelper.GetControllerHandlersForEachContext()
				for controller, controllerHandler := range ctrlHandlers {
					newStatus := controllerHandler.GetStatus()

					version, err := controllerHandler.GetVersion()
					if err != nil {
						er := model.ErrMesheryControllersStatusSubscription(err)
						r.Log.Error(er)
					}

					if _, ok := statusMapPerConnection[connectionID]; !ok {
						statusMapPerConnection[connectionID] = make(map[models.MesheryController]models.MesheryControllerStatusAndVersion)
					}

					previous, hasPrevious := statusMapPerConnection[connectionID][controller]
					if !hasPrevious || newStatus != previous.Status || version != previous.Version {
						update := []*model.MesheryControllersStatusListItem{{
							ConnectionID: connectionID,
							Controller:   model.GetInternalController(controller),
							Status:       model.GetInternalControllerStatus(newStatus),
							Version:      version,
						}}
						select {
						case resChan <- update:
						case <-ctx.Done():
							return
						}
					}

					statusMapPerConnection[connectionID][controller] = models.MesheryControllerStatusAndVersion{
						Status:  newStatus,
						Version: version,
					}
				}
			}
		}
	}()
	return resChan, nil
}

// SubscribeConfiguration is the resolver for the subscribeConfiguration field.
func (r *subscriptionResolver) SubscribeConfiguration(ctx context.Context, patternSelector model.PageFilter, filterSelector model.PageFilter) (<-chan *model.ConfigurationPage, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	user := ctx.Value(models.UserCtxKey).(*models.User)
	return r.subscribeConfiguration(ctx, provider, *user, patternSelector, filterSelector)
}

// SubscribeClusterResources is the resolver for the subscribeClusterResources field.
func (r *subscriptionResolver) SubscribeClusterResources(ctx context.Context, k8scontextIDs []string, namespace string) (<-chan *model.ClusterResources, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.subscribeClusterResources(ctx, provider, k8scontextIDs, namespace)
}

// SubscribeK8sContext is the resolver for the subscribeK8sContext field.
func (r *subscriptionResolver) SubscribeK8sContext(ctx context.Context, selector model.PageFilter) (<-chan *model.K8sContextsPage, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.subscribeK8sContexts(ctx, provider, selector)
}

// SubscribeMeshModelSummary is the resolver for the subscribeMeshModelSummary field.
func (r *subscriptionResolver) SubscribeMeshModelSummary(ctx context.Context, selector model.MeshModelSummarySelector) (<-chan *model.MeshModelSummary, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.subscribeMeshModelSummary(ctx, provider, selector)
}

// SubscribeEvents is the resolver for the subscribeEvents field.
func (r *subscriptionResolver) SubscribeEvents(ctx context.Context) (<-chan *model.Event, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	user := ctx.Value(models.UserCtxKey).(*models.User)
	return r.eventsResolver(ctx, provider, *user)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *subscriptionResolver) SubscribeMeshSyncEvents(ctx context.Context, connectionIDs []string, eventTypes []model.MeshSyncEventType) (<-chan *model.MeshSyncEvent, error) {
	resChan := make(chan *model.MeshSyncEvent)
	var isSubscriptionFlushed atomic.Bool
	brokerEventTypes := model.GetMesheryBrokerEventTypesFromArray(eventTypes)

	handler, ok := ctx.Value(models.HandlerKey).(*handlers.Handler)
	if !ok {
		er := model.ErrMeshSyncEventsSubscription(fmt.Errorf("meshsync data handlers are not configured for any of the contexts"))
		r.Log.Error(er)
		return nil, er
	}

	for _, connectionID := range connectionIDs {
		inst, ok := handler.ConnectionToStateMachineInstanceTracker.Get(uuid.FromStringOrNil(connectionID))
		if ok && inst != nil {
			machinectx, err := utils.Cast[*kubernetes.MachineCtx](inst.Context)
			if err != nil {
				r.Log.Error(model.ErrMesheryControllersStatusSubscription(err))
				continue
			}

			dataHandler := machinectx.MesheryCtrlsHelper.GetMeshSyncDataHandlersForEachContext()
			if dataHandler == nil {
				r.Log.Info("skipping meshsync events subscription for connection Id: %s", connectionID)
				r.Log.Info("connection to broker and datahandler is not yet initialised")
				continue
			}
			brokerEventsChan := make(chan *broker.Message)
			err = dataHandler.ListenToMeshSyncEvents(brokerEventsChan)
			if err != nil {
				r.Log.Warn(err)
				r.Log.Info("skipping meshsync events subscription for connection Id: %s", connectionID)
				continue
			}
			go func(connectionID string, brokerEventsChan chan *broker.Message) {
				publishHandlerWithProcessing := processAndRateLimitTheResponseOnGqlChannel(handler.MeshsyncChannel, resChan, r, 5*time.Second)
				for {
					select {
					case <-ctx.Done():
						return
					case event, ok := <-brokerEventsChan:
						if !ok {
							return
						}

						if event.EventType == broker.ErrorEvent || isSubscriptionFlushed.Load() { // better close the parent channel, but it is throwing panic
							// TODO: Handle errors accordingly
							continue
						}

						// skip event that UI doesn't want to listen to
						if !model.CheckIfBrokerEventExistsInArray(event.EventType, brokerEventTypes) {
							continue
						}

						// handle the events
						res := &model.MeshSyncEvent{
							ConnectionID: connectionID,
							Type:         string(event.EventType),
							Object:       event.Object,
						}
						publishHandlerWithProcessing(res)
					}
				}
			}(connectionID, brokerEventsChan)
		}
	}

	// handle subscription dispose
	go func() {
		<-ctx.Done() // executes when the subscription is dumped
		isSubscriptionFlushed.Store(true)
	}()

	return resChan, nil
}
func (r *queryResolver) GetClusterResources(ctx context.Context, k8scontextIDs []string, namespace string) (*model.ClusterResources, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	return r.getClusterResources(ctx, provider, k8scontextIDs, namespace)
}
func (r *subscriptionResolver) ListenToAddonState(ctx context.Context, filter *model.ServiceMeshFilter) (<-chan []*model.AddonList, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	if filter != nil {
		return r.listenToAddonState(ctx, provider, filter)
	}

	return nil, ErrInvalidRequest
}
func (r *subscriptionResolver) ListenToControlPlaneState(ctx context.Context, filter *model.ServiceMeshFilter) (<-chan []*model.ControlPlane, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	if filter != nil {
		return r.listenToControlPlaneState(ctx, provider, filter)
	}

	return nil, ErrInvalidRequest
}
func (r *subscriptionResolver) ListenToDataPlaneState(ctx context.Context, filter *model.ServiceMeshFilter) (<-chan []*model.DataPlane, error) {
	provider := ctx.Value(models.ProviderCtxKey).(models.Provider)
	if filter != nil {
		return r.listenToDataPlaneState(ctx, provider, filter)
	}

	return nil, ErrInvalidRequest
}
func processAndRateLimitTheResponseOnGqlChannel(meshsyncChan chan struct{}, publishChannel chan *model.MeshSyncEvent, r *subscriptionResolver, d time.Duration) func(meshsyncEvent *model.MeshSyncEvent) {
	type syncedProcessMap struct {
		mu         sync.Mutex
		processMap map[string]*model.MeshSyncEvent
		flushing   bool
	}

	processMap := syncedProcessMap{processMap: make(map[string]*model.MeshSyncEvent)}

	return func(meshsyncEvent *model.MeshSyncEvent) {
		// create a key to uniquely identify meshsync objects with its type, context and resource uid (if present)
		var b strings.Builder
		b.WriteString(meshsyncEvent.Type)
		b.WriteByte(':')
		b.WriteString(meshsyncEvent.ConnectionID)
		if objMap, ok := meshsyncEvent.Object.(map[string]interface{}); ok {
			if kindVal, ok := objMap["kind"]; ok {
				b.WriteByte(':')
				_, _ = fmt.Fprint(&b, kindVal)
			}
			if metadataVal, ok := objMap["metadata"]; ok {
				if metadataMap, ok := metadataVal.(map[string]interface{}); ok {
					if uidVal, ok := metadataMap["uid"]; ok && uidVal != nil {
						b.WriteByte(':')
						_, _ = fmt.Fprint(&b, uidVal)
					}
				}
			}
		}
		key := b.String()

		processMap.mu.Lock()
		processMap.processMap[key] = meshsyncEvent
		if processMap.flushing {
			processMap.mu.Unlock()
			return
		}
		processMap.flushing = true
		processMap.mu.Unlock()

		go func() {
			timer := time.NewTimer(d)
			defer timer.Stop()
			<-timer.C

			processMap.mu.Lock()
			items := make([]*model.MeshSyncEvent, 0, len(processMap.processMap))
			for k, v := range processMap.processMap {
				items = append(items, v)
				delete(processMap.processMap, k)
			}
			processMap.flushing = false
			processMap.mu.Unlock()

			for _, v := range items {
				publishChannel <- v
				go r.Config.DashboardK8sResourcesChan.PublishDashboardK8sResources()
				go func() { meshsyncChan <- struct{}{} }()
			}
		}()
	}
}
*/
