package main

import (
	//"bytes"
	"fmt"
	"io"
	"log"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
	//"gopkg.in/yaml.v2"

	"github.com/layer5io/meshery/mesheryctl/internal/cli/root"
	//"github.com/layer5io/meshery/mesheryctl/internal/cli/root/app"
	//"github.com/layer5io/meshery/mesheryctl/internal/cli/root/config"
	//"github.com/layer5io/meshery/mesheryctl/internal/cli/root/experimental"
	//"github.com/layer5io/meshery/mesheryctl/internal/cli/root/mesh"
	//"github.com/layer5io/meshery/mesheryctl/internal/cli/root/pattern"
	//"github.com/layer5io/meshery/mesheryctl/internal/cli/root/perf"
	//"github.com/layer5io/meshery/mesheryctl/internal/cli/root/system"
)

const markdownTemplateCommand = `---
layout: default
title: %s
permalink: /%s
redirect_from: /%s
type: reference
display-title: false
language: en
command: %s
---
`

const markdownTemplateSubcommand = `---
layout: default
title: %s
permalink: /%s
redirect_from: /%s
type: reference
display-title: false
language: en
command: %s
subcommand: %s
---
`

type cmdDoc struct {
	name        string
	description string
	usage       string   `yaml:",omitempty"`
	examples    []string `yaml:",omitempty"`
}

func prepender(filename string) string {
	title := filepath.Base(filename)
	base := strings.TrimSuffix(title, path.Ext(title))
	url := "reference/" + strings.ToLower(base) + "/"
	return fmt.Sprintf(markdownTemplateCommand, title, url, url, "test")
}

func linkHandler(name string) string {
	base := strings.TrimSuffix(name, path.Ext(name))
	return "reference/" + strings.ToLower(base) + "/"
}

func main() {
	markDownPath := "./internal/cli/root/testDoc/" //Sample path
	//yamlPath := "./internal/cli/root/testDoc/"

	fmt.Println("Scanning available commands...")
	cmd := root.TreePath() // Takes entire tree of mesheryctl commands

	// To skip the footer part "Auto generated by spf13/cobra.."
	cmd.DisableAutoGenTag = true

	fmt.Println("Generating markdown docs...")

	err := GenMarkdownTreeCustom(cmd, markDownPath, prepender, linkHandler)

	if err != nil {
		log.Fatal(err)
	}
}

// Custom function to generate markdown docs with '-' as separator
func GenMarkdownTreeCustom(cmd *cobra.Command, dir string, filePrepender, linkHandler func(string) string) error {
	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		if err := GenMarkdownTreeCustom(c, dir, filePrepender, linkHandler); err != nil {
			return err
		}
	}

	basename := strings.Replace(cmd.CommandPath(), " ", "-", -1) + ".md"
	filename := filepath.Join(dir, basename)
	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer f.Close()

	if _, err := io.WriteString(f, filePrepender(filename)); err != nil {
		return err
	}
	if err := doc.GenMarkdownCustom(cmd, f, linkHandler); err != nil {
		return err
	}
	return nil
}

/*
func GenYaml(cmd *cobra.Command, w io.Writer) error {
	return GenYamlCustom(cmd, w, func (s string) string  {
		return s
	})
}

func GenYamlCustom(cmd *cobra.Command, w io.Writer, linkHandler string) error {
	yaml := cmdDoc{}
	yaml.name = cmd.CommandPath()
	yaml.description = forceMultiLine(cmd.Long)
	yaml.usage = forceString(cmd.Use)
	if len(cmd.Example) > 0 {
		yaml.examples = strings.Split(cmd.Example, "\n")
	}

	final, err := yaml.Marshal(&yamlDoc)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	if _, err := w.Write(final); err != nil {
		return err
	}
	return nil
}
*/
