// Code generated by install/scripts/sync-provider-urls.py from install/providers.env; DO NOT EDIT.

package utils

// DefaultProviderBaseURLs is the canonical comma-joined list of Meshery's active
// remote providers, compiled into mesheryctl as the fallback used when the install
// docker-compose file cannot be downloaded.
const DefaultProviderBaseURLs = "https://cloud.meshery.io,https://cloud.layer5.io"
