// Code generated by install/scripts/sync-provider-urls.py from install/providers.env; DO NOT EDIT.

package utils

// Meshery Extension Point
// ---
// Purpose: List of active remote providers to be compiled into mesheryctl
// as the fallback used when the install docker-compose file cannot
// be downloaded.
// Learn more: See https://docs.meshery.io/extensibility
// Add your provider: https://github.com/meshery/meshery/issues/new/choose
// ---

// DefaultProviderBaseURLs is generated list of Meshery's active
// remote providers, compiled into mesheryctl as the fallback used when the
// install docker-compose file cannot be downloaded.
const DefaultProviderBaseURLs = "https://cloud.meshery.io,https://perf.smp-spec.io,https://cloud.layer5.io,https://meshery.tcs-labs.in"
