#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


if [ -e "$(dirname "$0")/../package-lock.json" ]
then
  echo  "[Husky] Looks like you have used npm for installing dependencies 😅 "
  echo "[Husky] Please remove package-lock.json and use yarn for installing dependenies 🙌 "
  exit 2 
else
  cd ui && yarn lint-staged
fi

