// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: meshops.proto

package meshes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpCategory int32

const (
	OpCategory_INSTALL            OpCategory = 0
	OpCategory_SAMPLE_APPLICATION OpCategory = 1
	OpCategory_CONFIGURE          OpCategory = 2
	OpCategory_VALIDATE           OpCategory = 3
	OpCategory_CUSTOM             OpCategory = 4
)

// Enum value maps for OpCategory.
var (
	OpCategory_name = map[int32]string{
		0: "INSTALL",
		1: "SAMPLE_APPLICATION",
		2: "CONFIGURE",
		3: "VALIDATE",
		4: "CUSTOM",
	}
	OpCategory_value = map[string]int32{
		"INSTALL":            0,
		"SAMPLE_APPLICATION": 1,
		"CONFIGURE":          2,
		"VALIDATE":           3,
		"CUSTOM":             4,
	}
)

func (x OpCategory) Enum() *OpCategory {
	p := new(OpCategory)
	*p = x
	return p
}

func (x OpCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_meshops_proto_enumTypes[0].Descriptor()
}

func (OpCategory) Type() protoreflect.EnumType {
	return &file_meshops_proto_enumTypes[0]
}

func (x OpCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpCategory.Descriptor instead.
func (OpCategory) EnumDescriptor() ([]byte, []int) {
	return file_meshops_proto_rawDescGZIP(), []int{0}
}

type EventType int32

const (
	EventType_INFO  EventType = 0
	EventType_WARN  EventType = 1
	EventType_ERROR EventType = 2
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "INFO",
		1: "WARN",
		2: "ERROR",
	}
	EventType_value = map[string]int32{
		"INFO":  0,
		"WARN":  1,
		"ERROR": 2,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_meshops_proto_enumTypes[1].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_meshops_proto_enumTypes[1]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_meshops_proto_rawDescGZIP(), []int{1}
}

type MeshNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MeshNameRequest) Reset() {
	*x = MeshNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshops_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeshNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshNameRequest) ProtoMessage() {}

func (x *MeshNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshops_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshNameRequest.ProtoReflect.Descriptor instead.
func (*MeshNameRequest) Descriptor() ([]byte, []int) {
	return file_meshops_proto_rawDescGZIP(), []int{0}
}

type MeshNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *MeshNameResponse) Reset() {
	*x = MeshNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshops_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeshNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshNameResponse) ProtoMessage() {}

func (x *MeshNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshops_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshNameResponse.ProtoReflect.Descriptor instead.
func (*MeshNameResponse) Descriptor() ([]byte, []int) {
	return file_meshops_proto_rawDescGZIP(), []int{1}
}

func (x *MeshNameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ApplyRuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpName      string   `protobuf:"bytes,1,opt,name=opName,proto3" json:"opName,omitempty"`
	Namespace   string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Username    string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	CustomBody  string   `protobuf:"bytes,4,opt,name=custom_body,json=customBody,proto3" json:"custom_body,omitempty"`
	DeleteOp    bool     `protobuf:"varint,5,opt,name=delete_op,json=deleteOp,proto3" json:"delete_op,omitempty"`
	OperationId string   `protobuf:"bytes,6,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	KubeConfigs []string `protobuf:"bytes,7,rep,name=kube_configs,json=kubeConfigs,proto3" json:"kube_configs,omitempty"`
}

func (x *ApplyRuleRequest) Reset() {
	*x = ApplyRuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshops_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRuleRequest) ProtoMessage() {}

func (x *ApplyRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshops_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRuleRequest.ProtoReflect.Descriptor instead.
func (*ApplyRuleRequest) Descriptor() ([]byte, []int) {
	return file_meshops_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyRuleRequest) GetOpName() string {
	if x != nil {
		return x.OpName
	}
	return ""
}

func (x *ApplyRuleRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ApplyRuleRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ApplyRuleRequest) GetCustomBody() string {
	if x != nil {
		return x.CustomBody
	}
	return ""
}

func (x *ApplyRuleRequest) GetDeleteOp() bool {
	if x != nil {
		return x.DeleteOp
	}
	return false
}

func (x *ApplyRuleRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ApplyRuleRequest) GetKubeConfigs() []string {
	if x != nil {
		return x.KubeConfigs
	}
	return nil
}

type ApplyRuleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error       string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	OperationId string `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
}

func (x *ApplyRuleResponse) Reset() {
	*x = ApplyRuleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshops_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRuleResponse) ProtoMessage() {}

func (x *ApplyRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshops_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRuleResponse.ProtoReflect.Descriptor instead.
func (*ApplyRuleResponse) Descriptor() ([]byte, []int) {
	return file_meshops_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyRuleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ApplyRuleResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type SupportedOperationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SupportedOperationsRequest) Reset() {
	*x = SupportedOperationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshops_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupportedOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedOperationsRequest) ProtoMessage() {}

func (x *SupportedOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshops_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedOperationsRequest.ProtoReflect.Descriptor instead.
func (*SupportedOperationsRequest) Descriptor() ([]byte, []int) {
	return file_meshops_proto_rawDescGZIP(), []int{4}
}

type SupportedOperationsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ops   []*SupportedOperation `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty"`
	Error string                `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SupportedOperationsResponse) Reset() {
	*x = SupportedOperationsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshops_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupportedOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedOperationsResponse) ProtoMessage() {}

func (x *SupportedOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshops_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedOperationsResponse.ProtoReflect.Descriptor instead.
func (*SupportedOperationsResponse) Descriptor() ([]byte, []int) {
	return file_meshops_proto_rawDescGZIP(), []int{5}
}

func (x *SupportedOperationsResponse) GetOps() []*SupportedOperation {
	if x != nil {
		return x.Ops
	}
	return nil
}

func (x *SupportedOperationsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SupportedOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      string     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value    string     `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Category OpCategory `protobuf:"varint,3,opt,name=category,proto3,enum=meshes.OpCategory" json:"category,omitempty"`
}

func (x *SupportedOperation) Reset() {
	*x = SupportedOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshops_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupportedOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedOperation) ProtoMessage() {}

func (x *SupportedOperation) ProtoReflect() protoreflect.Message {
	mi := &file_meshops_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedOperation.ProtoReflect.Descriptor instead.
func (*SupportedOperation) Descriptor() ([]byte, []int) {
	return file_meshops_proto_rawDescGZIP(), []int{6}
}

func (x *SupportedOperation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SupportedOperation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SupportedOperation) GetCategory() OpCategory {
	if x != nil {
		return x.Category
	}
	return OpCategory_INSTALL
}

type EventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EventsRequest) Reset() {
	*x = EventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshops_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest) ProtoMessage() {}

func (x *EventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshops_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest.ProtoReflect.Descriptor instead.
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return file_meshops_proto_rawDescGZIP(), []int{7}
}

type EventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType            EventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=meshes.EventType" json:"event_type,omitempty"`
	Summary              string    `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Details              string    `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	OperationId          string    `protobuf:"bytes,4,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ProbableCause        string    `protobuf:"bytes,5,opt,name=probable_cause,json=probableCause,proto3" json:"probable_cause,omitempty"`
	SuggestedRemediation string    `protobuf:"bytes,6,opt,name=suggested_remediation,json=suggestedRemediation,proto3" json:"suggested_remediation,omitempty"`
	ErrorCode            string    `protobuf:"bytes,7,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Component            string    `protobuf:"bytes,8,opt,name=component,proto3" json:"component,omitempty"`
	ComponentName        string    `protobuf:"bytes,9,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
}

func (x *EventsResponse) Reset() {
	*x = EventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshops_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse) ProtoMessage() {}

func (x *EventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshops_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse.ProtoReflect.Descriptor instead.
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return file_meshops_proto_rawDescGZIP(), []int{8}
}

func (x *EventsResponse) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_INFO
}

func (x *EventsResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *EventsResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *EventsResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *EventsResponse) GetProbableCause() string {
	if x != nil {
		return x.ProbableCause
	}
	return ""
}

func (x *EventsResponse) GetSuggestedRemediation() string {
	if x != nil {
		return x.SuggestedRemediation
	}
	return ""
}

func (x *EventsResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *EventsResponse) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *EventsResponse) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

type ProcessOAMRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username    string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	DeleteOp    bool     `protobuf:"varint,2,opt,name=delete_op,json=deleteOp,proto3" json:"delete_op,omitempty"`
	OamComps    []string `protobuf:"bytes,3,rep,name=oam_comps,json=oamComps,proto3" json:"oam_comps,omitempty"`
	OamConfig   string   `protobuf:"bytes,4,opt,name=oam_config,json=oamConfig,proto3" json:"oam_config,omitempty"`
	KubeConfigs []string `protobuf:"bytes,7,rep,name=kube_configs,json=kubeConfigs,proto3" json:"kube_configs,omitempty"`
}

func (x *ProcessOAMRequest) Reset() {
	*x = ProcessOAMRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshops_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessOAMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessOAMRequest) ProtoMessage() {}

func (x *ProcessOAMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshops_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessOAMRequest.ProtoReflect.Descriptor instead.
func (*ProcessOAMRequest) Descriptor() ([]byte, []int) {
	return file_meshops_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessOAMRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProcessOAMRequest) GetDeleteOp() bool {
	if x != nil {
		return x.DeleteOp
	}
	return false
}

func (x *ProcessOAMRequest) GetOamComps() []string {
	if x != nil {
		return x.OamComps
	}
	return nil
}

func (x *ProcessOAMRequest) GetOamConfig() string {
	if x != nil {
		return x.OamConfig
	}
	return ""
}

func (x *ProcessOAMRequest) GetKubeConfigs() []string {
	if x != nil {
		return x.KubeConfigs
	}
	return nil
}

type ProcessOAMResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ProcessOAMResponse) Reset() {
	*x = ProcessOAMResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshops_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessOAMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessOAMResponse) ProtoMessage() {}

func (x *ProcessOAMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshops_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessOAMResponse.ProtoReflect.Descriptor instead.
func (*ProcessOAMResponse) Descriptor() ([]byte, []int) {
	return file_meshops_proto_rawDescGZIP(), []int{10}
}

func (x *ProcessOAMResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MeshVersionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MeshVersionsRequest) Reset() {
	*x = MeshVersionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshops_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeshVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshVersionsRequest) ProtoMessage() {}

func (x *MeshVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshops_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshVersionsRequest.ProtoReflect.Descriptor instead.
func (*MeshVersionsRequest) Descriptor() ([]byte, []int) {
	return file_meshops_proto_rawDescGZIP(), []int{11}
}

type MeshVersionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version []string `protobuf:"bytes,1,rep,name=version,proto3" json:"version,omitempty"`
}

func (x *MeshVersionsResponse) Reset() {
	*x = MeshVersionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshops_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeshVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshVersionsResponse) ProtoMessage() {}

func (x *MeshVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshops_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshVersionsResponse.ProtoReflect.Descriptor instead.
func (*MeshVersionsResponse) Descriptor() ([]byte, []int) {
	return file_meshops_proto_rawDescGZIP(), []int{12}
}

func (x *MeshVersionsResponse) GetVersion() []string {
	if x != nil {
		return x.Version
	}
	return nil
}

// The idea is that all components' gRPC endpoint would provide a ComponentInfo function.
type ComponentInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ComponentInfoRequest) Reset() {
	*x = ComponentInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshops_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComponentInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentInfoRequest) ProtoMessage() {}

func (x *ComponentInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meshops_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentInfoRequest.ProtoReflect.Descriptor instead.
func (*ComponentInfoRequest) Descriptor() ([]byte, []int) {
	return file_meshops_proto_rawDescGZIP(), []int{13}
}

type ComponentInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       string            `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                                                                                     // the component type, e.g. "adapter", as all components might provide a ComponentInfo function
	Name       string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                                     // the component name, e.g. "kuma"
	Version    string            `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                                                                                               // the component version, e.g. v0.1.5
	GitSha     string            `protobuf:"bytes,4,opt,name=git_sha,json=gitSha,proto3" json:"git_sha,omitempty"`                                                                                   // the git commit sha
	Properties map[string]string `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // any other properties of interest
}

func (x *ComponentInfoResponse) Reset() {
	*x = ComponentInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meshops_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComponentInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentInfoResponse) ProtoMessage() {}

func (x *ComponentInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meshops_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentInfoResponse.ProtoReflect.Descriptor instead.
func (*ComponentInfoResponse) Descriptor() ([]byte, []int) {
	return file_meshops_proto_rawDescGZIP(), []int{14}
}

func (x *ComponentInfoResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ComponentInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ComponentInfoResponse) GetGitSha() string {
	if x != nil {
		return x.GitSha
	}
	return ""
}

func (x *ComponentInfoResponse) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

var File_meshops_proto protoreflect.FileDescriptor

var file_meshops_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x68, 0x6f, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x6d, 0x65, 0x73, 0x68, 0x65, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x68, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x26, 0x0a, 0x10, 0x4d, 0x65,
	0x73, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0xe8, 0x01, 0x0a, 0x10, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x75, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x5f, 0x6f, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6b, 0x75,
	0x62, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0b, 0x6b, 0x75, 0x62, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x22, 0x4c, 0x0a,
	0x11, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x1c, 0x0a, 0x1a, 0x53,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x61, 0x0a, 0x1b, 0x53, 0x75, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x03, 0x6f, 0x70, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x53,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x03, 0x6f, 0x70, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x6c, 0x0a, 0x12,
	0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d,
	0x65, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x4f, 0x70, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x0f, 0x0a, 0x0d, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xd9, 0x02, 0x0a, 0x0e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30,
	0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x62, 0x61,
	0x62, 0x6c, 0x65, 0x5f, 0x63, 0x61, 0x75, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x70, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x61, 0x75, 0x73, 0x65, 0x12, 0x33,
	0x0a, 0x15, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x73,
	0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x65, 0x64, 0x52, 0x65, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xab, 0x01, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x4f, 0x41, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x5f, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4f, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x61, 0x6d, 0x5f, 0x63, 0x6f,
	0x6d, 0x70, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x61, 0x6d, 0x43, 0x6f,
	0x6d, 0x70, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x61, 0x6d, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x61, 0x6d, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x6b, 0x75, 0x62, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x6b, 0x75, 0x62, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x73, 0x22, 0x2e, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x4f, 0x41, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x68, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x30, 0x0a, 0x14,
	0x4d, 0x65, 0x73, 0x68, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x16,
	0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x80, 0x02, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x70, 0x6f,
	0x6e, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x69, 0x74, 0x5f, 0x73, 0x68, 0x61, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x69, 0x74, 0x53, 0x68, 0x61, 0x12, 0x4d, 0x0a, 0x0a, 0x70,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2d, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0x5a, 0x0a, 0x0a, 0x4f, 0x70, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x53, 0x54, 0x41,
	0x4c, 0x4c, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x41, 0x4d, 0x50, 0x4c, 0x45, 0x5f, 0x41,
	0x50, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09,
	0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x55, 0x52, 0x45, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x41, 0x54, 0x45, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x55, 0x53,
	0x54, 0x4f, 0x4d, 0x10, 0x04, 0x2a, 0x2a, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x57, 0x41, 0x52, 0x4e, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0x02, 0x32, 0xa0, 0x04, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3f, 0x0a, 0x08, 0x4d, 0x65, 0x73, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x2e,
	0x6d, 0x65, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x65, 0x73, 0x2e,
	0x4d, 0x65, 0x73, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x4d, 0x65, 0x73, 0x68, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x1b, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x68,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x68, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x47, 0x0a, 0x0e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79,
	0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x65,
	0x73, 0x68, 0x65, 0x73, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x60, 0x0a, 0x13, 0x53, 0x75, 0x70, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x22, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x65, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x53, 0x75, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0c, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x15, 0x2e, 0x6d, 0x65, 0x73,
	0x68, 0x65, 0x73, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x45, 0x0a,
	0x0a, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4f, 0x41, 0x4d, 0x12, 0x19, 0x2e, 0x6d, 0x65,
	0x73, 0x68, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4f, 0x41, 0x4d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x65, 0x73, 0x2e,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4f, 0x41, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6d,
	0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x35, 0x69, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x68,
	0x65, 0x72, 0x79, 0x2f, 0x6d, 0x65, 0x73, 0x68, 0x65, 0x73, 0x3b, 0x6d, 0x65, 0x73, 0x68, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meshops_proto_rawDescOnce sync.Once
	file_meshops_proto_rawDescData = file_meshops_proto_rawDesc
)

func file_meshops_proto_rawDescGZIP() []byte {
	file_meshops_proto_rawDescOnce.Do(func() {
		file_meshops_proto_rawDescData = protoimpl.X.CompressGZIP(file_meshops_proto_rawDescData)
	})
	return file_meshops_proto_rawDescData
}

var file_meshops_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_meshops_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_meshops_proto_goTypes = []interface{}{
	(OpCategory)(0),                     // 0: meshes.OpCategory
	(EventType)(0),                      // 1: meshes.EventType
	(*MeshNameRequest)(nil),             // 2: meshes.MeshNameRequest
	(*MeshNameResponse)(nil),            // 3: meshes.MeshNameResponse
	(*ApplyRuleRequest)(nil),            // 4: meshes.ApplyRuleRequest
	(*ApplyRuleResponse)(nil),           // 5: meshes.ApplyRuleResponse
	(*SupportedOperationsRequest)(nil),  // 6: meshes.SupportedOperationsRequest
	(*SupportedOperationsResponse)(nil), // 7: meshes.SupportedOperationsResponse
	(*SupportedOperation)(nil),          // 8: meshes.SupportedOperation
	(*EventsRequest)(nil),               // 9: meshes.EventsRequest
	(*EventsResponse)(nil),              // 10: meshes.EventsResponse
	(*ProcessOAMRequest)(nil),           // 11: meshes.ProcessOAMRequest
	(*ProcessOAMResponse)(nil),          // 12: meshes.ProcessOAMResponse
	(*MeshVersionsRequest)(nil),         // 13: meshes.MeshVersionsRequest
	(*MeshVersionsResponse)(nil),        // 14: meshes.MeshVersionsResponse
	(*ComponentInfoRequest)(nil),        // 15: meshes.ComponentInfoRequest
	(*ComponentInfoResponse)(nil),       // 16: meshes.ComponentInfoResponse
	nil,                                 // 17: meshes.ComponentInfoResponse.PropertiesEntry
}
var file_meshops_proto_depIdxs = []int32{
	8,  // 0: meshes.SupportedOperationsResponse.ops:type_name -> meshes.SupportedOperation
	0,  // 1: meshes.SupportedOperation.category:type_name -> meshes.OpCategory
	1,  // 2: meshes.EventsResponse.event_type:type_name -> meshes.EventType
	17, // 3: meshes.ComponentInfoResponse.properties:type_name -> meshes.ComponentInfoResponse.PropertiesEntry
	2,  // 4: meshes.MeshService.MeshName:input_type -> meshes.MeshNameRequest
	13, // 5: meshes.MeshService.MeshVersions:input_type -> meshes.MeshVersionsRequest
	4,  // 6: meshes.MeshService.ApplyOperation:input_type -> meshes.ApplyRuleRequest
	6,  // 7: meshes.MeshService.SupportedOperations:input_type -> meshes.SupportedOperationsRequest
	9,  // 8: meshes.MeshService.StreamEvents:input_type -> meshes.EventsRequest
	11, // 9: meshes.MeshService.ProcessOAM:input_type -> meshes.ProcessOAMRequest
	15, // 10: meshes.MeshService.ComponentInfo:input_type -> meshes.ComponentInfoRequest
	3,  // 11: meshes.MeshService.MeshName:output_type -> meshes.MeshNameResponse
	14, // 12: meshes.MeshService.MeshVersions:output_type -> meshes.MeshVersionsResponse
	5,  // 13: meshes.MeshService.ApplyOperation:output_type -> meshes.ApplyRuleResponse
	7,  // 14: meshes.MeshService.SupportedOperations:output_type -> meshes.SupportedOperationsResponse
	10, // 15: meshes.MeshService.StreamEvents:output_type -> meshes.EventsResponse
	12, // 16: meshes.MeshService.ProcessOAM:output_type -> meshes.ProcessOAMResponse
	16, // 17: meshes.MeshService.ComponentInfo:output_type -> meshes.ComponentInfoResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_meshops_proto_init() }
func file_meshops_proto_init() {
	if File_meshops_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meshops_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeshNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshops_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeshNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshops_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyRuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshops_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyRuleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshops_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupportedOperationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshops_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupportedOperationsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshops_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupportedOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshops_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshops_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshops_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessOAMRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshops_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessOAMResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshops_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeshVersionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshops_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeshVersionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshops_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComponentInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meshops_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComponentInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meshops_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meshops_proto_goTypes,
		DependencyIndexes: file_meshops_proto_depIdxs,
		EnumInfos:         file_meshops_proto_enumTypes,
		MessageInfos:      file_meshops_proto_msgTypes,
	}.Build()
	File_meshops_proto = out.File
	file_meshops_proto_rawDesc = nil
	file_meshops_proto_goTypes = nil
	file_meshops_proto_depIdxs = nil
}
