// Copyright Meshery Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/meshery/meshery/mesheryctl/internal/cli/root"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	"gopkg.in/yaml.v3"
)

// GenMarkdownTreeCustom is a modified version of GenMarkdownTree from spf13/cobra
const markdownTemplateCommand = `---
title: %s
display_title: false
command: %s
subcommand: %s
---

`

// prepender is a function to prepend the frontmatter to the markdown file
func prepender(filename string) string {
	idx := strings.Index(filename, "mesheryctl")
	if idx == -1 {
		base := strings.TrimSuffix(filepath.Base(filename), ".md")
		return fmt.Sprintf(markdownTemplateCommand, base, base, "nil")
	}

	relPath := strings.TrimSuffix(filename[idx:], ".md")
	parts := strings.Split(relPath, string(os.PathSeparator))

	if len(parts) == 0 {
		return ""
	}

	if parts[len(parts)-1] == "_index" {
		parts = parts[:len(parts)-1]
	}

	var command, subcommand string

	if len(parts) == 1 {
		command = parts[0]
		subcommand = "nil"
	} else if len(parts) == 2 {
		command = parts[1] // Set the first part as the command
		subcommand = "nil" // Root command has no subcommand
	} else {
		command = parts[1]    // Set the first part as the command
		subcommand = parts[2] // Set the second part as the subcommand
	}

	title := strings.Join(parts, "-")

	return fmt.Sprintf(markdownTemplateCommand,
		title,
		command,
		subcommand,
	)
}

func linkHandler(name string) string {
	// Normalize path
	name = filepath.ToSlash(name)

	// Find the reference root
	idx := strings.Index(name, "reference/mesheryctl")
	if idx == -1 {
		return ""
	}

	// Trim everything before reference/mesheryctl
	trimmed := name[idx:]

	// Remove file extension
	trimmed = strings.TrimSuffix(trimmed, path.Ext(trimmed))

	// Remove trailing _index
	trimmed = strings.TrimSuffix(trimmed, "/_index")

	// Ensure leading slash
	if !strings.HasPrefix(trimmed, "/") {
		trimmed = "/" + trimmed
	}

	return trimmed
}

// docs is a function to generate the markdown docs for mesheryctl
func doc() {
	markDownPath := "../../docs/content/en/reference/mesheryctl/" // Path for docs
	commandDataPath := "../../docs/data/mesheryctlcommands/cmds.yml"
	//yamlPath := "./internal/cli/root/testDoc/"

	fmt.Println("Scanning available commands...")
	cmd := root.TreePath() // Takes entire tree of mesheryctl commands

	// To skip the footer part "Auto generated by spf13/cobra.."
	cmd.DisableAutoGenTag = true

	fmt.Println("Generating command data...")

	err := GenerateCommandData(cmd, commandDataPath)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("Command data generated at " + commandDataPath)

	fmt.Println("Generating markdown docs...")

	err = GenMarkdownTreeCustom(cmd, markDownPath, prepender, linkHandler)

	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("Documentation generated at " + markDownPath)
}

type commandDataFile struct {
	Order    []string
	Commands map[string]commandData
}

type commandData struct {
	Key         string
	Name        string
	Description string
	Usage       string
	URL         string
	Flags       []flagData
	Subcommands []commandData
}

type flagData struct {
	Key         string
	Name        string
	Description string
}

var preferredTopLevelCommandOrder = []string{
	"system",
	"adapter",
	"perf",
	"design",
	"filter",
	"model",
	"component",
	"registry",
	"environment",
	"connection",
	"organization",
	"relationship",
	"workspace",
	"exp",
}

var globalOnlyRootCommands = map[string]bool{
	"completion": true,
	"version":    true,
}

// GenerateCommandData writes Hugo data for the mesheryctl command reference page.
func GenerateCommandData(cmd *cobra.Command, outputPath string) error {
	cmd.InitDefaultHelpFlag()

	commandFile := commandDataFile{
		Order:    []string{"global"},
		Commands: make(map[string]commandData),
	}

	rootCommand := buildCommandData(cmd, "global", true)
	rootCommand.Subcommands = rootLevelLeafCommands(cmd)
	commandFile.Commands["global"] = rootCommand

	topLevelCommands := rootLevelCommandGroups(cmd)
	knownTopLevelCommands := make(map[string]commandData, len(topLevelCommands))
	for _, command := range topLevelCommands {
		knownTopLevelCommands[command.Key] = command
	}

	for _, key := range preferredTopLevelCommandOrder {
		command, ok := knownTopLevelCommands[key]
		if !ok {
			continue
		}
		commandFile.Order = append(commandFile.Order, key)
		commandFile.Commands[key] = command
		delete(knownTopLevelCommands, key)
	}

	remainingKeys := make([]string, 0, len(knownTopLevelCommands))
	for key := range knownTopLevelCommands {
		remainingKeys = append(remainingKeys, key)
	}
	sort.Strings(remainingKeys)
	for _, key := range remainingKeys {
		commandFile.Order = append(commandFile.Order, key)
		commandFile.Commands[key] = knownTopLevelCommands[key]
	}

	return writeCommandDataFile(commandFile, outputPath)
}

func rootLevelCommandGroups(cmd *cobra.Command) []commandData {
	commands := availableSubcommands(cmd)
	commandGroups := make([]commandData, 0, len(commands))
	for _, command := range commands {
		if globalOnlyRootCommands[commandWord(command)] {
			continue
		}
		key := commandWord(command)
		commandGroups = append(commandGroups, buildCommandData(command, key, false))
	}
	return commandGroups
}

func rootLevelLeafCommands(cmd *cobra.Command) []commandData {
	commands := availableSubcommands(cmd)
	leafCommands := make([]commandData, 0, len(commands))
	for _, command := range commands {
		if !globalOnlyRootCommands[commandWord(command)] {
			continue
		}
		key := commandWord(command)
		leafCommands = append(leafCommands, buildCommandData(command, key, false))
	}
	return leafCommands
}

func buildCommandData(cmd *cobra.Command, key string, includeHelpFlag bool) commandData {
	data := commandData{
		Key:         key,
		Name:        commandWord(cmd),
		Description: commandDescription(cmd),
		Usage:       cmd.UseLine(),
		URL:         referenceURL(cmd),
		Flags:       commandFlags(cmd, includeHelpFlag),
	}

	for _, command := range availableSubcommands(cmd) {
		data.Subcommands = append(data.Subcommands, buildCommandData(command, commandWord(command), false))
	}

	return data
}

func availableSubcommands(cmd *cobra.Command) []*cobra.Command {
	commands := make([]*cobra.Command, 0, len(cmd.Commands()))
	for _, command := range cmd.Commands() {
		if !command.IsAvailableCommand() || command.IsAdditionalHelpTopicCommand() {
			continue
		}
		commands = append(commands, command)
	}

	sort.SliceStable(commands, func(i, j int) bool {
		return commandWord(commands[i]) < commandWord(commands[j])
	})

	return commands
}

func commandWord(cmd *cobra.Command) string {
	fields := strings.Fields(cmd.Use)
	if len(fields) > 0 {
		return fields[0]
	}
	return cmd.Name()
}

func commandDescription(cmd *cobra.Command) string {
	if strings.TrimSpace(cmd.Short) != "" {
		return strings.TrimSpace(cmd.Short)
	}

	long := strings.TrimSpace(cmd.Long)
	if long == "" {
		return ""
	}

	lines := strings.Split(long, "\n")
	return strings.TrimSpace(lines[0])
}

func commandFlags(cmd *cobra.Command, includeHelpFlag bool) []flagData {
	flags := make([]flagData, 0)
	nonInheritedFlags := cmd.NonInheritedFlags()
	if nonInheritedFlags == nil {
		return flags
	}

	nonInheritedFlags.VisitAll(func(flag *pflag.Flag) {
		if flag.Hidden {
			return
		}
		if flag.Name == "help" && !includeHelpFlag {
			return
		}
		flags = append(flags, flagData{
			Key:         flagKey(flag),
			Name:        renderedFlagName(flag),
			Description: flag.Usage,
		})
	})

	return flags
}

func flagKey(flag *pflag.Flag) string {
	if flag.Name != "" {
		return normalizeKey(flag.Name)
	}
	if flag.Shorthand != "" {
		return normalizeKey(flag.Shorthand)
	}
	return normalizeKey(renderedFlagName(flag))
}

func renderedFlagName(flag *pflag.Flag) string {
	if flag.Name != "" && flag.Shorthand != "" {
		return fmt.Sprintf("--%s, -%s", flag.Name, flag.Shorthand)
	}
	if flag.Name != "" {
		return fmt.Sprintf("--%s", flag.Name)
	}
	if flag.Shorthand != "" {
		return fmt.Sprintf("-%s", flag.Shorthand)
	}
	return ""
}

func normalizeKey(key string) string {
	key = strings.TrimLeft(key, "-")
	key = strings.TrimSpace(strings.ToLower(key))
	key = strings.ReplaceAll(key, " ", "-")
	return key
}

func referenceURL(cmd *cobra.Command) string {
	words := commandPathWords(cmd)
	if len(words) <= 1 {
		return "/reference/mesheryctl/"
	}
	return "/reference/mesheryctl/" + strings.Join(words[1:], "/") + "/"
}

func commandPathWords(cmd *cobra.Command) []string {
	words := []string{}
	for command := cmd; command != nil; command = command.Parent() {
		words = append([]string{commandWord(command)}, words...)
	}
	return words
}

func writeCommandDataFile(commandFile commandDataFile, outputPath string) error {
	if err := os.MkdirAll(filepath.Dir(outputPath), os.ModePerm); err != nil {
		return err
	}

	var output bytes.Buffer
	output.WriteString("# Code generated by mesheryctl/doc/doc.go; DO NOT EDIT.\n")
	output.WriteString("# Run: cd mesheryctl && make docs\n")

	encoder := yaml.NewEncoder(&output)
	encoder.SetIndent(2)
	if err := encoder.Encode(commandDataFileNode(commandFile)); err != nil {
		return err
	}
	if err := encoder.Close(); err != nil {
		return err
	}

	return os.WriteFile(outputPath, output.Bytes(), 0644)
}

func commandDataFileNode(commandFile commandDataFile) *yaml.Node {
	root := mappingNode()
	appendKeyValue(root, "order", stringSequenceNode(commandFile.Order))

	commands := mappingNode()
	for _, key := range commandFile.Order {
		command, ok := commandFile.Commands[key]
		if !ok {
			continue
		}
		appendKeyValue(commands, key, commandNode(command))
	}
	appendKeyValue(root, "commands", commands)

	return root
}

func commandNode(command commandData) *yaml.Node {
	node := mappingNode()
	appendStringKeyValue(node, "key", command.Key)
	appendStringKeyValue(node, "name", command.Name)
	appendStringKeyValue(node, "description", command.Description)
	appendStringKeyValue(node, "usage", command.Usage)
	appendStringKeyValue(node, "url", command.URL)
	if len(command.Flags) > 0 {
		appendKeyValue(node, "flags", flagsNode(command.Flags))
	}
	if len(command.Subcommands) > 0 {
		subcommands := sequenceNode()
		for _, subcommand := range command.Subcommands {
			subcommands.Content = append(subcommands.Content, commandNode(subcommand))
		}
		appendKeyValue(node, "subcommands", subcommands)
	}
	return node
}

func flagsNode(flags []flagData) *yaml.Node {
	node := sequenceNode()
	for _, flag := range flags {
		flagNode := mappingNode()
		appendStringKeyValue(flagNode, "key", flag.Key)
		appendStringKeyValue(flagNode, "name", flag.Name)
		appendStringKeyValue(flagNode, "description", flag.Description)
		node.Content = append(node.Content, flagNode)
	}
	return node
}

func stringSequenceNode(values []string) *yaml.Node {
	node := sequenceNode()
	for _, value := range values {
		node.Content = append(node.Content, scalarNode(value))
	}
	return node
}

func mappingNode() *yaml.Node {
	return &yaml.Node{Kind: yaml.MappingNode}
}

func sequenceNode() *yaml.Node {
	return &yaml.Node{Kind: yaml.SequenceNode}
}

func appendStringKeyValue(node *yaml.Node, key, value string) {
	if value == "" {
		return
	}
	appendKeyValue(node, key, scalarNode(value))
}

func appendKeyValue(node *yaml.Node, key string, value *yaml.Node) {
	node.Content = append(node.Content, scalarNode(key), value)
}

func scalarNode(value string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Value: value}
}

// printOptions prints the options for a command
func printOptions(buf *bytes.Buffer, cmd *cobra.Command) error {
	flags := cmd.NonInheritedFlags()
	flags.SetOutput(buf)
	if flags.HasAvailableFlags() {
		buf.WriteString("## Options\n\n<pre class='codeblock-pre'>\n<div class='codeblock'>\n")
		flags.PrintDefaults()
		buf.WriteString("\n</div>\n</pre>\n\n")
	}

	parentFlags := cmd.InheritedFlags()
	parentFlags.SetOutput(buf)
	if parentFlags.HasAvailableFlags() {
		buf.WriteString("## Options inherited from parent commands\n\n<pre class='codeblock-pre'>\n<div class='codeblock'>\n")
		parentFlags.PrintDefaults()
		buf.WriteString("\n</div>\n</pre>\n\n")
	}
	return nil
}

// GenMarkdownCustom creates custom markdown output.
func GenMarkdownCustom(cmd *cobra.Command, w io.Writer, manuallyAddedContent map[int]string) error {
	// InitDefaultHelpCmd add the help command to the command tree.
	cmd.InitDefaultHelpCmd()
	// InitDefaultHelpFlag add the help flag to the command tree.
	cmd.InitDefaultHelpFlag()

	buf := new(bytes.Buffer)
	// CommandPath returns the full path to this command.
	name := cmd.CommandPath()

	buf.WriteString("# " + name + "\n\n")
	buf.WriteString(cmd.Short + "\n\n")
	if len(cmd.Long) > 0 {
		buf.WriteString("## Synopsis\n\n")
		longContent := cmd.Long
		// Since the long description is used for synopsis, we need to remove the "Find more information at:" line
		findIndex := strings.Index(longContent, "Find")
		if findIndex != -1 {
			buf.WriteString(longContent[:findIndex])
		} else {
			buf.WriteString(longContent)
		}
		buf.WriteString("\n")
	}

	// check if the command is runnable
	if cmd.Runnable() {
		fmt.Fprintf(buf, "<pre class='codeblock-pre'>\n<div class='codeblock'>\n%s\n\n</div>\n</pre> \n\n", cmd.UseLine())
	}

	// check cmd has annotations link and caption
	picLine, ok := cmd.Annotations["link"]
	if !ok {
		picLine = ""
	}
	picComment, ok := cmd.Annotations["caption"]
	if !ok {
		picComment = ""
	}

	// check if cmd has example
	if len(cmd.Example) > 0 {
		buf.WriteString("## Examples\n\n")
		var examples = strings.Split(cmd.Example, "\n")
		for i := 0; i < len(examples); i++ {
			if examples[i] != "" && examples[i] != " " && examples[i] != "	" {
				if strings.HasPrefix(examples[i], "//") {
					// Description Line
					buf.WriteString(strings.ReplaceAll(examples[i], "// ", "") + "\n")
				} else {
					// Code Block Line

					fmt.Fprintf(buf, "<pre class='codeblock-pre'>\n<div class='codeblock'>\n%s\n\n</div>\n</pre> \n\n", examples[i])
				}
			}
		}
	}

	if err := printOptions(buf, cmd); err != nil {
		return err
	}

	// If command has screenshot present
	if picLine != "" {
		buf.WriteString("## Screenshots\n\n")
		// Print Caption first
		buf.WriteString(picComment)
		buf.WriteString("\n")
		// Add markdown code for screenshot
		buf.WriteString(picLine)
		buf.WriteString("\n\n")
	}

	if len(manuallyAddedContent) > 0 {
		for _, content := range manuallyAddedContent {
			buf.WriteString("\n")
			buf.WriteString("{{< " + content + " >}}\n")
		}
	}

	if hasSeeAlso(cmd) {
		buf.WriteString("## See Also\n\n")
		if cmd.HasParent() {
			cmd.VisitParents(func(c *cobra.Command) {
				if c.DisableAutoGenTag {
					cmd.DisableAutoGenTag = c.DisableAutoGenTag
				}
			})
		}
		buf.WriteString("Go back to [command reference index](/reference/mesheryctl/), if you want to add content manually to the CLI documentation, please refer to the [instruction](/project/contributing/contributing-cli#preserving-manually-added-documentation) for guidance.")
		buf.WriteString("\n")
	}

	if !cmd.DisableAutoGenTag {
		buf.WriteString("###### Auto generated by spf13/cobra on " + time.Now().Format("2-Jan-2006") + "\n")
	}
	_, err := buf.WriteTo(w)
	return err
}

// hasSeeAlso checks if the command has any subcommands
func hasSeeAlso(cmd *cobra.Command) bool {
	if cmd.HasParent() {
		return true
	}
	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		return true
	}
	return false
}

// GenMarkdownTreeCustom creates custom markdown output.
func GenMarkdownTreeCustom(cmd *cobra.Command, dir string, filePrepender, linkHandler func(string) string) error {
	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		if err := GenMarkdownTreeCustom(c, dir, filePrepender, linkHandler); err != nil {
			return err
		}
	}

	pathParts := strings.Split(cmd.CommandPath(), " ")
	if len(pathParts) > 0 && pathParts[0] == "mesheryctl" {
		pathParts = pathParts[1:]
	}

	var currentDir string
	if cmd.HasAvailableSubCommands() {
		currentDir = filepath.Join(dir, filepath.Join(pathParts...))
		err := os.MkdirAll(currentDir, os.ModePerm)
		if err != nil {
			return err
		}
	} else {
		currentDir = dir
	}

	var filename string
	if cmd.HasAvailableSubCommands() {
		filename = filepath.Join(currentDir, "_index.md")
	} else {
		if len(pathParts) == 0 {
			filename = filepath.Join(dir, "_index.md")
		} else if len(pathParts) == 1 {
			filename = filepath.Join(dir, pathParts[0]+".md")
		} else {
			parentDirs := filepath.Join(pathParts[:len(pathParts)-1]...)
			filename = filepath.Join(dir, parentDirs, pathParts[len(pathParts)-1]+".md")
		}
	}

	// Skip overwriting the root _index.md file
	if filename == filepath.Join(dir, "_index.md") {
		return nil
	}

	manuallyAddedContent, _ := getManuallyAddedContentMap(filename)

	// Ensure the directory exists before creating the file
	err := os.MkdirAll(filepath.Dir(filename), os.ModePerm)
	if err != nil {
		return err
	}

	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer func() { _ = f.Close() }()

	_, err = io.WriteString(f, filePrepender(filename))
	if err != nil {
		return err
	}

	err = GenMarkdownCustom(cmd, f, manuallyAddedContent)
	if err != nil {
		return err
	}
	return nil
}

func getManuallyAddedContentMap(filename string) (map[int]string, error) {
	manuallyAddedContentMap := make(map[int]string)

	_, err := os.Stat(filename)
	if err != nil {
		return manuallyAddedContentMap, err
	}

	existingContent, err := os.ReadFile(filename)
	if err != nil {
		return manuallyAddedContentMap, err
	}

	content := string(existingContent)

	shortcodePattern := regexp.MustCompile(`\{\{<\s*([^>]+)\s*>\}\}`)
	shortcodeMatches := shortcodePattern.FindAllStringSubmatch(content, -1)
	for i, match := range shortcodeMatches {
		// Store the shortcode content in the map with order as the key
		manuallyAddedContentMap[i] = strings.TrimSpace(match[1])
	}
	return manuallyAddedContentMap, nil
}

func main() {
	doc()
}
