// Copyright Meshery Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/meshery/meshery/mesheryctl/internal/cli/root"
	"github.com/spf13/cobra"
)

// GenMarkdownTreeCustom is a modified version of GenMarkdownTree from spf13/cobra
const markdownTemplateCommand = `---
title: %s
display_title: false
command: %s
subcommand: %s
---

`

// prepender is a function to prepend the frontmatter to the markdown file
func prepender(filename string) string {
	idx := strings.Index(filename, "mesheryctl")
	if idx == -1 {
		base := strings.TrimSuffix(filepath.Base(filename), ".md")
		return fmt.Sprintf(markdownTemplateCommand, base, base, "nil")
	}

	relPath := strings.TrimSuffix(filename[idx:], ".md")
	parts := strings.Split(relPath, string(os.PathSeparator))

	if len(parts) == 0 {
		return ""
	}

	if parts[len(parts)-1] == "_index" {
		parts = parts[:len(parts)-1]
	}

	var command, subcommand string

	if len(parts) == 1 {
		command = parts[0]
		subcommand = "nil"
	} else if len(parts) == 2 {
		command = parts[1] // Set the first part as the command
		subcommand = "nil" // Root command has no subcommand
	} else {
		command = parts[1]    // Set the first part as the command
		subcommand = parts[2] // Set the second part as the subcommand
	}

	title := strings.Join(parts, "-")

	return fmt.Sprintf(markdownTemplateCommand,
		title,
		command,
		subcommand,
	)
}

func linkHandler(name string) string {
	// Normalize path
	name = filepath.ToSlash(name)

	// Find the reference root
	idx := strings.Index(name, "reference/mesheryctl")
	if idx == -1 {
		return ""
	}

	// Trim everything before reference/mesheryctl
	trimmed := name[idx:]

	// Remove file extension
	trimmed = strings.TrimSuffix(trimmed, path.Ext(trimmed))

	// Remove trailing _index
	trimmed = strings.TrimSuffix(trimmed, "/_index")

	// Ensure leading slash
	if !strings.HasPrefix(trimmed, "/") {
		trimmed = "/" + trimmed
	}

	return trimmed
}

// docs is a function to generate the markdown docs for mesheryctl
func doc() {
	markDownPath := "../../docs/content/en/reference/mesheryctl/" // Path for docs
	//yamlPath := "./internal/cli/root/testDoc/"

	fmt.Println("Scanning available commands...")
	cmd := root.TreePath() // Takes entire tree of mesheryctl commands

	// To skip the footer part "Auto generated by spf13/cobra.."
	cmd.DisableAutoGenTag = true

	fmt.Println("Generating markdown docs...")

	err := GenMarkdownTreeCustom(cmd, markDownPath, prepender, linkHandler)

	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("Documentation generated at " + markDownPath)
}

// printOptions prints the options for a command
func printOptions(buf *bytes.Buffer, cmd *cobra.Command) error {
	flags := cmd.NonInheritedFlags()
	flags.SetOutput(buf)
	if flags.HasAvailableFlags() {
		buf.WriteString("## Options\n\n<pre class='codeblock-pre'>\n<div class='codeblock'>\n")
		flags.PrintDefaults()
		buf.WriteString("\n</div>\n</pre>\n\n")
	}

	parentFlags := cmd.InheritedFlags()
	parentFlags.SetOutput(buf)
	if parentFlags.HasAvailableFlags() {
		buf.WriteString("## Options inherited from parent commands\n\n<pre class='codeblock-pre'>\n<div class='codeblock'>\n")
		parentFlags.PrintDefaults()
		buf.WriteString("\n</div>\n</pre>\n\n")
	}
	return nil
}

// GenMarkdownCustom creates custom markdown output.
func GenMarkdownCustom(cmd *cobra.Command, w io.Writer, manuallyAddedContent map[int]string) error {
	// InitDefaultHelpCmd add the help command to the command tree.
	cmd.InitDefaultHelpCmd()
	// InitDefaultHelpFlag add the help flag to the command tree.
	cmd.InitDefaultHelpFlag()

	buf := new(bytes.Buffer)
	// CommandPath returns the full path to this command.
	name := cmd.CommandPath()

	buf.WriteString("# " + name + "\n\n")
	buf.WriteString(cmd.Short + "\n\n")
	if len(cmd.Long) > 0 {
		buf.WriteString("## Synopsis\n\n")
		longContent := cmd.Long
		// Since the long description is used for synopsis, we need to remove the "Find more information at:" line
		findIndex := strings.Index(longContent, "Find")
		if findIndex != -1 {
			buf.WriteString(longContent[:findIndex])
		} else {
			buf.WriteString(longContent)
		}
		buf.WriteString("\n")
	}

	// check if the command is runnable
	if cmd.Runnable() {
		fmt.Fprintf(buf, "<pre class='codeblock-pre'>\n<div class='codeblock'>\n%s\n\n</div>\n</pre> \n\n", cmd.UseLine())
	}

	// check cmd has annotations link and caption
	picLine, ok := cmd.Annotations["link"]
	if !ok {
		picLine = ""
	}
	picComment, ok := cmd.Annotations["caption"]
	if !ok {
		picComment = ""
	}

	// check if cmd has example
	if len(cmd.Example) > 0 {
		buf.WriteString("## Examples\n\n")
		var examples = strings.Split(cmd.Example, "\n")
		for i := 0; i < len(examples); i++ {
			if examples[i] != "" && examples[i] != " " && examples[i] != "	" {
				if strings.HasPrefix(examples[i], "//") {
					// Description Line
					buf.WriteString(strings.ReplaceAll(examples[i], "// ", "") + "\n")
				} else {
					// Code Block Line

					fmt.Fprintf(buf, "<pre class='codeblock-pre'>\n<div class='codeblock'>\n%s\n\n</div>\n</pre> \n\n", examples[i])
				}
			}
		}
	}

	if err := printOptions(buf, cmd); err != nil {
		return err
	}

	// If command has screenshot present
	if picLine != "" {
		buf.WriteString("## Screenshots\n\n")
		// Print Caption first
		buf.WriteString(picComment)
		buf.WriteString("\n")
		// Add markdown code for screenshot
		buf.WriteString(picLine)
		buf.WriteString("\n\n")
	}

	if len(manuallyAddedContent) > 0 {
		for _, content := range manuallyAddedContent {
			buf.WriteString("\n")
			buf.WriteString("{{< " + content + " >}}\n")
		}
	}

	if hasSeeAlso(cmd) {
		buf.WriteString("## See Also\n\n")
		if cmd.HasParent() {
			cmd.VisitParents(func(c *cobra.Command) {
				if c.DisableAutoGenTag {
					cmd.DisableAutoGenTag = c.DisableAutoGenTag
				}
			})
		}
		buf.WriteString("Go back to [command reference index](/reference/mesheryctl/), if you want to add content manually to the CLI documentation, please refer to the [instruction](/project/contributing/contributing-cli#preserving-manually-added-documentation) for guidance.")
		buf.WriteString("\n")
	}

	if !cmd.DisableAutoGenTag {
		buf.WriteString("###### Auto generated by spf13/cobra on " + time.Now().Format("2-Jan-2006") + "\n")
	}
	_, err := buf.WriteTo(w)
	return err
}

// hasSeeAlso checks if the command has any subcommands
func hasSeeAlso(cmd *cobra.Command) bool {
	if cmd.HasParent() {
		return true
	}
	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		return true
	}
	return false
}

// GenMarkdownTreeCustom creates custom markdown output.
func GenMarkdownTreeCustom(cmd *cobra.Command, dir string, filePrepender, linkHandler func(string) string) error {
	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		if err := GenMarkdownTreeCustom(c, dir, filePrepender, linkHandler); err != nil {
			return err
		}
	}

	pathParts := strings.Split(cmd.CommandPath(), " ")
	if len(pathParts) > 0 && pathParts[0] == "mesheryctl" {
		pathParts = pathParts[1:]
	}

	var currentDir string
	if cmd.HasAvailableSubCommands() {
		currentDir = filepath.Join(dir, filepath.Join(pathParts...))
		err := os.MkdirAll(currentDir, os.ModePerm)
		if err != nil {
			return err
		}
	} else {
		currentDir = dir
	}

	var filename string
	if cmd.HasAvailableSubCommands() {
		filename = filepath.Join(currentDir, "_index.md")
	} else {
		if len(pathParts) == 0 {
			filename = filepath.Join(dir, "_index.md")
		} else if len(pathParts) == 1 {
			filename = filepath.Join(dir, pathParts[0]+".md")
		} else {
			parentDirs := filepath.Join(pathParts[:len(pathParts)-1]...)
			filename = filepath.Join(dir, parentDirs, pathParts[len(pathParts)-1]+".md")
		}
	}

	// Skip overwriting the root _index.md file
	if filename == filepath.Join(dir, "_index.md") {
		fmt.Println("Skipping root _index.md file: ", filename)
		return nil
	}

	manuallyAddedContent, _ := getManuallyAddedContentMap(filename)

	// Ensure the directory exists before creating the file
	err := os.MkdirAll(filepath.Dir(filename), os.ModePerm)
	if err != nil {
		return err
	}

	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer func() { _ = f.Close() }()

	_, err = io.WriteString(f, filePrepender(filename))
	if err != nil {
		return err
	}

	err = GenMarkdownCustom(cmd, f, manuallyAddedContent)
	if err != nil {
		return err
	}
	return nil
}

func getManuallyAddedContentMap(filename string) (map[int]string, error) {
	manuallyAddedContentMap := make(map[int]string)

	_, err := os.Stat(filename)
	if err != nil {
		return manuallyAddedContentMap, err
	}

	existingContent, err := os.ReadFile(filename)
	if err != nil {
		return manuallyAddedContentMap, err
	}

	content := string(existingContent)

	shortcodePattern := regexp.MustCompile(`\{\{<\s*([^>]+)\s*>\}\}`)
	shortcodeMatches := shortcodePattern.FindAllStringSubmatch(content, -1)
	for i, match := range shortcodeMatches {
		// Store the shortcode content in the map with order as the key
		manuallyAddedContentMap[i] = strings.TrimSpace(match[1])
	}
	return manuallyAddedContentMap, nil
}

func main() {
	doc()
}
