// Copyright Meshery Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	"gopkg.in/yaml.v2"

	"github.com/meshery/meshery/mesheryctl/internal/cli/root"
)

// GenMarkdownTreeCustom is a modified version of GenMarkdownTree from spf13/cobra
const markdownTemplateCommand = `---
title: %s
display_title: false
command: %s
subcommand: %s
---

`

// cmdDoc is a struct to hold the data for a command
type cmdDoc struct {
	Name        string `yaml:"name"`
	Description string `yaml:"description"`
	Usage       string `yaml:"usage"`
	Example     string `yaml:"example"`
}

// prepender is a function to prepend the frontmatter to the markdown file
func prepender(filename string) string {
	idx := strings.Index(filename, "mesheryctl")
	if idx == -1 {
		base := strings.TrimSuffix(filepath.Base(filename), ".md")
		return fmt.Sprintf(markdownTemplateCommand, base, base, "nil")
	}

	relPath := strings.TrimSuffix(filename[idx:], ".md")
	parts := strings.Split(relPath, string(os.PathSeparator))

	if len(parts) == 0 {
		return ""
	}

	if parts[len(parts)-1] == "_index" {
		parts = parts[:len(parts)-1]
	}

	var command, subcommand string

	if len(parts) == 1 {
		command = parts[0]
		subcommand = "nil"
	} else if len(parts) == 2 {
		command = parts[1] // Set the first part as the command
		subcommand = "nil" // Root command has no subcommand
	} else {
		command = parts[1]    // Set the first part as the command
		subcommand = parts[2] // Set the second part as the subcommand
	}

	title := strings.Join(parts, "-")

	return fmt.Sprintf(markdownTemplateCommand,
		title,
		command,
		subcommand,
	)
}

func linkHandler(name string) string {
	// Normalize path
	name = filepath.ToSlash(name)

	// Find the reference root
	idx := strings.Index(name, "reference/mesheryctl")
	if idx == -1 {
		return ""
	}

	// Trim everything before reference/mesheryctl
	trimmed := name[idx:]

	// Remove file extension
	trimmed = strings.TrimSuffix(trimmed, path.Ext(trimmed))

	// Remove trailing _index
	trimmed = strings.TrimSuffix(trimmed, "/_index")

	// Ensure leading slash
	if !strings.HasPrefix(trimmed, "/") {
		trimmed = "/" + trimmed
	}

	return trimmed
}

// docs is a function to generate the markdown docs for mesheryctl
func doc() {
	markDownPath := "../../docs/content/en/reference/mesheryctl/" // Path for docs
	yamlPath := "../../docs/data/mesheryctlcommands/cmds.yml"

	fmt.Println("Scanning available commands...")
	cmd := root.TreePath() // Takes entire tree of mesheryctl commands

	// To skip the footer part "Auto generated by spf13/cobra.."
	cmd.DisableAutoGenTag = true

	fmt.Println("Generating markdown docs...")

	err := GenMarkdownTreeCustom(cmd, markDownPath, prepender, linkHandler)

	if err != nil {
		log.Fatal(err)
	}

	err = GenerateCommandTracker(cmd, yamlPath)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("Documentation generated at " + markDownPath)
	fmt.Println("Command tracker generated at " + yamlPath)
}

func visibleCommands(cmd *cobra.Command) []*cobra.Command {
	commands := make([]*cobra.Command, 0)
	for _, child := range cmd.Commands() {
		if !child.IsAvailableCommand() || child.IsAdditionalHelpTopicCommand() || child.Hidden {
			continue
		}
		commands = append(commands, child)
	}
	return commands
}

func rootGlobalSubcommands(cmd *cobra.Command) []*cobra.Command {
	ordered := []string{"version", "completion"}
	children := visibleCommands(cmd)
	lookup := make(map[string]*cobra.Command, len(children))
	for _, child := range children {
		lookup[child.Name()] = child
	}
	commands := make([]*cobra.Command, 0)
	for _, name := range ordered {
		if child, ok := lookup[name]; ok {
			commands = append(commands, child)
		}
	}
	return commands
}

func initCommandTree(cmd *cobra.Command) {
	cmd.InitDefaultHelpCmd()
	cmd.InitDefaultHelpFlag()
	for _, child := range cmd.Commands() {
		initCommandTree(child)
	}
}

func topLevelCommands(rootCmd *cobra.Command) map[string]*cobra.Command {
	commands := make(map[string]*cobra.Command)
	for _, cmd := range visibleCommands(rootCmd) {
		commands[cmd.Name()] = cmd
	}
	return commands
}

func legacyTopLevelOrder() []string {
	return []string{
		"system",
		"perf",
		"adapter",
		"design",
		"filter",
		"registry",
		"model",
		"component",
		"environment",
		"connection",
		"organization",
		"relationship",
		"exp",
	}
}

func legacySystemAliasOrder() []string {
	return []string{"channel", "context", "provider"}
}

func commandKey(cmd *cobra.Command) string {
	if cmd.Parent() == nil {
		return "global"
	}
	return cmd.Name()
}

func commandName(cmd *cobra.Command) string {
	if cmd.Parent() == nil {
		return cmd.CommandPath()
	}
	return cmd.Name()
}

func displayCommandName(cmd *cobra.Command, alias string) string {
	if alias != "" {
		return alias
	}
	return commandName(cmd)
}

func flagName(flag *pflag.Flag) string {
	if flag.Shorthand == "" {
		return fmt.Sprintf("--%s", flag.Name)
	}
	return fmt.Sprintf("--%s, -%s", flag.Name, flag.Shorthand)
}

func flagValueSuffix(flag *pflag.Flag) string {
	if flag.Value == nil || flag.Value.Type() == "bool" || flag.NoOptDefVal != "" {
		return ""
	}
	return " <value>"
}

func flagsMap(cmd *cobra.Command) yaml.MapSlice {
	flags := yaml.MapSlice{}
	cmd.NonInheritedFlags().VisitAll(func(flag *pflag.Flag) {
		if flag.Hidden {
			return
		}
		flagDoc := yaml.MapSlice{
			{Key: "name", Value: flagName(flag)},
			{Key: "description", Value: flag.Usage},
			{Key: "usage", Value: fmt.Sprintf("%s --%s%s", cmd.CommandPath(), flag.Name, flagValueSuffix(flag))},
		}
		flags = append(flags, yaml.MapItem{Key: flag.Name, Value: flagDoc})
	})
	return flags
}

func commandDoc(cmd *cobra.Command, alias string, children []*cobra.Command) yaml.MapSlice {
	entry := yaml.MapSlice{
		{Key: "name", Value: displayCommandName(cmd, alias)},
		{Key: "description", Value: cmd.Short},
		{Key: "usage", Value: cmd.UseLine()},
	}

	if strings.TrimSpace(cmd.Example) != "" {
		entry = append(entry, yaml.MapItem{Key: "example", Value: cmd.Example})
	}

	flags := flagsMap(cmd)
	if len(flags) > 0 {
		entry = append(entry, yaml.MapItem{Key: "flags", Value: flags})
	}

	if len(children) > 0 {
		subcommands := yaml.MapSlice{}
		for _, child := range children {
			subcommands = append(subcommands, yaml.MapItem{Key: commandKey(child), Value: commandDoc(child, "", visibleCommands(child))})
		}
		entry = append(entry, yaml.MapItem{Key: "subcommands", Value: subcommands})
	}

	return entry
}

func systemCommandDoc(cmd *cobra.Command) yaml.MapSlice {
	excluded := map[string]struct{}{
		"channel":  {},
		"context":  {},
		"provider": {},
	}
	children := make([]*cobra.Command, 0)
	for _, child := range visibleCommands(cmd) {
		if _, ok := excluded[child.Name()]; ok {
			continue
		}
		children = append(children, child)
	}
	return commandDoc(cmd, "", children)
}

func experimentalCommandDoc(cmd *cobra.Command) yaml.MapSlice {
	entry := yaml.MapSlice{}
	for _, child := range visibleCommands(cmd) {
		entry = append(entry, yaml.MapItem{Key: child.Name(), Value: commandDoc(child, "", visibleCommands(child))})
	}
	return entry
}

func commandTrackerDoc(rootCmd *cobra.Command) yaml.MapSlice {
	initCommandTree(rootCmd)
	topLevel := topLevelCommands(rootCmd)
	tracker := yaml.MapSlice{}
	tracker = append(tracker, yaml.MapItem{Key: "global", Value: commandDoc(rootCmd, "", rootGlobalSubcommands(rootCmd))})

	if systemCmd, ok := topLevel["system"]; ok {
		tracker = append(tracker, yaml.MapItem{Key: "system", Value: systemCommandDoc(systemCmd)})
		children := topLevelCommands(systemCmd)
		for _, name := range legacySystemAliasOrder() {
			if child, ok := children[name]; ok {
				tracker = append(tracker, yaml.MapItem{Key: "system-" + name, Value: commandDoc(child, "system "+name, visibleCommands(child))})
			}
		}
	}

	for _, name := range legacyTopLevelOrder() {
		cmd, ok := topLevel[name]
		if !ok || name == "system" {
			continue
		}
		if name == "exp" {
			tracker = append(tracker, yaml.MapItem{Key: name, Value: experimentalCommandDoc(cmd)})
			continue
		}
		tracker = append(tracker, yaml.MapItem{Key: commandKey(cmd), Value: commandDoc(cmd, "", visibleCommands(cmd))})
	}

	for _, cmd := range visibleCommands(rootCmd) {
		if _, ok := topLevel[cmd.Name()]; !ok {
			continue
		}
		if cmd.Name() == "system" || cmd.Name() == "exp" {
			continue
		}
		found := false
		for _, name := range legacyTopLevelOrder() {
			if name == cmd.Name() {
				found = true
				break
			}
		}
		if !found && cmd.Name() != "completion" && cmd.Name() != "version" {
			tracker = append(tracker, yaml.MapItem{Key: commandKey(cmd), Value: commandDoc(cmd, "", visibleCommands(cmd))})
		}
	}
	return tracker
}

func GenerateCommandTracker(rootCmd *cobra.Command, outputPath string) error {
	if err := os.MkdirAll(filepath.Dir(outputPath), os.ModePerm); err != nil {
		return err
	}

	content, err := yaml.Marshal(commandTrackerDoc(rootCmd))
	if err != nil {
		return err
	}

	return os.WriteFile(outputPath, content, 0644)
}

func normalizeGeneratedOutput(content string) string {
	homeDir, err := os.UserHomeDir()
	if err != nil || homeDir == "" {
		return content
	}

	return strings.ReplaceAll(content, homeDir, "/home/runner")
}

// printOptions prints the options for a command
func printOptions(buf *bytes.Buffer, cmd *cobra.Command) error {
	flags := cmd.NonInheritedFlags()
	flags.SetOutput(buf)
	if flags.HasAvailableFlags() {
		flagBuf := new(bytes.Buffer)
		flags.SetOutput(flagBuf)
		buf.WriteString("## Options\n\n<pre class='codeblock-pre'>\n<div class='codeblock'>\n")
		flags.PrintDefaults()
		buf.WriteString(normalizeGeneratedOutput(flagBuf.String()))
		buf.WriteString("\n</div>\n</pre>\n\n")
	}

	parentFlags := cmd.InheritedFlags()
	parentFlags.SetOutput(buf)
	if parentFlags.HasAvailableFlags() {
		parentFlagBuf := new(bytes.Buffer)
		parentFlags.SetOutput(parentFlagBuf)
		buf.WriteString("## Options inherited from parent commands\n\n<pre class='codeblock-pre'>\n<div class='codeblock'>\n")
		parentFlags.PrintDefaults()
		buf.WriteString(normalizeGeneratedOutput(parentFlagBuf.String()))
		buf.WriteString("\n</div>\n</pre>\n\n")
	}
	return nil
}

// GenMarkdownCustom creates custom markdown output.
func GenMarkdownCustom(cmd *cobra.Command, w io.Writer, manuallyAddedContent map[int]string) error {
	// InitDefaultHelpCmd add the help command to the command tree.
	cmd.InitDefaultHelpCmd()
	// InitDefaultHelpFlag add the help flag to the command tree.
	cmd.InitDefaultHelpFlag()

	buf := new(bytes.Buffer)
	// CommandPath returns the full path to this command.
	name := cmd.CommandPath()

	buf.WriteString("# " + name + "\n\n")
	buf.WriteString(cmd.Short + "\n\n")
	if len(cmd.Long) > 0 {
		buf.WriteString("## Synopsis\n\n")
		longContent := cmd.Long
		// Since the long description is used for synopsis, we need to remove the "Find more information at:" line
		findIndex := strings.Index(longContent, "Find")
		if findIndex != -1 {
			buf.WriteString(longContent[:findIndex])
		} else {
			buf.WriteString(longContent)
		}
		buf.WriteString("\n")
	}

	// check if the command is runnable
	if cmd.Runnable() {
		fmt.Fprintf(buf, "<pre class='codeblock-pre'>\n<div class='codeblock'>\n%s\n\n</div>\n</pre> \n\n", cmd.UseLine())
	}

	// check cmd has annotations link and caption
	picLine, ok := cmd.Annotations["link"]
	if !ok {
		picLine = ""
	}
	picComment, ok := cmd.Annotations["caption"]
	if !ok {
		picComment = ""
	}

	// check if cmd has example
	if len(cmd.Example) > 0 {
		buf.WriteString("## Examples\n\n")
		var examples = strings.Split(cmd.Example, "\n")
		for i := 0; i < len(examples); i++ {
			if examples[i] != "" && examples[i] != " " && examples[i] != "	" {
				if strings.HasPrefix(examples[i], "//") {
					// Description Line
					buf.WriteString(strings.ReplaceAll(examples[i], "// ", "") + "\n")
				} else {
					// Code Block Line

					fmt.Fprintf(buf, "<pre class='codeblock-pre'>\n<div class='codeblock'>\n%s\n\n</div>\n</pre> \n\n", examples[i])
				}
			}
		}
	}

	if err := printOptions(buf, cmd); err != nil {
		return err
	}

	// If command has screenshot present
	if picLine != "" {
		buf.WriteString("## Screenshots\n\n")
		// Print Caption first
		buf.WriteString(picComment)
		buf.WriteString("\n")
		// Add markdown code for screenshot
		buf.WriteString(picLine)
		buf.WriteString("\n\n")
	}

	if len(manuallyAddedContent) > 0 {
		for _, content := range manuallyAddedContent {
			buf.WriteString("\n")
			buf.WriteString("{{< " + content + " >}}\n")
		}
	}

	if hasSeeAlso(cmd) {
		buf.WriteString("## See Also\n\n")
		if cmd.HasParent() {
			cmd.VisitParents(func(c *cobra.Command) {
				if c.DisableAutoGenTag {
					cmd.DisableAutoGenTag = c.DisableAutoGenTag
				}
			})
		}
		buf.WriteString("Go back to [command reference index](/reference/mesheryctl/), if you want to add content manually to the CLI documentation, please refer to the [instruction](/project/contributing/contributing-cli#preserving-manually-added-documentation) for guidance.")
		buf.WriteString("\n")
	}

	if !cmd.DisableAutoGenTag {
		buf.WriteString("###### Auto generated by spf13/cobra on " + time.Now().Format("2-Jan-2006") + "\n")
	}
	_, err := buf.WriteTo(w)
	return err
}

// hasSeeAlso checks if the command has any subcommands
func hasSeeAlso(cmd *cobra.Command) bool {
	if cmd.HasParent() {
		return true
	}
	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		return true
	}
	return false
}

// GenMarkdownTreeCustom creates custom markdown output.
func GenMarkdownTreeCustom(cmd *cobra.Command, dir string, filePrepender, linkHandler func(string) string) error {
	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		if err := GenMarkdownTreeCustom(c, dir, filePrepender, linkHandler); err != nil {
			return err
		}
	}

	pathParts := strings.Split(cmd.CommandPath(), " ")
	if len(pathParts) > 0 && pathParts[0] == "mesheryctl" {
		pathParts = pathParts[1:]
	}

	var currentDir string
	if cmd.HasAvailableSubCommands() {
		currentDir = filepath.Join(dir, filepath.Join(pathParts...))
		err := os.MkdirAll(currentDir, os.ModePerm)
		if err != nil {
			return err
		}
	} else {
		currentDir = dir
	}

	var filename string
	if cmd.HasAvailableSubCommands() {
		filename = filepath.Join(currentDir, "_index.md")
	} else {
		if len(pathParts) == 0 {
			filename = filepath.Join(dir, "_index.md")
		} else if len(pathParts) == 1 {
			filename = filepath.Join(dir, pathParts[0]+".md")
		} else {
			parentDirs := filepath.Join(pathParts[:len(pathParts)-1]...)
			filename = filepath.Join(dir, parentDirs, pathParts[len(pathParts)-1]+".md")
		}
	}

	// Skip overwriting the root _index.md file
	if filename == filepath.Join(dir, "_index.md") {
		fmt.Println("Skipping root _index.md file: ", filename)
		return nil
	}

	manuallyAddedContent, _ := getManuallyAddedContentMap(filename)

	// Ensure the directory exists before creating the file
	err := os.MkdirAll(filepath.Dir(filename), os.ModePerm)
	if err != nil {
		return err
	}

	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer func() { _ = f.Close() }()

	_, err = io.WriteString(f, filePrepender(filename))
	if err != nil {
		return err
	}

	err = GenMarkdownCustom(cmd, f, manuallyAddedContent)
	if err != nil {
		return err
	}
	return nil
}

func getManuallyAddedContentMap(filename string) (map[int]string, error) {
	manuallyAddedContentMap := make(map[int]string)

	_, err := os.Stat(filename)
	if err != nil {
		return manuallyAddedContentMap, err
	}

	existingContent, err := os.ReadFile(filename)
	if err != nil {
		return manuallyAddedContentMap, err
	}

	content := string(existingContent)

	shortcodePattern := regexp.MustCompile(`\{\{<\s*([^>]+)\s*>\}\}`)
	shortcodeMatches := shortcodePattern.FindAllStringSubmatch(content, -1)
	for i, match := range shortcodeMatches {
		// Store the shortcode content in the map with order as the key
		manuallyAddedContentMap[i] = strings.TrimSpace(match[1])
	}
	return manuallyAddedContentMap, nil
}

// GenYamlTreeCustom creates custom yaml output.
func GenYamlTreeCustom(cmd *cobra.Command, dir string, filePrepender, linkHandler func(string) string) error {
	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		if err := GenYamlTreeCustom(c, dir, filePrepender, linkHandler); err != nil {
			return err
		}
	}

	basename := "cmds.yml"
	filename := filepath.Join(dir, basename)
	f, err := os.OpenFile(basename, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}

	_, err = io.WriteString(f, filePrepender(filename))
	if err != nil {
		return err
	}

	err = GenYamlCustom(cmd, f)
	if err != nil {
		return err
	}

	// check error before closing
	if err = f.Close(); err != nil {
		return err
	}

	return nil
}

// GenYamlCustom generates yaml docs for the command
func GenYamlCustom(cmd *cobra.Command, w io.Writer) error {
	// init default help command and flag
	cmd.InitDefaultHelpCmd()
	cmd.InitDefaultHelpFlag()
	yamlDoc := cmdDoc{}

	yamlDoc.Name = cmd.CommandPath()
	// cmd.Short is the short description of the command
	yamlDoc.Description = cmd.Short
	yamlDoc.Usage = cmd.UseLine()
	if len(cmd.Example) > 0 {
		yamlDoc.Example = cmd.Example
	}

	fmt.Println(yamlDoc)
	final, err := yaml.Marshal(&yamlDoc)

	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	_, err = w.Write(final)
	if err != nil {
		return err
	}

	return nil
}

func main() {
	doc()
}
