package model

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestHasCSVs(t *testing.T) {
	tests := []struct {
		name           string
		dirPath        string
		expectedResult bool
	}{
		{
			name:           "directory with CSVs",
			dirPath:        "./fixtures/with_csvs",
			expectedResult: true,
		},
		{
			name:           "directory without CSVs",
			dirPath:        "./fixtures/without_csvs",
			expectedResult: false,
		},
		{
			name:           "non-existent directory",
			dirPath:        "./fixtures/invalid_path",
			expectedResult: false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			res := hasCSVs(tc.dirPath)
			assert.Equal(t, tc.expectedResult, res)
		})
	}
}

// TestScaffoldToModel_MapsInitScaffoldToURLTemplate verifies that a full canonical
// ModelDefinition template (generated by "mesheryctl model init") is correctly
// converted to a flat schemav1beta1.Model for the ImportRequest.
// This exercises Path 1 (canonical ModelDefinition unmarshal).
func TestScaffoldToModel_MapsInitScaffoldToURLTemplate(t *testing.T) {
	input := []byte(`{
		"name": "test-model",
		"displayName": "Test Model",
		"category": {"name": "Uncategorized"},
		"subCategory": "Utilities",
		"registrant": {"kind": "github", "name": ""},
		"metadata": {
			"primaryColor": "#00b39f",
			"secondaryColor": "#00D3A9",
			"shape": "circle",
			"svgColor": "<svg-color/>",
			"svgWhite": "<svg-white/>",
			"isAnnotation": true
		}
	}`)

	got, err := scaffoldToModel(input)
	require.NoError(t, err)

	assert.Equal(t, "test-model", got.Model)
	assert.Equal(t, "Test Model", got.ModelDisplayName)
	assert.Equal(t, "github", got.Registrant)
	assert.Equal(t, "#00b39f", got.PrimaryColor)
	assert.Equal(t, "#00D3A9", got.SecondaryColor)
	assert.Equal(t, "<svg-color/>", got.SvgColor)
	assert.Equal(t, "<svg-white/>", got.SvgWhite)
	assert.Equal(t, true, got.IsAnnotation)
	// Bug fix #2: shape must now be correctly copied from metadata
	assert.Equal(t, "circle", got.Shape, "shape from metadata must not be silently dropped")
}

// TestScaffoldToModel_PreservesExistingURLTemplateKeys verifies that a simple flat
// template (fixtures/template.json format) is passed through correctly.
// This exercises Path 2 (direct flat unmarshal fallback).
func TestScaffoldToModel_PreservesExistingURLTemplateKeys(t *testing.T) {
	input := []byte(`{
		"model": "cert-manager",
		"modelDisplayName": "Cert Manager",
		"registrant": "github",
		"category": "Security",
		"subCategory": "Certificates",
		"primaryColor": "#0B5FFF",
		"secondaryColor": "#121212",
		"isAnnotation": false,
		"publishToRegistry": false
	}`)

	got, err := scaffoldToModel(input)
	require.NoError(t, err)

	assert.Equal(t, "cert-manager", got.Model)
	assert.Equal(t, "Cert Manager", got.ModelDisplayName)
	assert.Equal(t, "github", got.Registrant)
	assert.Equal(t, "#0B5FFF", got.PrimaryColor)
	assert.Equal(t, "#121212", got.SecondaryColor)
	assert.Equal(t, false, got.IsAnnotation)
	assert.Equal(t, false, got.PublishToRegistry)
}

// TestScaffoldToModel_ResolvesDisplayNameAlias verifies that the flat template's
// "displayName" key (used in fixtures/template.json) is resolved to
// schemav1beta1.Model.ModelDisplayName even though the json tags don't match.
// This is Bug fix #1: prevents the user's display name from being silently dropped.
func TestScaffoldToModel_ResolvesDisplayNameAlias(t *testing.T) {
	// This matches the exact shape of fixtures/templates/template.json which uses
	// "displayName" (not "modelDisplayName")
	input := []byte(`{
		"registrant": "github",
		"model": "cert-manager",
		"displayName": "Cert Manager",
		"category": "Security",
		"subCategory": "Certificates",
		"primaryColor": "#0B5FFF",
		"secondaryColor": "#121212",
		"isAnnotation": false,
		"publishToRegistry": false
	}`)

	got, err := scaffoldToModel(input)
	require.NoError(t, err)

	assert.Equal(t, "cert-manager", got.Model)
	assert.Equal(t, "github", got.Registrant)
	// Bug fix #1: "displayName" in the flat template must map to ModelDisplayName
	assert.Equal(t, "Cert Manager", got.ModelDisplayName,
		"displayName from flat template must not be silently dropped (json tag alias)")
}

// TestScaffoldToModel_PreservesLogoFromFixtureTemplate verifies the flat fixture
// template is correctly parsed. Note: "logo" is not a field in schemav1beta1.Model
// and is not forwarded to the server — this is documented behaviour.
func TestScaffoldToModel_PreservesLogoFromFixtureTemplate(t *testing.T) {
	input := []byte(`{
		"registrant": "github",
		"model": "cert-manager",
		"modelDisplayName": "Cert Manager",
		"category": "Security",
		"primaryColor": "#0B5FFF",
		"isAnnotation": false,
		"publishToRegistry": false
	}`)

	got, err := scaffoldToModel(input)
	require.NoError(t, err)

	assert.Equal(t, "cert-manager", got.Model)
	assert.Equal(t, "github", got.Registrant)
	assert.Equal(t, "#0B5FFF", got.PrimaryColor)
	assert.Equal(t, false, got.IsAnnotation)
}
