export const DEFAULT_LAYOUT = {
  lg: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 16,
      x: 0,
      y: 0,
    },
    {
      h: 2,
      i: 'GETTING_STARTED',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 3,
    },
    {
      h: 2,
      i: 'HELP_CENTER',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 5,
    },
    { h: 2, i: 'MY_DESIGNS', moved: false, static: false, w: 3, x: 3, y: 3 },
    { h: 2, i: 'WORKSPACE_ACTIVITY', moved: false, static: false, w: 6, x: 6, y: 3 },
    { h: 2, i: 'CONNECTIONS_STATUS_CHART', moved: false, static: false, w: 6, x: 3, y: 5 },
  ],
  md: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 16,
      x: 0,
      y: 0,
    },
    {
      h: 2,
      i: 'GETTING_STARTED',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 3,
    },
    {
      h: 2,
      i: 'HELP_CENTER',
      moved: false,
      static: false,
      w: 3,
      x: 6,
      y: 3,
    },
    { h: 2, i: 'MY_DESIGNS', moved: false, static: false, w: 3, x: 3, y: 3 },
    { h: 2, i: 'WORKSPACE_ACTIVITY', moved: false, static: false, w: 6, x: 0, y: 5 },
    { h: 2, i: 'CONNECTIONS_STATUS_CHART', moved: false, static: false, w: 6, x: 0, y: 7 },
  ],
  sm: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
    },
    {
      h: 2,
      i: 'GETTING_STARTED',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 3,
    },
    {
      h: 2,
      i: 'HELP_CENTER',
      moved: false,
      static: false,
      w: 3,
      x: 3,
      y: 3,
    },
    { h: 2, i: 'MY_DESIGNS', moved: false, static: false, w: 3, x: 0, y: 5 },
    { h: 2, i: 'WORKSPACE_ACTIVITY', moved: false, static: false, w: 6, x: 0, y: 7 },
    { h: 2, i: 'CONNECTIONS_STATUS_CHART', moved: false, static: false, w: 6, x: 0, y: 9 },
  ],
  xs: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
    },
    {
      h: 2,
      i: 'GETTING_STARTED',
      moved: false,
      static: false,
      w: 2,
      x: 0,
      y: 3,
    },
    {
      h: 2,
      i: 'HELP_CENTER',
      moved: false,
      static: false,
      w: 2,
      x: 2,
      y: 3,
    },
    { h: 2, i: 'MY_DESIGNS', moved: false, static: false, w: 2, x: 0, y: 5 },
    { h: 2, i: 'WORKSPACE_ACTIVITY', moved: false, static: false, w: 6, x: 0, y: 7 },
    { h: 2, i: 'CONNECTIONS_STATUS_CHART', moved: false, static: false, w: 6, x: 0, y: 9 },
  ],
  xxs: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
    },
    {
      h: 2,
      i: 'GETTING_STARTED',
      moved: false,
      static: false,
      w: 2,
      x: 0,
      y: 3,
    },
    {
      h: 2,
      i: 'HELP_CENTER',
      moved: false,
      static: false,
      w: 2,
      x: 0,
      y: 5,
    },
    { h: 2, i: 'MY_DESIGNS', moved: false, static: false, w: 2, x: 0, y: 7 },
    { h: 2, i: 'WORKSPACE_ACTIVITY', moved: false, static: false, w: 6, x: 0, y: 9 },
    { h: 2, i: 'CONNECTIONS_STATUS_CHART', moved: false, static: false, w: 6, x: 0, y: 11 },
  ],
};

export const LOCAL_PROVIDER_LAYOUT = {
  lg: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 16,
      x: 0,
      y: 0,
    },
    {
      h: 2,
      i: 'LATEST_BLOGS',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 3,
    },
  ],
  md: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 16,
      x: 0,
      y: 0,
    },
    {
      h: 2,
      i: 'LATEST_BLOGS',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 3,
    },
  ],
  sm: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
    },
    {
      h: 2,
      i: 'LATEST_BLOGS',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 3,
    },
  ],
  xs: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
    },
    {
      h: 2,
      i: 'LATEST_BLOGS',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 3,
    },
  ],
  xxs: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
    },
    {
      h: 2,
      i: 'LATEST_BLOGS',
      moved: false,
      static: false,
      w: 3,
      x: 0,
      y: 3,
    },
  ],
};

export const OVERVIEW_LAYOUT = {
  lg: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 16,
      x: 0,
      y: 0,
    },
  ],
  md: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 16,
      x: 0,
      y: 0,
    },
  ],
  sm: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
    },
  ],
  xs: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
    },
  ],
  xxs: [
    {
      h: 2.565,
      i: 'OVERVIEW',
      moved: false,
      static: false,
      w: 12,
      x: 0,
      y: 0,
    },
  ],
};
