// Code generated by install/scripts/sync-provider-urls.py from install/providers.env; DO NOT EDIT.

package models

// DefaultRemoteProviderURLs is the comma-joined list of active default remote
// provider URLs. The server seeds it via SetDefault("PROVIDER_BASE_URLS", ...) so
// operators who do not set the env var still register the canonical providers.
const DefaultRemoteProviderURLs = "https://cloud.meshery.io,https://perf.smp-spec.io,https://cloud.layer5.io,https://meshery.tcs-labs.in,https://provider.od10.in"

// PrimaryProviderURL is the single canonical provider host used by single-URL
// consumers (the built-in local provider's capability paths, SaaS deep links,
// provider-ui return-to fallback, e2e defaults).
const PrimaryProviderURL = "https://cloud.meshery.io"
