package policies

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"sort"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/meshery/meshkit/logger"
	"github.com/meshery/schemas/models/v1beta1/pattern"
	"github.com/open-policy-agent/opa/v1/rego"
	"github.com/open-policy-agent/opa/v1/storage/inmem"
)

// catalogEntry identifies one design in the Meshery Catalog.
type catalogEntry struct {
	id      string // catalog folder UUID
	version string // catalog folder version
	name    string // human-readable name (used as filename)
}

// catalogDesigns returns 73 catalog designs that have relationships.
func catalogDesigns() []catalogEntry {
	return []catalogEntry{
		{"0e64cfa4-c8a4-4155-a8b1-bf21aa9e5107", "0.0.14", "3-Tier-Architecture"},
		{"1abccf09-dcb8-46e4-8cac-f9e33c27516d", "0.0.1", "AWS-RDS-Controller"},
		{"37792455-294f-481b-a7a8-13e79ca835ca", "0.0.1", "AWS-cloudfront-controller"},
		{"075ec9ba-6ad7-4421-a09c-3b8edd5fb4a6", "0.0.1", "Accelerated-mTLS-handshake-for-Envoy-data-planes"},
		{"0b6b1ff8-cb2e-41d4-baff-e0a053f7e4d9", "0.0.1", "Apache-Airflow"},
		{"2b8ca8e9-b964-4102-8ee7-dbb2f1fbed49", "0.0.1", "Autogenerated"},
		{"3ec30961-1aba-4db7-86c5-7556de5d90ca", "0.0.1", "Busybox-single-fresh"},
		{"294946e9-2079-4e6e-8a44-489fbdcf9e3f", "0.0.15", "Complete-Kubernetes-Application-Pattern"},
		{"28715e69-c6c1-4f96-bfa2-05113b00bae0", "0.0.1", "CryptoMB-TLS-handshake-acceleration-for-Istio"},
		{"0aa86dd0-415c-4bf8-ae76-832560470b74", "0.0.1", "DaemonSet-GKE-Autopilot"},
		{"31ed2484-4aeb-4dcc-aa98-b61933d371cc", "0.0.1", "Delay-Action-for-Chaos-Mesh"},
		{"3afb9cdf-4a37-4db2-a9f9-2e2b8769ec3e", "0.0.11", "Deploy-Meshery-using-Meshery"},
		{"147e429b-fe51-45b3-a275-a5940cb91882", "0.0.42", "Deployable-simple-web-architecture-design"},
		{"28980b0e-fb2f-4b18-8a79-47c45b477ca3", "0.0.16", "Double-Bubble-Map"},
		{"397e88c7-38d9-4499-85b2-73696f0b195a", "0.0.54", "Edge-Firewall-relationship"},
		{"57f4628b-798e-4f72-be0e-03b42683b27b", "0.0.3", "Edge-Relationships-diff"},
		{"37422db6-b585-4b1a-baaa-d307d33d5ebf", "0.0.116", "Edge-mount-relationship"},
		{"3cf2d3a4-460f-44a0-8efc-bfc5b5ae661c", "0.0.34", "Exam-Portal-with-Real-Time-Leaderboard-AWS"},
		{"1f79b0c6-2efe-4ee9-b08c-e1bd07a3926b", "0.0.1", "Example-Edge-Network"},
		{"02413809-9fbf-4649-ae22-3d0947d264c6", "0.0.1", "Example-Labels-and-Annotations"},
		{"08379ae3-cd9e-4b55-a190-91a47a1ff638", "0.0.1", "Fault-tolerant-batch-GKE"},
		{"070b4569-2b26-4e13-93f7-9992fdf1e6fd", "0.0.332", "GCP-DataMesh"},
		{"107f4fc2-0655-4d00-be3d-164947159647", "0.0.1", "Hello-Kubernetes-Tutorial"},
		{"3255f170-e2b1-48e8-bbed-40d4e0198a90", "0.0.4", "Hierarchical-Parent-Inventory-Relationship"},
		{"3ec9ec04-1a16-4814-ba1d-12c61b356bc3", "0.0.33", "Hierarchical-Parent-Matchlabels-Relationship"},
		{"1fa80124-d38d-41d1-a768-0fcb7cdae31e", "0.0.1", "HorizontalPodAutoscaler"},
		{"06ef6097-8f21-4a76-b025-0c9271168814", "0.0.1", "Istio-Operator"},
		{"32f10b2a-82eb-4ab9-b1f7-4f8c7f888011", "0.0.1", "Jaeger-operator"},
		{"1a9cfdfb-daaf-4c19-be93-6d9bc0f7b94d", "0.0.144", "K8s-Workload-Controllers"},
		{"0e426f91-14df-4f70-b6cc-ed3624d53ccd", "0.0.1", "Key-cloak-operator"},
		{"23d03e32-4232-40f1-b953-0416e47b9b5d", "0.0.1", "Kubernetes-Engine-Training-Example"},
		{"287dc0fe-6497-4483-b54e-178eb8d65da8", "0.0.1", "Kubernetes-cronjob"},
		{"336465da-5ead-418c-baee-a369fb5581e9", "0.0.65", "Kubernetes-service-Design"},
		{"210422ee-a1c4-4844-9591-bab374608cba", "0.0.1", "Litmus-Chaos-Operator"},
		{"2197b9bf-c48d-4394-873e-680a2ae35ed2", "0.0.91", "LoxiLB-K8S-External-Load-Balancer"},
		{"2d0a36b9-8170-4076-8aea-4fa6b28caf31", "0.0.166", "Match-Labels-Relationship"},
		{"081aa52c-7921-48dd-b81e-03f4ebfc70b5", "0.0.1", "Minecraft-App"},
		{"22df0361-9be1-4e48-a3fb-f782ce900cbd", "0.0.54", "Namespaces-in-kubernetes"},
		{"100a9ac6-9cb2-47e3-b960-6429674cdb04", "0.0.8", "Observable-K8s-Workloads"},
		{"3e85b81b-f366-4afc-a24f-763a4cf66a8b", "0.0.3", "Online-Polling-Application"},
		{"10caf581-6498-4a1f-a00a-76011b60af48", "0.0.643", "Oracle-e-commerce-microservices-on-kubernetes"},
		{"2649785a-6cb1-4671-b625-a790ac375043", "0.0.1", "Persistence-volume-claim"},
		{"17c46515-50ef-436c-9383-451e13348ddd", "0.0.1", "Pod-Multi-Containers"},
		{"0194ff83-0a43-4b83-9c75-b8f0f32da6b7", "0.0.1", "Pod-Readiness"},
		{"05ff8dbb-2552-4a23-a6a8-318fe412bf30", "0.0.1", "Pod-Resource-Request"},
		{"307373c2-a096-4b52-841e-fc18c3a5d17f", "0.0.21", "Redis-PHP-Guestbook"},
		{"189a3e71-8be9-4e64-9fed-150a9b1060de", "0.0.1", "Resilient-Web-App"},
		{"205a4fe3-1daf-4150-9062-3e7c81dde143", "0.0.1", "Simple-Kubernetes-Pod"},
		{"2a5bf8bd-d53a-4d8a-ba59-da43b0948b44", "0.0.5", "URL-Shortener-Application"},
		{"2f7597bd-9713-461e-b64f-c571415d2a86", "0.0.11", "VPC-WORKFLOW-DESIGN"},
		{"3039deb0-7a26-4f4c-ab4c-a4c45a4f281c", "0.0.4", "Weather-Forecasting-App"},
		{"2df29b2b-7e5e-4d8b-a5b3-3dea569f4d25", "0.0.1", "WordPress-and-MySQL-with-Persistent-Volume"},
		{"10919143-fe49-419d-9022-7906e75fe1bf", "0.0.75", "clickhouse-otel-hyperdx-arch"},
		{"13e803b7-596c-4620-bdc4-4d3a28a027a2", "0.0.20", "container-alias-relationship"},
		{"0a2d8c39-df40-490b-94b7-75d0fb7fc207", "0.0.1", "default-ns"},
		{"1f3c7dcd-e49a-4bf7-985a-661d6c64d8d7", "0.0.1", "doks-nginx-deployment"},
		{"045bdba0-bc55-4bf8-8e54-1ae05ebd671c", "0.0.7", "example-project"},
		{"129c524b-ead9-4170-b236-a1c9dd274ece", "0.0.1", "gitlab-runner-deployment"},
		{"3a38cc90-e998-4f2a-9747-17f2d7ddf313", "0.0.1", "grafana-deployment"},
		{"28e09dc6-de75-4c61-8531-e6e3744f7e98", "0.0.2", "hierarchical-parent-namespace-relationship"},
		{"1c9730ce-b481-41c3-92ed-8044e1203f17", "0.0.3", "katib-242"},
		{"3e027027-05dc-4c10-9bd0-287cb34c2b09", "0.0.8", "kibana-helm-design-fixed"},
		{"3b2a210d-77b4-4267-bc8e-bc32758edf76", "0.0.1", "meshery-cilium-deployment"},
		{"34fe3846-4b90-4558-914c-8e57caefd52f", "0.0.2", "meshery-design-fixturejson"},
		{"114c94c9-052b-46a2-86fe-4cdd2e88c746", "0.0.1", "my-first-app-design"},
		{"2512c0cb-385d-40de-b1f5-bc4a67131538", "0.0.1", "my-sql-with-cinder-vol-plugin"},
		{"1e2478e0-7611-4d4f-a44f-ea02cebf7b91", "0.0.1", "postgreSQL-cluster"},
		{"2a42de8b-3c58-4571-b092-2fda29ecfb1a", "0.0.1", "prometheus-operator-crd-cluster-roles"},
		{"3c3439a0-d215-4a71-aa47-13a5f2d007b7", "0.0.1", "prometheus_kubernetes"},
		{"2aa761d3-cd30-419a-a441-2f042934116f", "0.0.2", "service-to-deployment-network"},
		{"34cc15a9-2cf7-4eb6-91b6-c9731e0984d8", "0.0.5", "sqlcl-liquibase-100tgz"},
		{"0ecab33d-6ac2-40ff-9ff9-76a706598cbe", "0.0.13", "test-design-account"},
		{"22e28213-8c94-49d5-b104-3b7feee84b5e", "0.0.1", "voting_app"},

		// --- Additional catalog entries (309 more designs) ---
		{"00fadfee-3655-40c7-8a38-6c5cd72ea4da", "0.0.1", "vault-0.30.1.tgz"},
		{"032e4645-0d1e-4873-be52-b6fcd9d0cd4c", "0.0.4", "Untitled-Design-032e"},
		{"04cf78e7-6041-45f7-bca5-999d5d7d6a19", "0.0.5", "Dapr"},
		{"0b81f11d-da05-4638-9d48-0c8bcdb406e4", "0.0.1", "ms-emails-worker-0.0.11.tgz"},
		{"0d8d6d6d-362f-49e3-9a88-2d7e6aa20542", "0.0.1", "Design-With-Validation-Errors"},
		{"0dcaacf8-3538-4cb3-b877-a80078af0378", "0.0.1", "Untitled-Design-0dca"},
		{"1012970d-bbf5-4bc5-b5e2-f6cb1da64b84", "0.0.1", "aspnet-core-7.0.35.tgz"},
		{"104be089-dae0-4d09-be70-c1d121673119", "0.0.1", "mTLS-handshake-acceleration-for-Istio"},
		{"11d54f4a-129a-43f5-9c17-7e7518202ea6", "0.0.2", "dremio-helm"},
		{"12250207-b931-43b6-b3c2-a3dbc0ab775a", "0.0.4", "Kyverno-Policy-Engine"},
		{"155ea647-2719-4dad-bb6a-d53f21c3002e", "0.0.4", "Untitled-Design-155e"},
		{"17924ed6-4556-40c1-a019-53f343825014", "0.0.3", "ms-filestorage-worker-design"},
		{"1d3b05ee-7c11-4c01-be93-81c3bb1b6524", "0.0.1", "Emojivoto-Application"},
		{"22f5ec4d-362f-423d-be53-ff4a34a80f4c", "0.0.3", "ms-microsoftgraph-rest-0.0.11.tgz"},
		{"254aa1d3-d972-4894-813a-f58fdd24021c", "0.0.8", "Hashicorp-Vault"},
		{"2584ee1a-8f55-4b84-ad65-ee8514e3ec10", "0.0.2", "ms-locations-rest-0.0.11.tgz"},
		{"27454352-6b1b-426e-830e-683b8c34b94e", "0.0.64", "Edge-Binding-Permissions-Relationship"},
		{"29b94780-865c-460b-b852-cc5c31730561", "0.0.5", "nginx-k8s-deployment"},
		{"2a9672d5-1690-49f8-ae3d-1010556d494b", "0.0.1", "clickhouse-9.4.4.tgz"},
		{"2d54f372-10e5-4c4e-8d23-b9c35c68ce98", "0.0.1", "Robot-Shop-Sample-App"},
		{"2f7c65a7-dc3d-4359-8bdf-3d5344ef64e8", "0.0.1", "Kafka-Streaming-Platform"},
		{"2fdf5dcb-a3c0-4c2c-a64f-a3943ac87d5f", "0.0.310", "All-relationships-2fdf"},
		{"328ceb3f-970c-4e70-93f9-61e987d7952c", "0.0.2", "Simple-Kubernetes-Pod-328c"},
		{"33307744-8085-4f09-9dda-28666c6bb8c1", "0.0.1", "rabbitmq-cluster-operator"},
		{"3375dd93-d96f-43da-9a70-efff84b412e9", "0.0.2", "ms-payments-rest"},
		{"3546d0d4-ba6e-4c7e-9661-853ade11847f", "0.0.1", "Wordpress-and-MySql-on-Kubernetes"},
		{"35e082b6-7c4f-40f1-a7b8-000b6c65dfaf", "0.0.1", "cluster-istio-18.11.60.tgz"},
		{"35ecff6c-41f5-400b-92c4-f959dd23ee15", "0.0.1", "Autoscaling-based-on-Metrics-in-GKE"},
		{"378da4da-dc81-4b6f-9473-fc91b5ce88e1", "0.0.1", "KEDA-Setup"},
		{"3793337c-8c85-4112-848d-d659a4d34b22", "0.0.18", "Edge-Mount-Relationship-3793"},
		{"381b381a-b7d3-4534-8075-0b1a8105ea10", "0.0.2", "ms-base-0.0.22.tgz"},
		{"3a949b4a-7113-4394-a286-65406289210a", "0.0.178", "Design-Annotation-Patterns"},
		{"3d01bc39-8627-42b7-abe1-0cf9eb3a0a9d", "0.0.1", "CryptoMB-TLS-handshake-acceleration-for-Istio-3d01"},
		{"3e3c169a-c252-4b71-8667-62dd6ed085be", "0.0.1", "guest_book"},
		{"3f3e545b-063b-4c0a-9cb5-0928d7bd9462", "0.0.1", "Vault-operator"},
		{"3f712cfe-b2a9-4b4f-89df-ac5b19d10f3a", "0.0.61", "Managing-Configuration-for-Kubernetes-Pods"},
		{"3fd06d85-e516-4eae-b7b6-474231b6d48d", "0.0.593", "Sample-Template-Relationship-Diagram"},
		{"3fe52f86-0214-4813-9d23-727f2e57469b", "0.0.1", "Serve-an-LLM-using-multi-host-TPUs-on-GKE"},
		{"4032a5c3-d081-429b-9087-2b9bdaa7396b", "0.0.1", "Mount-Pod-PersistentVolume"},
		{"4085f7a4-34e4-45a5-b00b-7fb1c19543a7", "0.0.9", "Distributed-Web-Crawler"},
		{"40e5c357-472a-43cd-be4a-8af002974ed5", "0.0.187", "TagSet-Relationships"},
		{"40ed4661-c68c-4f9d-ba2f-0541ee16ea29", "0.0.1", "Microservices-Deployment"},
		{"41c80476-8147-4e7e-adaa-1da35c1103a4", "0.0.1", "cert-manager-v1.18.2.tgz"},
		{"4213db96-87ad-4829-9553-d3c6fdaa9206", "0.0.98", "Azure-Service-Operator"},
		{"42ae63d9-06d1-4957-bf91-7be82ce80742", "0.0.1", "ms-microsoftgraph-worker-0.0.11.tgz"},
		{"454dff6a-d988-4a09-8206-963eaa816c8d", "0.0.1", "Istio-Control-Plane"},
		{"45d7d037-52a2-457b-a670-06526c4f814b", "0.0.1", "mongoDB-Sample-app"},
		{"464b4f2a-78d8-4034-915a-612475f757d2", "0.0.1", "Thanos-Query-Design"},
		{"4690406b-60e7-4c82-87c3-20b22862f5b5", "0.0.1", "Argo-CD-w-Dex"},
		{"470c84f8-32ba-4741-8a78-64e64774a7b4", "0.0.2", "kafka-32.3.10.tgz"},
		{"479108bc-c07d-4a25-aa02-40d63451f10b", "0.0.212", "All-relationships-4791"},
		{"48db8990-978a-4845-9e82-de1eae091498", "0.0.3", "chaos-mesh-architecture-copy"},
		{"496ac5d6-cf5c-4943-b0ca-2e3e346ad202", "0.0.5", "kiali-architecture-design"},
		{"4a871757-054c-48cf-bc30-32814b7271a5", "0.0.185", "Hierarchical-Parent-Inventory-Relationship-4a87"},
		{"4c918765-c145-4607-a0ad-af01a7fa696e", "0.0.1", "jenkins-13.6.17.tgz"},
		{"4cc2bbfb-6bb9-4981-a21f-e52955d92a9d", "0.0.1", "NGINX-deployment"},
		{"4d3d5921-2293-4b12-b3b5-aa147fbbf755", "0.0.35", "hello-design.yml"},
		{"4efe3cb7-c901-48a9-9324-67d73d546aff", "0.0.1", "ArgoCD-application-controller"},
		{"4fa79264-3c97-497d-aaf1-f79f52c7decf", "0.0.74", "Elasticsearch-with-Kubernetes"},
		{"4fb7a134-d048-4db4-a556-c1e2c834c995", "0.0.1", "loxilb-0.1.0.tgz"},
		{"4fe5b8f3-d8c7-487c-9860-bc7cb8674d48", "0.0.1", "Prometheus-dummy-exporter"},
		{"4fed25f3-e63e-48b2-bff8-b05da462af14", "0.0.96", "Spring-Cloud-Microservices-Architecture"},
		{"50579aa0-0ada-4400-b954-02d237a107c2", "0.0.117", "Mattermost-Server-Scaling-for-aws-design"},
		{"508efffb-d106-4593-af7b-0b85e1a59822", "0.0.1490", "Tutorial-Comments"},
		{"517a238d-da27-47d3-94e0-1b75fd0b3052", "0.0.13", "Guestbook-Application-Extended-Version"},
		{"51e49367-2f57-4055-b2df-dc0f35d4d7c8", "0.0.4", "Edge-Firewall-Relationship-51e4"},
		{"5275aa84-91e0-4df1-883d-8df61397f951", "0.0.1", "appsmith-7.0.3.tgz"},
		{"5479aed9-669a-4bea-9693-56921b55d04d", "0.0.1", "Prometheus-Sample"},
		{"571a79c9-01c5-4c4b-b8c6-c3f0b2f2415f", "0.0.1", "Browserless-Chrome"},
		{"5751de17-4f97-41c2-a3de-bfc156d456c5", "0.0.1", "Mattermost-Cluster-Install"},
		{"57b9de8d-2ab3-4d18-9314-11125e63e551", "0.0.1", "Pod-Volumes-Projected"},
		{"57f7230d-015b-4892-9042-cd1ea97fcb30", "0.0.1", "Kubernetes-Metrics-Server-Configuration"},
		{"57fd2528-fa40-4627-9a4a-67144982b9c3", "0.0.1", "Acme-Operator"},
		{"580d0f01-839b-4b44-90c3-a05656bfc2ab", "0.0.2", "ms-filestorage-rest"},
		{"58fc14c4-1ba6-41b6-8dd0-ed1dabd87215", "0.0.1", "Service-Internal-Traffic-Policy"},
		{"58fda714-eaa4-490f-b228-b8bcfe3a1e47", "0.0.1", "Example-Edge-Firewall-Relationship"},
		{"59e0f642-3249-46c3-9436-9e873b8eef56", "0.0.1", "prometheus.yaml"},
		{"5ace2887-9622-41da-bc55-55ce674ead02", "0.0.3", "ms-rbac-grpc"},
		{"5b19bed7-f6d2-4637-8506-9020fbd68740", "0.0.1", "Simple-Kubernetes-Pod-5b19"},
		{"5b755f6d-92fa-4616-aeb8-7c932baf3bc0", "0.0.1", "prometheus-opencost-exporter"},
		{"5d1f5f57-355e-49a4-b181-ead453d86cae", "0.0.2", "Hierarchical-Parent-Wallet-Relationship"},
		{"5d71d1b6-868e-456f-afb0-95f12410dbf9", "0.0.4", "ms-payments-worker-0.0.11.tgz"},
		{"5eeaef1f-9c17-4b52-b0bb-3e488ad15a2c", "0.0.1", "Meshery-v0.6.73"},
		{"5fdb64c5-80ca-4f6c-ba6e-1a1f98b553a9", "0.0.1", "Gerrit-operator"},
		{"6032511d-bb55-4bcf-bccd-582cd9e61ec0", "0.0.14", "Nginx-Controller"},
		{"6036b918-a3c7-4b16-9da1-8727909ab2be", "0.0.1", "ELK-stack"},
		{"60467829-05b2-4ccd-97b9-bb57221d42bc", "0.0.61", "Terraform_Architecture"},
		{"6046f07a-e9b5-4ffd-ad5d-d8d5f55a2203", "0.0.6", "Managing-Configuration-for-Kubernetes-Pods-6046"},
		{"60769e03-f392-4796-9c20-a141c6fa3ab2", "0.0.1", "Install-Traefik-as-ingress-controller"},
		{"616567e0-937b-46a3-8748-cdaa69f4be7f", "0.0.233", "Tutorial-Canary-Deployment-with-Meshery"},
		{"623a0154-3c09-4e52-9c87-fa8abeda2fe7", "0.0.1", "Pod-Volume-Mount-SubPath"},
		{"62e3f0ef-503e-4637-85d3-288584db81a5", "0.0.1", "KEDA-HTTPRequestsScaler"},
		{"6370ffcd-13a6-4a65-b426-30f1e63dc381", "0.0.1", "Hierarchical-Parent-Relationship-6370"},
		{"6482df99-27aa-4a51-9aab-92d2a2a9d0ca", "0.0.10", "Node-Problem-Detector"},
		{"661bf5e6-cf42-4804-8a74-f7fe651b8bb4", "0.0.8", "Azure-Monitor-Containers"},
		{"66d4e848-fe7e-4baf-b8db-9ff54d0113d6", "0.0.1", "QAT-TLS-handshake-acceleration-for-Istio"},
		{"66f483b2-5ca5-457a-b149-46a661468c34", "0.0.1", "webserver"},
		{"68a67a3a-eb39-472e-8d9c-a3b34fa23a71", "0.0.1", "Simple-MySQL-Pod"},
		{"69844b4a-d60d-4705-b255-edf2dbde0f5a", "0.0.1", "the-new-stack"},
		{"69afa37b-0ac4-4be5-a55e-ac4247dd3c1b", "0.0.156", "First_Contribution"},
		{"69afafc0-f0a6-4c6c-beae-c96956b40a4f", "0.0.1", "RuntimeClass"},
		{"69c0efd0-08bd-48f2-8b20-c172f3489ee2", "0.0.23", "Edge-Annotation-relationship"},
		{"69e3ebda-e5d7-436b-82ec-c0295a08122c", "0.0.2", "Azure-Istio-CICD-Mesh-Architecture-copy"},
		{"69fdde5f-c7fb-404f-b785-154586b354ae", "0.0.3", "Design-Annotation-Patterns-69fd"},
		{"6a0492fd-73b2-496d-9c5f-278c00d3a5ca", "0.0.1", "My-first-k8s-app"},
		{"6b6e5bbd-1c8b-4aab-87be-b7b397f2aeed", "0.0.5", "K8s-Cluster-overprovisioner"},
		{"6c6a05dd-dd82-41fc-a749-716408990eda", "0.0.2", "ditto-operator-0.3.0.tgz"},
		{"6d4bb838-2a05-447e-bba4-b59104ace089", "0.0.1", "Redis_using_configmap"},
		{"6da8edb1-cba2-4c81-b9d6-00dfb0386ad1", "0.0.1", "Wordpress-Deployment"},
		{"6ddc8245-74a0-4343-8619-0a9755b04fc2", "0.0.25", "k8s-webapp-deployment-service"},
		{"6e232806-21da-4ec5-9962-d23ea011b0bf", "0.0.72", "kubeflow-ecosystem-architecture"},
		{"6f3f0b77-3f4a-4639-b513-e7d6a0c57550", "0.0.583", "Untitled-Design-6f3f"},
		{"6f8474c8-d81b-43eb-83a0-52f71af4ce7b", "0.0.1", "Cloud-native-pizza-store"},
		{"7182c6f4-fe51-496f-8890-72ce45e36079", "0.0.1", "Nodejs-kubernetes-microservices"},
		{"7191dfdd-2c44-4235-acb7-688f5e99750d", "0.0.382", "Kubernetes-DaemonSet-Pattern"},
		{"71a28a89-6bf6-45c1-b6ad-d0dfb271d52f", "0.0.394", "Design-Reviews"},
		{"736a8f97-c3f8-4481-888a-1eff27414caa", "0.0.1", "node-feature-discovery"},
		{"7464feb1-450a-47d8-b03c-4318a4b62589", "0.0.84", "traefik-enterprise-architecture"},
		{"74b17e3a-3fc8-411c-8086-e4c13138bb65", "0.0.4", "ms-payments-grpc-0.0.11"},
		{"755b64db-59c5-41a3-896b-788aa579de41", "0.0.1", "Pod-Resource-Limit"},
		{"75cf43b6-5528-48c1-a3a7-1f996e8309fa", "0.0.3", "test-75cf"},
		{"7607aeb0-3248-4c89-8a63-22ccd8d9cf79", "0.0.1", "Nginx-Deployment-7607"},
		{"7656ade4-9934-4b51-b182-2e04ca70522e", "0.0.235", "Adobe-Flex-in-a-Box-Architecture"},
		{"792f17b4-08f5-4654-8c10-3628fd56ac03", "0.0.1", "ElasticSearch"},
		{"79fb7ba9-583d-4e04-af43-5fed438cd416", "0.0.1", "Simple-Kubernetes-Pod-79fb"},
		{"7a16f09c-c8d6-4ca5-aebf-f45f805afb30", "0.0.1", "mattermost-operator-1.0.4.tgz"},
		{"7a65270b-b5f1-4229-8abc-def9856cd06a", "0.0.1157", "Prometheus-and-Grafana-monitoring-stack"},
		{"7ab91040-5402-406f-8211-37c3ab9eb2bb", "0.0.1", "Prometheus-adapter"},
		{"7b1a4654-0215-4407-8057-f7669965960c", "0.0.16", "Edge-Network-Relationship-7b1a"},
		{"7b2e40b0-3cc8-4da3-bccd-b66bc6cd206a", "0.0.1", "Network-policy"},
		{"7b717cb2-24a1-4f4a-976e-ef1c9a982696", "0.0.242", "All-relationships-7b71"},
		{"7be5170d-d13e-4d83-bc1e-f1acc91b4048", "0.0.1", "nginx-ingress"},
		{"7d5f9d34-3bbc-4b31-a940-0a4f8583d4ac", "0.0.1", "GuestBook-App"},
		{"7d75f2d5-ca18-485d-b762-8429d46310a0", "0.0.2", "ms-emails-rest"},
		{"7dd39d30-7b14-4f9f-a66c-06ba3e5000fa", "0.0.1", "Example-Edge-Permission-Relationship"},
		{"7e3b5894-0e9f-470a-82fa-0b5d8a3a057c", "0.0.3", "Untitled-Design-7e3b"},
		{"7fae3c13-8807-4134-a35b-3c531fa21e4e", "0.0.1", "Pod-Node-Affinity"},
		{"80181f03-ff56-4c63-bfb1-0686fc50fee5", "0.0.15", "MERN"},
		{"812a64a6-800a-4d86-b2fd-ef1bc22f7bed", "0.0.25", "Vald-Helm-v1.7.17.tgz"},
		{"82688db0-647b-4086-b843-0b6856b92077", "0.0.45", "fullstack-app-design"},
		{"82af7058-6bb7-4f0c-a3c8-f8dc6fecfd9a", "0.0.2", "Deploy-Meshery-using-Meshery-82af"},
		{"83191f0e-001a-430e-8620-158a05323ac5", "0.0.8", "deployment-configmap-reference-relationship"},
		{"84b3e150-36a0-439f-a1f4-03d1aa240a45", "0.0.2", "myFirstMesheryDesign"},
		{"855884db-267b-4357-8e8e-cf189ec971a5", "0.0.1", "Redis-master-deployment"},
		{"856f2e02-5367-4dc4-981c-576d0c1c1ecb", "0.0.390", "Format-template"},
		{"858ebe68-4a49-4020-98c7-414ba7d2d198", "0.0.15", "Analytics-Dashboard-Backend"},
		{"85d5a84d-85e1-492d-98c7-6a365c00cc1b", "0.0.1", "MySQL-Deployment"},
		{"8652b112-80d7-4fde-bc87-9d2dbd4327cc", "0.0.1", "Pod-Volume-Mount-SubPath-expr"},
		{"86545f65-1034-437a-ac9b-ed85fe4dcdc8", "0.0.1", "Pod-Life-Cycle"},
		{"868df315-bbca-445a-8abb-fa7c53bc515c", "0.0.17", "three-test-publish"},
		{"8738285d-de4d-421a-aab7-e8760ba57537", "0.0.5", "NGINX-Pod-with-Meshery-Milestone-app"},
		{"877ec148-d9dd-4536-bfab-4dcab83ffec1", "0.0.383", "EventDrivenMicroservicesKafka"},
		{"88313950-0d4a-4f03-acc8-debfd3cf34b4", "0.0.19", "Edge-Permission-Relationship"},
		{"88794a57-f0f7-4ff6-9192-54ab7241ded8", "0.0.1", "Azure-monitor-containers"},
		{"88cdf94a-ffa9-4acf-9b24-bf0b6c024d89", "0.0.10", "Edge-Network-Relationship-Service-to-Deployment"},
		{"8aff6564-9e88-40f3-ae6f-75d92654d7b0", "0.0.2", "BitBucket-Publishing-Test"},
		{"8b041687-3c09-4cfd-8613-cf326a54e1b2", "0.0.1", "JAX-Hello-World-using-NVIDIA-GPUs-A100-80GB-on-GKE"},
		{"8b3a14d0-b822-4c0d-8051-571032558408", "0.0.28", "hello-nginx-design"},
		{"8b646678-95c0-42ec-b5c5-42f7b88a7791", "0.0.80", "fluentbit-log-pipeline"},
		{"8ba4a8da-9455-4079-a771-388eb5a14a21", "0.0.1", "Load-Balanced-AWS-Architecture"},
		{"8ba59757-4ae6-4568-be5c-32e32fe51031", "0.0.1", "Pod-Priviledged-Simple"},
		{"8ce06bfa-a917-44e5-b670-15c74ec177c0", "0.0.1", "marblerun"},
		{"8cff4bae-818f-4c9b-8511-a6feaabf6b1e", "0.0.1", "aspnet-core-6.0.0.tgz"},
		{"8d6526e4-3c85-44c4-bf2b-b45592fd880d", "0.0.3", "understanding-persistent-storage-in-kubernetes"},
		{"8de78d71-5b77-4858-b29a-b6acee15e636", "0.0.10", "testtt"},
		{"8f7e1431-3885-4ebf-9ef7-d2ec64bd4eb5", "0.0.44", "EC2-CONTROLLER-DESIGN"},
		{"90ae7d59-1eba-4ce5-b029-d14f79f1895f", "0.0.1", "Edge-Permission-Relationship-90ae"},
		{"9144ecb9-36e3-4b82-9725-b5e1b60d565a", "0.0.4", "Aws-Cloudwatch-Agent-for-Cluster-Metrics"},
		{"94889315-c812-4017-bb1e-17d3e6314d66", "0.0.3", "logstash-8.5.1"},
		{"9527442a-7072-4c98-a187-1b9ce1b0001c", "0.0.1", "Busybox-single"},
		{"95cb2be3-4052-45d9-9156-34fd4b8fe17e", "0.0.1", "Pod-Resource-Memory-Request-Limit"},
		{"962c49f4-39c0-4ce9-ad79-0adc78ebb4f5", "0.0.1", "Dapr-OAuth-Authorization-to-External-Service"},
		{"96c43aaf-4bd9-4f28-bc02-c64e3d26f1f8", "0.0.1", "fluentd-deployment"},
		{"96cc39d9-de6a-4339-96bf-096d09d9d7bd", "0.0.1", "Running-ZooKeeper"},
		{"971d44b4-3dd5-4a09-b87f-b8fac073c5dc", "0.0.1964", "Traefik-Proxy-Architecture"},
		{"977960d3-27d9-4fac-bf32-45d7ef604292", "0.0.40", "ELKK-Design-Kafka"},
		{"9814f836-0943-4f5e-a9f5-c5802d25dfeb", "0.0.1", "ms-emails-grpc-0.0.11.tgz"},
		{"9815d6cf-ef6d-49fa-99a7-97e935af67c4", "0.0.1", "fluentd-kubernetes-aws"},
		{"990eab50-9e7c-4f4e-93ed-410c921d9373", "0.0.78", "wordpress-ha-stack"},
		{"9b21dcd1-12a3-4fa2-a941-b28e72cd2b26", "0.0.127", "LoxiLB-Clustered-Load-Balancer-with-CGNAT"},
		{"9b677af7-478c-48d4-83a5-9b20d5094007", "0.0.1", "istio-ingress-service-web-api-v1-only"},
		{"9d3b33bf-eaf6-4d06-9dd6-64aa725ab383", "0.0.1", "Serve-an-LLM-with-multiple-GPUs-in-GKE"},
		{"9f249a4b-13da-4ea1-860e-98c4060a444a", "0.0.3", "pv-pvc-edge-non-binding-reference-relationship"},
		{"9f358588-ba37-4ebe-852d-df4dd0c71ecb", "0.0.2", "Hierarchical-Parent-Inventory-Relationship-9f35"},
		{"9fc0c134-4a85-4e59-8593-e93d9cc2fce2", "0.0.5", "Brainstorming-Template"},
		{"a10ca98d-d978-4cfd-accb-d9834a26904f", "0.0.280", "Kanvas-Docker-Extension-Architecture"},
		{"a1eaf8c4-4da3-4cc4-ba75-edc9e808ab98", "0.0.49", "ELKK-Stack-with-Kafka"},
		{"a2e7d86c-ff41-4385-9c19-81335a1204e7", "0.0.458", "Keycloak-SSO-with-OAuth2-Proxy-design"},
		{"a3a75d20-9453-4c80-a404-4d126fc72aa9", "0.0.1", "wordpress-26.0.0.tgz"},
		{"a5828d7d-d4eb-4e94-b013-ca804685cf15", "0.0.268", "Lightrun-Architecture"},
		{"a674263f-2e62-49e5-a986-2585b13c6591", "0.0.3", "Understanding-Relationships"},
		{"a67af210-22af-4115-a788-c64aadcd67ac", "0.0.5", "apache-11.3.5.tgz"},
		{"a70386a6-2b09-45dd-9c91-15b7beb0ac87", "0.0.1", "HAProxy_Ingress_Controller"},
		{"a71de4f9-bae8-4ccd-97a9-e05c4435ad82", "0.0.13", "test-design-a71d"},
		{"a7b25ce4-0ae2-45a8-bf20-36add30d5ff5", "0.0.7", "ms-catalogs-worker"},
		{"a7c1ed4b-0b4b-4614-afba-8d23082e27c3", "0.0.1", "Fortio-Server"},
		{"a7fdc9a5-4668-4e80-8580-1a557e68106e", "0.0.67", "Edge-Network-Relationship-Service-to-Deployment-a7fd"},
		{"a88ae43c-4a3c-4c57-b839-b1101e20f842", "0.0.1", "Kubernetes-Service-for-Product-Page-App"},
		{"a95b76ce-ceaf-4bdf-bac7-95a6773168cd", "0.0.616", "Kubernetes-Service-Traffic-Distribution"},
		{"aa3c3cc3-7506-49cf-8160-dfc2a448ff02", "0.0.11", "test-design-1"},
		{"aaae149b-95d2-458f-b3c1-710fb544acad", "0.0.6", "ebpf-exporter"},
		{"aaeda8bd-2133-4e52-bc3f-5014babb23a1", "0.0.697", "LoxiLB-Multi-Cloud-VPN-Connectivity"},
		{"ac4014f9-d320-4a39-9364-46a1b3627b33", "0.0.6", "robot-shop"},
		{"ae801c1f-8134-4f48-bc2e-d97c14f6a99c", "0.0.16", "ISCSI-pod-creation"},
		{"b00abde6-3416-4e3f-acbb-2af51adfd398", "0.0.1", "Untitled-Design-b00a"},
		{"b1e81bd2-787a-4bd2-88cd-932d53a57405", "0.0.3", "Publishing-test-microservice-architecture-spring-cloud"},
		{"b2b05f54-fd48-44f5-bf2d-308761874d59", "0.0.1", "Tutorial-Exploring-Kubernetes-Pods-With-Meshery"},
		{"b319f0f5-2abd-4f33-b134-824b5ac3ba2d", "0.0.1", "Persistent-Volume"},
		{"b597c1a5-a834-4f18-9351-4d78a8d4bfa2", "0.0.3", "ms-modules-rest"},
		{"b5f5dc10-40e3-473d-b77d-83e329285bdf", "0.0.2036", "Brainstorming-Template-b5f5"},
		{"b71276fc-524c-4dcc-9015-6fd9c9f589f5", "0.0.1", "Untitled-Design-b712"},
		{"b7782414-0dd6-486d-ba77-888577e9fa2e", "0.0.15", "elastic-stack"},
		{"b7bdd606-40a0-4849-a58e-d89af0d9688a", "0.0.1", "replication-controller"},
		{"b82e1abb-318b-4462-badc-494a21612381", "0.0.1", "KEDA-HTTPRequestsScaler-b82e"},
		{"b991c21e-5147-4aa9-bb8d-fce2b37bb3c3", "0.0.1", "GlusterFS-Service"},
		{"bb80642c-2179-4817-b0b7-6d0e28151f9a", "0.0.1", "nginx-deployment-bb80"},
		{"bbd15978-2924-48be-bac2-cdfc5331bfb2", "0.0.1", "Bank-of-Anthos"},
		{"bcd881e4-eaf6-4fe0-9d8c-80a07140cab7", "0.0.110", "Kubernetes-Cluster-Access-Model"},
		{"bda951e5-329a-48c8-a4e2-1f3d269cc8b6", "0.0.3", "Argocd-metrics"},
		{"be89d5ca-8a5a-4c2c-bc5e-3b974aa08380", "0.0.3", "Tutorial-Exploring-Kubernetes-Pod"},
		{"be8c9e9e-1a74-4c5a-b128-235364399410", "0.0.1", "Hierarchical-Inventory-Relationship"},
		{"bef1a2a2-9ae0-4d43-a277-13e8acd8149d", "0.0.2", "Rajshree"},
		{"bf5913ca-e6b3-4467-8830-7718b8b86636", "0.0.3", "Expose-NGINX-app-with-Ingress"},
		{"bffca2b7-b3c3-4a9d-86f4-bdae70848cfa", "0.0.2", "AWS-cloudfront-controller-bffc"},
		{"c0db1f13-46e8-481f-b5b5-27b6d2e0b74d", "0.0.1", "gke-online-serving-single-gpu"},
		{"c183b615-deb3-460e-b56f-55a1f87b1497", "0.0.186", "Vald-architecture"},
		{"c2141477-379b-432e-b47e-1c89600235a5", "0.0.453", "Meshery-Certification-Tracks"},
		{"c288c409-3ca4-4b20-86a2-c9a28c58f986", "0.0.1", "Guestbook-App-All-in-One"},
		{"c3180105-0fac-492c-810e-47aa41778ed2", "0.0.399", "Kubernetes-Cluster-Architecture"},
		{"c40ae08b-deaa-4fc5-a1e8-8081907b64a3", "0.0.1", "Simple-Kubernetes-Pod-c40a"},
		{"c4761073-5b69-47f4-948a-d1c25e0129b0", "0.0.3", "published"},
		{"c60f32ae-358b-4eab-81b6-2e52ef383bab", "0.0.1", "mattermost-operator"},
		{"c6dcd76c-a837-42f6-92b2-9dbaa6115bae", "0.0.25", "DevOps-Workflow"},
		{"c8320ac6-8b12-449b-a86f-d2a518a112c5", "0.0.856", "Architecture-Diagramming"},
		{"c8b4f9ed-ae71-47f1-b576-2c46ec927685", "0.0.20", "MS-Catalogs-gRPC-Microservice"},
		{"c920fb94-6c51-463a-9b71-c370ee76adf5", "0.0.1694", "Litmus-Architecture"},
		{"c9c97c00-9718-4e6c-a225-6168693e9ae1", "0.0.14", "Simple-Kubernetes-Pod-c9c9"},
		{"cabdb426-864e-4009-9b83-be23badeafe5", "0.0.1752", "k8s-Gateway-Api"},
		{"cc4fcaaa-5b7e-492c-9920-f2408bdcefed", "0.0.524", "LoxiLB-5G-Load-Balancer-LBO-architecture"},
		{"cca2fb89-48e1-419d-8e1b-e69e1e12931a", "0.0.41", "EC2-INSTANCES"},
		{"cce763fc-508a-4d3d-95da-0cfcf722d7cf", "0.0.1", "instana-agent-for-Kubernetes"},
		{"ce088baa-27d0-4bdd-8d89-71b4cfb8e236", "0.0.1", "ms-rbac-rest-0.0.11.tgz"},
		{"ce4eb460-b6c0-429d-befb-88cf2f1f883f", "0.0.1", "Consul-on-kubernetes"},
		{"cfde9483-de24-498f-869f-d8d74353a2af", "0.0.4", "all-pods-metal03"},
		{"d127a347-5af5-422a-b1ff-508fda5d239e", "0.0.3", "uptime-kuma"},
		{"d20a6041-ed06-454a-9d69-739ebaed4651", "0.0.1", "Simple-Kubernetes-Pod-d20a"},
		{"d223427e-1f46-4390-8fc9-51e499c44b7d", "0.0.3", "Kubernetes-Global-Balancer"},
		{"d3481e21-5000-4c90-a999-f53050863dc3", "0.0.1", "minIO-Deployment"},
		{"d427862d-4658-437c-97f3-44208f9c8c51", "0.0.437", "Mattermost-Server-Scaling-for-Azure-design"},
		{"d695eba0-7703-42f3-934f-f1779367281a", "0.0.1", "Jenkins-operator"},
		{"d6a40cd8-3c13-4920-a96c-b6278836565e", "0.0.1", "Tutorial-Simple-MySQL-Pod"},
		{"d6d78cdd-6bc8-4cb9-8ed3-c392e6152576", "0.0.1", "Limit-Range"},
		{"d79ab97f-86bd-44d1-8a37-aa05506b2b14", "0.0.2", "clickhouse-9.4.4-d79a"},
		{"d86c6005-fa0b-4f74-bb66-7e3e47cbc846", "0.0.1", "App-graph"},
		{"d8f5f7e8-eff0-4fb0-a144-18c2870f7678", "0.0.3", "copy-Tutorial-Exploring-Kubernetes-Pods-With-Meshery"},
		{"d9fdd47e-84d7-4395-b9e0-1f3db50df818", "0.0.1522", "Azure-Microservices-Architecture-with-AKS-design"},
		{"dbc5cf33-6db9-4644-a5aa-c8df5ffaf0a6", "0.0.109", "Expose-Kubernetes-App-with-NGINX-Ingress"},
		{"dc027e0a-ae6c-4d44-9d48-76d41322902a", "0.0.1", "datadog-3.127.1.tgz"},
		{"dc11f014-d259-41e3-a377-717d4fe960ae", "0.0.5", "authentik-2025.8.4.tgz"},
		{"df24a01a-8235-449f-8dad-4a2474059ad3", "0.0.1", "Amazon-Web-Services-IoT-Architecture-Diagram"},
		{"df7815d8-10dd-4001-90b9-c37e79136133", "0.0.1", "airflow-25.0.2.tgz"},
		{"df959bcd-09c8-40b1-bf58-47ad6be30cd7", "0.0.11", "EC2-CONTROLLER"},
		{"e0989a1d-1aa1-49cb-9eb4-a963f61fd328", "0.0.73", "Configure-a-Pod-to-Use-a-ConfigMap"},
		{"e0d62083-2575-42ba-984b-f547812ae9ac", "0.0.2", "E2E-Test-Design-Relationship"},
		{"e0eb807e-360a-4f65-9c6e-aa9e70ff9912", "0.0.1", "nexus3-5.15.0.tgz"},
		{"e17af2e2-b48d-42d9-98f2-01b9305c1b0f", "0.0.1", "apisix-6.0.0.tgz"},
		{"e1cb209f-e641-463f-903c-d54838b5db9a", "0.0.9", "test-kkk-team"},
		{"e2d3f5c8-3ff8-4756-8848-0c9b5797bec2", "0.0.1", "Pod-Service-Account-Token"},
		{"e31a3c6d-2102-4215-8ea2-3ab399ca29f6", "0.0.1", "Dapr-with-Kubernetes-events"},
		{"e5c65f06-4616-4ce7-9fe9-cb528128d242", "0.0.1", "knative-service"},
		{"e76bb526-8e8a-4f15-9dfe-df369bef344d", "0.0.3", "Hierarchical-Parent-Wallet-Relationship-e76b"},
		{"e79ebaa2-06f1-498b-8307-c434a8911b18", "0.0.1", "Online-Boutique"},
		{"e81a4aaa-fda4-4840-88ef-5d4a6a831553", "0.0.2", "datadog-3.127.1-e81a"},
		{"e81d639e-5c9b-4acb-8833-93a8e708f1b2", "0.0.4", "cert-manager-architecture-copy"},
		{"e92dba43-813f-4490-9b1b-541009d61ff8", "0.0.157", "Tutorial-Exploring-Kubernetes-Deployments-with-Meshery"},
		{"e958fd44-4a43-4096-9cd5-ef1e9204996f", "0.0.1", "KEDA-Setup-e958"},
		{"e9fd2bec-59bf-44ee-ba62-9ab9f0e090f7", "0.0.4", "publish-test"},
		{"ea07d238-15f4-4693-afe2-e413b3b93d6f", "0.0.1", "MySQL-installation-with-cinder-volume-plugin"},
		{"ea57586d-7d26-4367-bf9e-1a0fe1fe81f3", "0.0.1", "mysql-operator"},
		{"ea75ea93-1f5a-4c85-8efd-0d862599fbed", "0.0.1", "Pods-Image-Pull-Policy"},
		{"ead48885-d494-4dfd-a53a-ddc7b05ee761", "0.0.3", "glasskube-operator"},
		{"eb7a21e0-afd8-4263-94f2-e9083ac0b602", "0.0.1", "GuestBook-App-Copy"},
		{"ec343550-04ea-440f-b17e-5de2c171194a", "0.0.1", "Network-Service-Endpoint"},
		{"ec6a41d2-d2bd-4089-b1c2-72a5c76b9313", "0.0.1", "hello-app"},
		{"ec728414-5dd9-48a0-9be4-2ca0dffa1f2c", "0.0.4", "iscsi"},
		{"ee6fcb5e-852c-446c-91f4-9715116a7844", "0.0.467", "Kubernetes-Cluster-Architecture-Design"},
		{"f0cef2ff-73cd-42a8-99d6-2ba6c88eae30", "0.0.5", "ms-licenses-rest"},
		{"f0db31f1-10cf-4a2d-9b2d-e4c59d0522af", "0.0.35", "Pet-Adoption-Portal"},
		{"f129b08a-c024-441b-ba56-577c4f67665f", "0.0.1", "CryptoMB"},
		{"f139ae76-c6a1-4a61-b7e5-62852eb689cc", "0.0.374", "Kubernetes-Architecture"},
		{"f176d529-767d-485b-a68d-79db3f6e8dd2", "0.0.29", "Multi-tenancy-Virtual-Cluster"},
		{"f2a88e2b-6b1d-476f-979a-24635502f2c8", "0.0.1", "ms-catalogs-rest"},
		{"f4328c69-513c-4fa9-af37-27a2f1475cdf", "0.0.7", "Understanding-Relationships-f432"},
		{"f60a00b8-2038-48cc-9f44-818ffac4987f", "0.0.1", "Redis-Leader-Deployment"},
		{"f732b20e-08a0-4db0-9977-90b9009ced09", "0.0.1", "External-Dns-for-Kubernetes"},
		{"f752c99c-cbe9-4af2-98a7-c3b7a05b94b6", "0.0.1", "RBAC-for-ElasticSearch"},
		{"f8c65b6a-99a9-4694-8f96-92582f4c5b03", "0.0.16", "discoursedesign"},
		{"f90ecf87-6ca5-4d32-8ecf-f67cb20e3061", "0.0.1", "k8s-Deployment-2"},
		{"f967e5a4-9ca6-4fba-b9cd-5ee000576a91", "0.0.24", "Architectural-Design-Terraform"},
		{"f970dc8a-137e-49cc-a53e-362a924bf726", "0.0.4", "aws-k8s-cni"},
		{"fb0315e9-e6e5-4120-9a2f-b479ac2d2180", "0.0.39", "senthil-app-new"},
		{"fb725223-6246-4905-99e5-821a1341880e", "0.0.4", "publish-test-fb72"},
		{"fb8a31f7-0adb-40e7-ac26-bffb0a0f4547", "0.0.1", "Serving-T5-Large-Language-Model-with-TorchServe"},
		{"fde9c2da-e402-4f53-b7cd-02036ac65043", "0.0.1", "ZooKeeper-Cluster"},
		{"fdf70802-9e51-4e8e-a0a9-0f0480bf5741", "0.0.2", "Edge-Reference-Relationship"},
		{"fe260015-147d-487a-9e2c-44cbff354f60", "0.0.1", "Kubernetes-Deployment-with-Azure-File-Storage"},
		{"fe3bf101-18ec-4a7e-86bb-3f69a53b1e5f", "0.0.1", "Pod-Liveness"},
		{"ff84d220-d1ea-44ee-8473-a44b972ff85b", "0.0.1", "Pod-Resource-Memory-Request-Limit"},
		{"fffb7c9d-3051-4dd9-a198-39aee88da1d6", "0.0.1", "prometheus-postgres-exporter"},
	}
}

// --- Relationship fingerprinting for deep comparison ---

// relFingerprint uniquely identifies a relationship by its semantic content.
type relFingerprint struct {
	Kind    string
	Type    string
	SubType string
	FromID  string
	ToID    string
	Status  string
}

func (f relFingerprint) key() string {
	return fmt.Sprintf("%s/%s/%s|%s->%s", f.Kind, f.Type, f.SubType, f.FromID, f.ToID)
}

func (f relFingerprint) typeKey() string {
	return fmt.Sprintf("%s/%s/%s", f.Kind, f.Type, f.SubType)
}

func fingerprintRel(rel map[string]any) relFingerprint {
	return relFingerprint{
		Kind:    strings.ToLower(getMapString(rel, "kind")),
		Type:    strings.ToLower(getMapString(rel, "type")),
		SubType: strings.ToLower(getMapString(rel, "subType")),
		FromID:  relMapFromID(rel),
		ToID:    relMapToID(rel),
		Status:  strings.ToLower(getMapString(rel, "status")),
	}
}

// relMapFromID extracts the from component ID from a map-based relationship definition.
func relMapFromID(rel map[string]any) string {
	selectors, _ := rel["selectors"].([]any)
	if len(selectors) == 0 {
		return ""
	}
	ss, _ := selectors[0].(map[string]any)
	allow, _ := ss["allow"].(map[string]any)
	from, _ := allow["from"].([]any)
	if len(from) == 0 {
		return ""
	}
	fromItem, _ := from[0].(map[string]any)
	id, _ := fromItem["id"].(string)
	return id
}

// relMapToID extracts the to component ID from a map-based relationship definition.
func relMapToID(rel map[string]any) string {
	selectors, _ := rel["selectors"].([]any)
	if len(selectors) == 0 {
		return ""
	}
	ss, _ := selectors[0].(map[string]any)
	allow, _ := ss["allow"].(map[string]any)
	to, _ := allow["to"].([]any)
	if len(to) == 0 {
		return ""
	}
	toItem, _ := to[0].(map[string]any)
	id, _ := toItem["id"].(string)
	return id
}

// fingerprintTypedDesignRels fingerprints relationships from a typed PatternFile.
func fingerprintTypedDesignRels(design *pattern.PatternFile) []relFingerprint {
	var fps []relFingerprint
	for _, rel := range design.Relationships {
		if rel == nil {
			continue
		}
		fp := relFingerprint{
			Kind:    strings.ToLower(string(rel.Kind)),
			Type:    strings.ToLower(rel.RelationshipType),
			SubType: strings.ToLower(rel.SubType),
			FromID:  fromComponentID(rel),
			ToID:    toComponentID(rel),
			Status:  strings.ToLower(getRelStatus(rel)),
		}
		fps = append(fps, fp)
	}
	return fps
}

func fingerprintOPARels(opaDesign any) []relFingerprint {
	designMap, ok := opaDesign.(map[string]any)
	if !ok {
		return nil
	}
	rels, _ := designMap["relationships"].([]any)
	var fps []relFingerprint
	for _, r := range rels {
		rel, ok := r.(map[string]any)
		if !ok {
			continue
		}
		fps = append(fps, fingerprintRel(rel))
	}
	return fps
}

// relDiff computes which fingerprints are in A but not B (by key).
type relDiff struct {
	GoOnly  []relFingerprint
	OPAOnly []relFingerprint
	Common  []relFingerprint
}

func diffFingerprints(goFps, opaFps []relFingerprint) relDiff {
	goSet := make(map[string]relFingerprint, len(goFps))
	for _, f := range goFps {
		goSet[f.key()] = f
	}
	opaSet := make(map[string]relFingerprint, len(opaFps))
	for _, f := range opaFps {
		opaSet[f.key()] = f
	}

	var d relDiff
	for k, f := range goSet {
		if _, exists := opaSet[k]; exists {
			d.Common = append(d.Common, f)
		} else {
			d.GoOnly = append(d.GoOnly, f)
		}
	}
	for k, f := range opaSet {
		if _, exists := goSet[k]; !exists {
			d.OPAOnly = append(d.OPAOnly, f)
		}
	}
	return d
}

// typeDistFromFingerprints groups fingerprints by type key and returns counts.
func typeDistFromFingerprints(fps []relFingerprint) map[string]int {
	dist := make(map[string]int)
	for _, f := range fps {
		dist[f.typeKey()]++
	}
	return dist
}

// statusDistFromFingerprints groups fingerprints by status.
func statusDistFromFingerprints(fps []relFingerprint) map[string]int {
	dist := make(map[string]int)
	for _, f := range fps {
		s := f.Status
		if s == "" {
			s = "unknown"
		}
		dist[s]++
	}
	return dist
}

// --- Divergence classification (diff-driven) ---

type divergenceCategory string

const (
	catMatch         divergenceCategory = "MATCH"
	catDeepMatch     divergenceCategory = "DEEP_MATCH"
	catOPACrash      divergenceCategory = "OPA_CRASH"
	catOPANoResult   divergenceCategory = "OPA_NO_RESULT"
	catLegacyPrepass divergenceCategory = "LEGACY_PREPASS"
	catSetOrdering   divergenceCategory = "SET_ORDERING"
	catDeleteRetain  divergenceCategory = "DELETE_RETAIN"
	catOPATimeout    divergenceCategory = "OPA_TIMEOUT"
	catRelCountDiff  divergenceCategory = "REL_COUNT_DIFF"
	catContentDiff   divergenceCategory = "CONTENT_DIFF"
)

func classifyFromDiff(goFps, opaFps []relFingerprint, diff relDiff) divergenceCategory {
	// Count match: same relationships, same count
	if len(diff.GoOnly) == 0 && len(diff.OPAOnly) == 0 {
		return catDeepMatch
	}

	// OPA returned nothing while Go found relationships
	if len(opaFps) == 0 && len(goFps) > 0 {
		return catLegacyPrepass
	}

	// OPA retains deleted-status rels that Go correctly removes
	allOPAOnlyDeleted := len(diff.OPAOnly) > 0
	for _, f := range diff.OPAOnly {
		if f.Status != "deleted" {
			allOPAOnlyDeleted = false
			break
		}
	}
	if allOPAOnlyDeleted && len(diff.GoOnly) == 0 {
		return catDeleteRetain
	}

	// Go has strictly more rels of matchlabels type (OPA set ordering drops some)
	if len(diff.OPAOnly) == 0 && len(diff.GoOnly) > 0 {
		goOnlyTypes := typeDistFromFingerprints(diff.GoOnly)
		allMatchLabels := true
		for tk := range goOnlyTypes {
			if !strings.Contains(tk, "sibling") && !strings.Contains(tk, "matchlabels") {
				allMatchLabels = false
				break
			}
		}
		if allMatchLabels {
			return catSetOrdering
		}
	}

	if len(goFps) != len(opaFps) {
		return catRelCountDiff
	}

	return catContentDiff
}

// --- Result types ---

type designResult struct {
	name     string
	comps    int
	rels     int
	category divergenceCategory

	goRels  int
	opaRels int

	goFps  []relFingerprint
	opaFps []relFingerprint
	diff   relDiff

	goActions []PolicyAction

	goTime  time.Duration
	opaTime time.Duration

	opaErr string
}

type catalogDesignData struct {
	name string
	data map[string]any
}

// fetchCatalogDesigns downloads all catalog designs concurrently into memory.
// Nothing is written to disk.
func fetchCatalogDesigns(t *testing.T) []catalogDesignData {
	t.Helper()
	entries := catalogDesigns()
	client := &http.Client{Timeout: 30 * time.Second}

	t.Logf("Fetching %d catalog designs in-memory...", len(entries))

	type result struct {
		idx  int
		name string
		data map[string]any
	}

	sem := make(chan struct{}, 10)
	var wg sync.WaitGroup
	var mu sync.Mutex
	var fetched []result

	for i, d := range entries {
		wg.Add(1)
		go func(i int, d catalogEntry) {
			defer wg.Done()
			sem <- struct{}{}
			defer func() { <-sem }()

			url := fmt.Sprintf(
				"https://raw.githubusercontent.com/meshery/meshery.io/master/catalog/%s/%s/design.yml",
				d.id, d.version,
			)
			resp, err := client.Get(url)
			if err != nil || resp.StatusCode != http.StatusOK {
				return
			}
			defer func() { _ = resp.Body.Close() }()
			body, err := io.ReadAll(resp.Body)
			if err != nil {
				return
			}
			var m map[string]any
			if json.Unmarshal(body, &m) != nil {
				return
			}
			mu.Lock()
			fetched = append(fetched, result{idx: i, name: d.name, data: m})
			mu.Unlock()
		}(i, d)
	}
	wg.Wait()

	sort.Slice(fetched, func(i, j int) bool {
		return fetched[i].name < fetched[j].name
	})

	designs := make([]catalogDesignData, len(fetched))
	for i, r := range fetched {
		designs[i] = catalogDesignData{name: r.name, data: r.data}
	}

	t.Logf("Fetched %d designs", len(designs))
	return designs
}

func countRelationships(design map[string]any) int {
	return len(getMapSlice(design, "relationships"))
}

func countComponents(design map[string]any) int {
	return len(getMapSlice(design, "components"))
}

func truncName(name string, maxLen int) string {
	if len(name) <= maxLen {
		return name
	}
	return name[:maxLen-3] + "..."
}

func formatDuration(d time.Duration) string {
	if d == 0 {
		return "-"
	}
	if d < time.Millisecond {
		return fmt.Sprintf("%dus", d.Microseconds())
	}
	return fmt.Sprintf("%dms", d.Milliseconds())
}

func speedup(goTime, opaTime time.Duration) string {
	if goTime == 0 || opaTime == 0 {
		return "-"
	}
	return fmt.Sprintf("%.1fx", float64(opaTime)/float64(goTime))
}

// TestCatalogAlignment evaluates catalog designs through both engines,
// comparing internal behavior (per-relationship diff) and performance.
func TestCatalogAlignment(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping catalog alignment test in short mode")
	}
	designs := fetchCatalogDesigns(t)
	if len(designs) == 0 {
		t.Fatal("no designs found")
	}

	log, _ := logger.New("catalog-alignment", logger.Options{Format: logger.SyslogLogFormat})
	goEngine := NewGoEngine(log)
	opaModules := loadOPAModules(t)

	var results []designResult
	var totalGoTime, totalOPATime time.Duration

	for _, cd := range designs {
		design := cd.data
		comps := countComponents(design)
		rels := countRelationships(design)

		if rels == 0 {
			continue
		}

		// --- Go engine ---
		// Convert the map-based design to typed structs for the Go engine.
		typedDesign, convErr := mapToPatternFile(design)
		if convErr != nil {
			continue
		}
		relsInScope := typedDesign.Relationships
		goStart := time.Now()
		goTypedDesign, goActions := goEngine.evaluate(deepCopyDesign(typedDesign), relsInScope)
		goTime := time.Since(goStart)
		totalGoTime += goTime

		goFps := fingerprintTypedDesignRels(goTypedDesign)

		// --- OPA engine ---
		// Run eval in a goroutine so a hung OPA goroutine (e.g. ast.Compare
		// infinite recursion on cyclic data) doesn't block the whole test.
		opaData := map[string]any{"relationships": getMapSlice(design, "relationships")}
		store := inmem.NewFromObject(opaData)
		opts := append(opaModules,
			rego.Query("data.relationship_evaluation_policy.evaluate"),
			rego.Input(design),
			rego.Store(store),
		)

		type opaEval struct {
			rs  rego.ResultSet
			err error
		}

		opaStart := time.Now()
		r := rego.New(opts...)
		opaEvalCh := make(chan opaEval, 1)
		go func() {
			rs, err := r.Eval(context.Background())
			opaEvalCh <- opaEval{rs, err}
		}()

		const opaTimeout = 10 * time.Second
		var rs rego.ResultSet
		var opaErr error
		var opaTime time.Duration

		select {
		case result := <-opaEvalCh:
			rs = result.rs
			opaErr = result.err
			opaTime = time.Since(opaStart)
		case <-time.After(opaTimeout):
			// OPA goroutine is stuck (ast.Compare infinite loop). Leak it and move on.
			opaTime = opaTimeout
			totalOPATime += opaTime
			results = append(results, designResult{
				name: cd.name, comps: comps, rels: rels,
				category: catOPATimeout, goRels: len(goFps), goFps: goFps,
				goActions: goActions, goTime: goTime, opaTime: opaTime,
				opaErr: "OPA hung (ast.Compare infinite loop)",
			})
			continue
		}
		totalOPATime += opaTime

		if opaErr != nil {
			shortErr := opaErr.Error()
			if len(shortErr) > 80 {
				shortErr = shortErr[:80]
			}
			results = append(results, designResult{
				name: cd.name, comps: comps, rels: rels,
				category: catOPACrash, goRels: len(goFps), goFps: goFps,
				goActions: goActions, goTime: goTime, opaTime: opaTime,
				opaErr: shortErr,
			})
			continue
		}

		if len(rs) == 0 || len(rs[0].Expressions) == 0 {
			results = append(results, designResult{
				name: cd.name, comps: comps, rels: rels,
				category: catOPANoResult, goRels: len(goFps), goFps: goFps,
				goActions: goActions, goTime: goTime, opaTime: opaTime,
			})
			continue
		}

		opaResult, ok := rs[0].Expressions[0].Value.(map[string]any)
		if !ok {
			results = append(results, designResult{
				name: cd.name, comps: comps, rels: rels,
				category: catOPACrash, goRels: len(goFps), goFps: goFps,
				goActions: goActions, goTime: goTime, opaTime: opaTime,
				opaErr: "unexpected result type",
			})
			continue
		}

		opaFps := fingerprintOPARels(opaResult["design"])
		diff := diffFingerprints(goFps, opaFps)

		// Count-level match vs deep match
		var cat divergenceCategory
		if len(goFps) == len(opaFps) && len(diff.GoOnly) == 0 && len(diff.OPAOnly) == 0 {
			cat = catDeepMatch
		} else {
			cat = classifyFromDiff(goFps, opaFps, diff)
		}

		results = append(results, designResult{
			name: cd.name, comps: comps, rels: rels,
			category: cat,
			goRels:   len(goFps), opaRels: len(opaFps),
			goFps: goFps, opaFps: opaFps, diff: diff,
			goActions: goActions, goTime: goTime, opaTime: opaTime,
		})
	}

	// =========================================================================
	// TABLE 1: Per-design summary with timing
	// =========================================================================
	t.Logf("\n")
	t.Logf("TABLE 1: Per-design alignment and performance")
	t.Logf("%s", strings.Repeat("=", 140))
	t.Logf("%-42s %5s %5s %16s %6s %6s %5s %5s %8s %8s %7s",
		"Design", "Comps", "InRel", "Category", "GoRel", "OPARl", "GoAct", "Comm", "GoTime", "OPATime", "Speedup")
	t.Logf("%s", strings.Repeat("-", 140))

	for _, r := range results {
		name := truncName(r.name, 41)
		common := len(r.diff.Common)
		goAct := len(r.goActions)
		t.Logf("%-42s %5d %5d %16s %6d %6d %5d %5d %8s %8s %7s",
			name, r.comps, r.rels, r.category,
			r.goRels, r.opaRels, goAct, common,
			formatDuration(r.goTime), formatDuration(r.opaTime),
			speedup(r.goTime, r.opaTime))
	}

	t.Logf("%s", strings.Repeat("-", 140))
	t.Logf("%-42s %5s %5s %16s %6s %6s %5s %5s %8s %8s %7s",
		fmt.Sprintf("TOTAL (%d designs)", len(results)), "", "", "",
		"", "", "", "",
		formatDuration(totalGoTime), formatDuration(totalOPATime),
		speedup(totalGoTime, totalOPATime))

	// =========================================================================
	// TABLE 2: Category summary
	// =========================================================================
	t.Logf("\n")
	t.Logf("TABLE 2: Divergence category summary")
	t.Logf("%s", strings.Repeat("=", 100))

	type catEntry struct {
		cat   divergenceCategory
		count int
	}
	catCounts := make(map[divergenceCategory]int)
	for _, r := range results {
		catCounts[r.category]++
	}
	var catList []catEntry
	for c, n := range catCounts {
		catList = append(catList, catEntry{c, n})
	}
	sort.Slice(catList, func(i, j int) bool { return catList[i].count > catList[j].count })

	catLabels := map[divergenceCategory]string{
		catDeepMatch:     "Both engines produce identical relationships (content-level match)",
		catMatch:         "Same relationship count (content not compared due to OPA issues)",
		catOPACrash:      "OPA crashes with eval_conflict_error in patch_helper_rules.rego",
		catOPATimeout:    "OPA evaluation timed out (>10s per design)",
		catLegacyPrepass: "OPA legacy prepass (evaluation.rego:76-198) deletes all relationships before new flow",
		catSetOrdering:   "OPA Rego set-to-array conversion (evaluation.rego:206) drops matchlabel relationships",
		catDeleteRetain:  "OPA retains status=deleted relationships that Go correctly removes",
		catRelCountDiff:  "Relationship count differs (side-effect of legacy prepass or OPA bugs)",
		catContentDiff:   "Same count but different relationship content",
		catOPANoResult:   "OPA returns no evaluation result",
	}

	for _, e := range catList {
		label := catLabels[e.cat]
		t.Logf("  %-16s %3d  %s", e.cat, e.count, label)
	}

	// =========================================================================
	// TABLE 3: Per-relationship-type breakdown for divergent designs
	// =========================================================================
	t.Logf("\n")
	t.Logf("TABLE 3: Relationship type breakdown for divergent designs")
	t.Logf("%s", strings.Repeat("=", 120))

	for _, r := range results {
		if r.category == catDeepMatch || r.category == catMatch {
			continue
		}
		if r.category == catOPACrash || r.category == catOPANoResult || r.category == catOPATimeout {
			// For OPA crashes/timeouts, show Go-only output
			goDist := typeDistFromFingerprints(r.goFps)
			t.Logf("  %-40s [%s] Go produced %d rels, OPA crashed",
				truncName(r.name, 39), r.category, r.goRels)
			for tk, cnt := range goDist {
				t.Logf("    %-40s Go=%d OPA=n/a", tk, cnt)
			}
			continue
		}

		if len(r.diff.GoOnly) == 0 && len(r.diff.OPAOnly) == 0 {
			continue
		}

		t.Logf("  %-40s [%s] Go=%d OPA=%d common=%d",
			truncName(r.name, 39), r.category, r.goRels, r.opaRels, len(r.diff.Common))

		// Show type-level diff
		goOnlyDist := typeDistFromFingerprints(r.diff.GoOnly)
		opaOnlyDist := typeDistFromFingerprints(r.diff.OPAOnly)

		allTypes := make(map[string]bool)
		for tk := range goOnlyDist {
			allTypes[tk] = true
		}
		for tk := range opaOnlyDist {
			allTypes[tk] = true
		}

		var sortedTypes []string
		for tk := range allTypes {
			sortedTypes = append(sortedTypes, tk)
		}
		sort.Strings(sortedTypes)

		for _, tk := range sortedTypes {
			goN := goOnlyDist[tk]
			opaN := opaOnlyDist[tk]
			t.Logf("    %-40s Go-only=%d  OPA-only=%d", tk, goN, opaN)
		}

		// Show up to 5 specific Go-only relationships
		if len(r.diff.GoOnly) > 0 {
			limit := len(r.diff.GoOnly)
			if limit > 5 {
				limit = 5
			}
			for i := 0; i < limit; i++ {
				f := r.diff.GoOnly[i]
				t.Logf("      Go-only: %s  from=%s to=%s status=%s",
					f.typeKey(), short(f.FromID), short(f.ToID), f.Status)
			}
			if len(r.diff.GoOnly) > 5 {
				t.Logf("      ... and %d more Go-only relationships", len(r.diff.GoOnly)-5)
			}
		}

		// Show up to 5 specific OPA-only relationships
		if len(r.diff.OPAOnly) > 0 {
			limit := len(r.diff.OPAOnly)
			if limit > 5 {
				limit = 5
			}
			for i := 0; i < limit; i++ {
				f := r.diff.OPAOnly[i]
				t.Logf("      OPA-only: %s  from=%s to=%s status=%s",
					f.typeKey(), short(f.FromID), short(f.ToID), f.Status)
			}
			if len(r.diff.OPAOnly) > 5 {
				t.Logf("      ... and %d more OPA-only relationships", len(r.diff.OPAOnly)-5)
			}
		}
	}

	// =========================================================================
	// TABLE 4: Action distribution for Go engine
	// =========================================================================
	t.Logf("\n")
	t.Logf("TABLE 4: Go engine action distribution (all designs)")
	t.Logf("%s", strings.Repeat("=", 60))

	totalActionDist := make(map[string]int)
	for _, r := range results {
		for _, a := range r.goActions {
			totalActionDist[a.Op]++
		}
	}
	var actionOps []string
	for op := range totalActionDist {
		actionOps = append(actionOps, op)
	}
	sort.Strings(actionOps)
	for _, op := range actionOps {
		t.Logf("  %-40s %d", op, totalActionDist[op])
	}

	// =========================================================================
	// TABLE 5: Performance summary by category
	// =========================================================================
	t.Logf("\n")
	t.Logf("TABLE 5: Performance by divergence category")
	t.Logf("%s", strings.Repeat("=", 100))
	t.Logf("%-16s %5s %10s %10s %10s %10s",
		"Category", "Count", "AvgGoTime", "AvgOPATime", "MinSpeedup", "MaxSpeedup")
	t.Logf("%s", strings.Repeat("-", 100))

	type perfBucket struct {
		cat        divergenceCategory
		count      int
		totalGo    time.Duration
		totalOPA   time.Duration
		minSpeedup float64
		maxSpeedup float64
	}
	buckets := make(map[divergenceCategory]*perfBucket)
	for _, r := range results {
		b, exists := buckets[r.category]
		if !exists {
			b = &perfBucket{cat: r.category, minSpeedup: 1e9}
			buckets[r.category] = b
		}
		b.count++
		b.totalGo += r.goTime
		b.totalOPA += r.opaTime
		if r.goTime > 0 && r.opaTime > 0 {
			s := float64(r.opaTime) / float64(r.goTime)
			if s < b.minSpeedup {
				b.minSpeedup = s
			}
			if s > b.maxSpeedup {
				b.maxSpeedup = s
			}
		}
	}

	for _, e := range catList {
		b := buckets[e.cat]
		if b == nil {
			continue
		}
		avgGo := b.totalGo / time.Duration(b.count)
		avgOPA := b.totalOPA / time.Duration(b.count)
		minS := "-"
		maxS := "-"
		if b.minSpeedup < 1e9 {
			minS = fmt.Sprintf("%.1fx", b.minSpeedup)
		}
		if b.maxSpeedup > 0 {
			maxS = fmt.Sprintf("%.1fx", b.maxSpeedup)
		}
		t.Logf("%-16s %5d %10s %10s %10s %10s",
			e.cat, b.count,
			formatDuration(avgGo), formatDuration(avgOPA),
			minS, maxS)
	}

	// =========================================================================
	// TABLE 6: Status distribution comparison (for non-crash designs)
	// =========================================================================
	t.Logf("\n")
	t.Logf("TABLE 6: Relationship status distribution (Go vs OPA, non-crash designs)")
	t.Logf("%s", strings.Repeat("=", 80))

	goStatusTotal := make(map[string]int)
	opaStatusTotal := make(map[string]int)
	for _, r := range results {
		if r.category == catOPACrash || r.category == catOPANoResult || r.category == catOPATimeout {
			continue
		}
		for s, n := range statusDistFromFingerprints(r.goFps) {
			goStatusTotal[s] += n
		}
		for s, n := range statusDistFromFingerprints(r.opaFps) {
			opaStatusTotal[s] += n
		}
	}

	allStatuses := make(map[string]bool)
	for s := range goStatusTotal {
		allStatuses[s] = true
	}
	for s := range opaStatusTotal {
		allStatuses[s] = true
	}
	var sortedStatuses []string
	for s := range allStatuses {
		sortedStatuses = append(sortedStatuses, s)
	}
	sort.Strings(sortedStatuses)

	t.Logf("  %-20s %8s %8s", "Status", "Go", "OPA")
	t.Logf("  %s", strings.Repeat("-", 40))
	for _, s := range sortedStatuses {
		t.Logf("  %-20s %8d %8d", s, goStatusTotal[s], opaStatusTotal[s])
	}
}

func short(id string) string {
	if len(id) <= 8 {
		return id
	}
	return id[:8]
}

// mapToPatternFile converts a map-based design to a typed PatternFile via JSON round-trip.
func mapToPatternFile(m map[string]any) (*pattern.PatternFile, error) {
	data, err := json.Marshal(m)
	if err != nil {
		return nil, err
	}
	var pf pattern.PatternFile
	if err := json.Unmarshal(data, &pf); err != nil {
		return nil, err
	}
	return &pf, nil
}
