// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meshops.proto

package meshes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EventType int32

const (
	EventType_INFO  EventType = 0
	EventType_WARN  EventType = 1
	EventType_ERROR EventType = 2
)

var EventType_name = map[int32]string{
	0: "INFO",
	1: "WARN",
	2: "ERROR",
}
var EventType_value = map[string]int32{
	"INFO":  0,
	"WARN":  1,
	"ERROR": 2,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}
func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_meshops_b7cfde95663509a1, []int{0}
}

type CreateMeshInstanceRequest struct {
	K8SConfig            []byte   `protobuf:"bytes,1,opt,name=k8sConfig,proto3" json:"k8sConfig,omitempty"`
	ContextName          string   `protobuf:"bytes,2,opt,name=contextName,proto3" json:"contextName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMeshInstanceRequest) Reset()         { *m = CreateMeshInstanceRequest{} }
func (m *CreateMeshInstanceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMeshInstanceRequest) ProtoMessage()    {}
func (*CreateMeshInstanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meshops_b7cfde95663509a1, []int{0}
}
func (m *CreateMeshInstanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMeshInstanceRequest.Unmarshal(m, b)
}
func (m *CreateMeshInstanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMeshInstanceRequest.Marshal(b, m, deterministic)
}
func (dst *CreateMeshInstanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMeshInstanceRequest.Merge(dst, src)
}
func (m *CreateMeshInstanceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMeshInstanceRequest.Size(m)
}
func (m *CreateMeshInstanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMeshInstanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMeshInstanceRequest proto.InternalMessageInfo

func (m *CreateMeshInstanceRequest) GetK8SConfig() []byte {
	if m != nil {
		return m.K8SConfig
	}
	return nil
}

func (m *CreateMeshInstanceRequest) GetContextName() string {
	if m != nil {
		return m.ContextName
	}
	return ""
}

type CreateMeshInstanceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMeshInstanceResponse) Reset()         { *m = CreateMeshInstanceResponse{} }
func (m *CreateMeshInstanceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMeshInstanceResponse) ProtoMessage()    {}
func (*CreateMeshInstanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_meshops_b7cfde95663509a1, []int{1}
}
func (m *CreateMeshInstanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMeshInstanceResponse.Unmarshal(m, b)
}
func (m *CreateMeshInstanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMeshInstanceResponse.Marshal(b, m, deterministic)
}
func (dst *CreateMeshInstanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMeshInstanceResponse.Merge(dst, src)
}
func (m *CreateMeshInstanceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMeshInstanceResponse.Size(m)
}
func (m *CreateMeshInstanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMeshInstanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMeshInstanceResponse proto.InternalMessageInfo

type MeshNameRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeshNameRequest) Reset()         { *m = MeshNameRequest{} }
func (m *MeshNameRequest) String() string { return proto.CompactTextString(m) }
func (*MeshNameRequest) ProtoMessage()    {}
func (*MeshNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meshops_b7cfde95663509a1, []int{2}
}
func (m *MeshNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshNameRequest.Unmarshal(m, b)
}
func (m *MeshNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshNameRequest.Marshal(b, m, deterministic)
}
func (dst *MeshNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshNameRequest.Merge(dst, src)
}
func (m *MeshNameRequest) XXX_Size() int {
	return xxx_messageInfo_MeshNameRequest.Size(m)
}
func (m *MeshNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MeshNameRequest proto.InternalMessageInfo

type MeshNameResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeshNameResponse) Reset()         { *m = MeshNameResponse{} }
func (m *MeshNameResponse) String() string { return proto.CompactTextString(m) }
func (*MeshNameResponse) ProtoMessage()    {}
func (*MeshNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_meshops_b7cfde95663509a1, []int{3}
}
func (m *MeshNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshNameResponse.Unmarshal(m, b)
}
func (m *MeshNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshNameResponse.Marshal(b, m, deterministic)
}
func (dst *MeshNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshNameResponse.Merge(dst, src)
}
func (m *MeshNameResponse) XXX_Size() int {
	return xxx_messageInfo_MeshNameResponse.Size(m)
}
func (m *MeshNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MeshNameResponse proto.InternalMessageInfo

func (m *MeshNameResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ApplyRuleRequest struct {
	OpName               string   `protobuf:"bytes,1,opt,name=opName,proto3" json:"opName,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	CustomBody           string   `protobuf:"bytes,4,opt,name=custom_body,json=customBody,proto3" json:"custom_body,omitempty"`
	DeleteOp             bool     `protobuf:"varint,5,opt,name=delete_op,json=deleteOp,proto3" json:"delete_op,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyRuleRequest) Reset()         { *m = ApplyRuleRequest{} }
func (m *ApplyRuleRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyRuleRequest) ProtoMessage()    {}
func (*ApplyRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meshops_b7cfde95663509a1, []int{4}
}
func (m *ApplyRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyRuleRequest.Unmarshal(m, b)
}
func (m *ApplyRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyRuleRequest.Marshal(b, m, deterministic)
}
func (dst *ApplyRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyRuleRequest.Merge(dst, src)
}
func (m *ApplyRuleRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyRuleRequest.Size(m)
}
func (m *ApplyRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyRuleRequest proto.InternalMessageInfo

func (m *ApplyRuleRequest) GetOpName() string {
	if m != nil {
		return m.OpName
	}
	return ""
}

func (m *ApplyRuleRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ApplyRuleRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ApplyRuleRequest) GetCustomBody() string {
	if m != nil {
		return m.CustomBody
	}
	return ""
}

func (m *ApplyRuleRequest) GetDeleteOp() bool {
	if m != nil {
		return m.DeleteOp
	}
	return false
}

type ApplyRuleResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyRuleResponse) Reset()         { *m = ApplyRuleResponse{} }
func (m *ApplyRuleResponse) String() string { return proto.CompactTextString(m) }
func (*ApplyRuleResponse) ProtoMessage()    {}
func (*ApplyRuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_meshops_b7cfde95663509a1, []int{5}
}
func (m *ApplyRuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyRuleResponse.Unmarshal(m, b)
}
func (m *ApplyRuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyRuleResponse.Marshal(b, m, deterministic)
}
func (dst *ApplyRuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyRuleResponse.Merge(dst, src)
}
func (m *ApplyRuleResponse) XXX_Size() int {
	return xxx_messageInfo_ApplyRuleResponse.Size(m)
}
func (m *ApplyRuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyRuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyRuleResponse proto.InternalMessageInfo

func (m *ApplyRuleResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SupportedOperationsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SupportedOperationsRequest) Reset()         { *m = SupportedOperationsRequest{} }
func (m *SupportedOperationsRequest) String() string { return proto.CompactTextString(m) }
func (*SupportedOperationsRequest) ProtoMessage()    {}
func (*SupportedOperationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meshops_b7cfde95663509a1, []int{6}
}
func (m *SupportedOperationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupportedOperationsRequest.Unmarshal(m, b)
}
func (m *SupportedOperationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupportedOperationsRequest.Marshal(b, m, deterministic)
}
func (dst *SupportedOperationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupportedOperationsRequest.Merge(dst, src)
}
func (m *SupportedOperationsRequest) XXX_Size() int {
	return xxx_messageInfo_SupportedOperationsRequest.Size(m)
}
func (m *SupportedOperationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SupportedOperationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SupportedOperationsRequest proto.InternalMessageInfo

type SupportedOperationsResponse struct {
	Ops                  map[string]string `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Error                string            `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SupportedOperationsResponse) Reset()         { *m = SupportedOperationsResponse{} }
func (m *SupportedOperationsResponse) String() string { return proto.CompactTextString(m) }
func (*SupportedOperationsResponse) ProtoMessage()    {}
func (*SupportedOperationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_meshops_b7cfde95663509a1, []int{7}
}
func (m *SupportedOperationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupportedOperationsResponse.Unmarshal(m, b)
}
func (m *SupportedOperationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupportedOperationsResponse.Marshal(b, m, deterministic)
}
func (dst *SupportedOperationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupportedOperationsResponse.Merge(dst, src)
}
func (m *SupportedOperationsResponse) XXX_Size() int {
	return xxx_messageInfo_SupportedOperationsResponse.Size(m)
}
func (m *SupportedOperationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SupportedOperationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SupportedOperationsResponse proto.InternalMessageInfo

func (m *SupportedOperationsResponse) GetOps() map[string]string {
	if m != nil {
		return m.Ops
	}
	return nil
}

func (m *SupportedOperationsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SupportedOperation struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SupportedOperation) Reset()         { *m = SupportedOperation{} }
func (m *SupportedOperation) String() string { return proto.CompactTextString(m) }
func (*SupportedOperation) ProtoMessage()    {}
func (*SupportedOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_meshops_b7cfde95663509a1, []int{8}
}
func (m *SupportedOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupportedOperation.Unmarshal(m, b)
}
func (m *SupportedOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupportedOperation.Marshal(b, m, deterministic)
}
func (dst *SupportedOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupportedOperation.Merge(dst, src)
}
func (m *SupportedOperation) XXX_Size() int {
	return xxx_messageInfo_SupportedOperation.Size(m)
}
func (m *SupportedOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_SupportedOperation.DiscardUnknown(m)
}

var xxx_messageInfo_SupportedOperation proto.InternalMessageInfo

func (m *SupportedOperation) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SupportedOperation) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EventsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventsRequest) Reset()         { *m = EventsRequest{} }
func (m *EventsRequest) String() string { return proto.CompactTextString(m) }
func (*EventsRequest) ProtoMessage()    {}
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_meshops_b7cfde95663509a1, []int{9}
}
func (m *EventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsRequest.Unmarshal(m, b)
}
func (m *EventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsRequest.Marshal(b, m, deterministic)
}
func (dst *EventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsRequest.Merge(dst, src)
}
func (m *EventsRequest) XXX_Size() int {
	return xxx_messageInfo_EventsRequest.Size(m)
}
func (m *EventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventsRequest proto.InternalMessageInfo

type EventsResponse struct {
	EventType            EventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=meshes.EventType" json:"event_type,omitempty"`
	Summary              string    `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Details              string    `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EventsResponse) Reset()         { *m = EventsResponse{} }
func (m *EventsResponse) String() string { return proto.CompactTextString(m) }
func (*EventsResponse) ProtoMessage()    {}
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_meshops_b7cfde95663509a1, []int{10}
}
func (m *EventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsResponse.Unmarshal(m, b)
}
func (m *EventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsResponse.Marshal(b, m, deterministic)
}
func (dst *EventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsResponse.Merge(dst, src)
}
func (m *EventsResponse) XXX_Size() int {
	return xxx_messageInfo_EventsResponse.Size(m)
}
func (m *EventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventsResponse proto.InternalMessageInfo

func (m *EventsResponse) GetEventType() EventType {
	if m != nil {
		return m.EventType
	}
	return EventType_INFO
}

func (m *EventsResponse) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *EventsResponse) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateMeshInstanceRequest)(nil), "meshes.CreateMeshInstanceRequest")
	proto.RegisterType((*CreateMeshInstanceResponse)(nil), "meshes.CreateMeshInstanceResponse")
	proto.RegisterType((*MeshNameRequest)(nil), "meshes.MeshNameRequest")
	proto.RegisterType((*MeshNameResponse)(nil), "meshes.MeshNameResponse")
	proto.RegisterType((*ApplyRuleRequest)(nil), "meshes.ApplyRuleRequest")
	proto.RegisterType((*ApplyRuleResponse)(nil), "meshes.ApplyRuleResponse")
	proto.RegisterType((*SupportedOperationsRequest)(nil), "meshes.SupportedOperationsRequest")
	proto.RegisterType((*SupportedOperationsResponse)(nil), "meshes.SupportedOperationsResponse")
	proto.RegisterMapType((map[string]string)(nil), "meshes.SupportedOperationsResponse.OpsEntry")
	proto.RegisterType((*SupportedOperation)(nil), "meshes.SupportedOperation")
	proto.RegisterType((*EventsRequest)(nil), "meshes.EventsRequest")
	proto.RegisterType((*EventsResponse)(nil), "meshes.EventsResponse")
	proto.RegisterEnum("meshes.EventType", EventType_name, EventType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MeshServiceClient is the client API for MeshService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MeshServiceClient interface {
	CreateMeshInstance(ctx context.Context, in *CreateMeshInstanceRequest, opts ...grpc.CallOption) (*CreateMeshInstanceResponse, error)
	MeshName(ctx context.Context, in *MeshNameRequest, opts ...grpc.CallOption) (*MeshNameResponse, error)
	ApplyOperation(ctx context.Context, in *ApplyRuleRequest, opts ...grpc.CallOption) (*ApplyRuleResponse, error)
	SupportedOperations(ctx context.Context, in *SupportedOperationsRequest, opts ...grpc.CallOption) (*SupportedOperationsResponse, error)
	StreamEvents(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (MeshService_StreamEventsClient, error)
}

type meshServiceClient struct {
	cc *grpc.ClientConn
}

func NewMeshServiceClient(cc *grpc.ClientConn) MeshServiceClient {
	return &meshServiceClient{cc}
}

func (c *meshServiceClient) CreateMeshInstance(ctx context.Context, in *CreateMeshInstanceRequest, opts ...grpc.CallOption) (*CreateMeshInstanceResponse, error) {
	out := new(CreateMeshInstanceResponse)
	err := c.cc.Invoke(ctx, "/meshes.MeshService/CreateMeshInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) MeshName(ctx context.Context, in *MeshNameRequest, opts ...grpc.CallOption) (*MeshNameResponse, error) {
	out := new(MeshNameResponse)
	err := c.cc.Invoke(ctx, "/meshes.MeshService/MeshName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) ApplyOperation(ctx context.Context, in *ApplyRuleRequest, opts ...grpc.CallOption) (*ApplyRuleResponse, error) {
	out := new(ApplyRuleResponse)
	err := c.cc.Invoke(ctx, "/meshes.MeshService/ApplyOperation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) SupportedOperations(ctx context.Context, in *SupportedOperationsRequest, opts ...grpc.CallOption) (*SupportedOperationsResponse, error) {
	out := new(SupportedOperationsResponse)
	err := c.cc.Invoke(ctx, "/meshes.MeshService/SupportedOperations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) StreamEvents(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (MeshService_StreamEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MeshService_serviceDesc.Streams[0], "/meshes.MeshService/StreamEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &meshServiceStreamEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MeshService_StreamEventsClient interface {
	Recv() (*EventsResponse, error)
	grpc.ClientStream
}

type meshServiceStreamEventsClient struct {
	grpc.ClientStream
}

func (x *meshServiceStreamEventsClient) Recv() (*EventsResponse, error) {
	m := new(EventsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MeshServiceServer is the server API for MeshService service.
type MeshServiceServer interface {
	CreateMeshInstance(context.Context, *CreateMeshInstanceRequest) (*CreateMeshInstanceResponse, error)
	MeshName(context.Context, *MeshNameRequest) (*MeshNameResponse, error)
	ApplyOperation(context.Context, *ApplyRuleRequest) (*ApplyRuleResponse, error)
	SupportedOperations(context.Context, *SupportedOperationsRequest) (*SupportedOperationsResponse, error)
	StreamEvents(*EventsRequest, MeshService_StreamEventsServer) error
}

func RegisterMeshServiceServer(s *grpc.Server, srv MeshServiceServer) {
	s.RegisterService(&_MeshService_serviceDesc, srv)
}

func _MeshService_CreateMeshInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMeshInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).CreateMeshInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meshes.MeshService/CreateMeshInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).CreateMeshInstance(ctx, req.(*CreateMeshInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_MeshName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeshNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).MeshName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meshes.MeshService/MeshName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).MeshName(ctx, req.(*MeshNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_ApplyOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).ApplyOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meshes.MeshService/ApplyOperation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).ApplyOperation(ctx, req.(*ApplyRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_SupportedOperations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupportedOperationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).SupportedOperations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meshes.MeshService/SupportedOperations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).SupportedOperations(ctx, req.(*SupportedOperationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MeshServiceServer).StreamEvents(m, &meshServiceStreamEventsServer{stream})
}

type MeshService_StreamEventsServer interface {
	Send(*EventsResponse) error
	grpc.ServerStream
}

type meshServiceStreamEventsServer struct {
	grpc.ServerStream
}

func (x *meshServiceStreamEventsServer) Send(m *EventsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _MeshService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "meshes.MeshService",
	HandlerType: (*MeshServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMeshInstance",
			Handler:    _MeshService_CreateMeshInstance_Handler,
		},
		{
			MethodName: "MeshName",
			Handler:    _MeshService_MeshName_Handler,
		},
		{
			MethodName: "ApplyOperation",
			Handler:    _MeshService_ApplyOperation_Handler,
		},
		{
			MethodName: "SupportedOperations",
			Handler:    _MeshService_SupportedOperations_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _MeshService_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "meshops.proto",
}

func init() { proto.RegisterFile("meshops.proto", fileDescriptor_meshops_b7cfde95663509a1) }

var fileDescriptor_meshops_b7cfde95663509a1 = []byte{
	// 577 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x51, 0x6f, 0xd3, 0x40,
	0x0c, 0x5e, 0xda, 0x6d, 0x24, 0xee, 0xd6, 0xa5, 0x07, 0x8c, 0x2c, 0x9b, 0x44, 0x09, 0x12, 0x2a,
	0x13, 0xaa, 0xa6, 0x22, 0xa1, 0x09, 0x21, 0x50, 0x99, 0x0a, 0xda, 0x03, 0xad, 0x94, 0x22, 0xf1,
	0x80, 0x50, 0xc9, 0x5a, 0xc3, 0xaa, 0x35, 0xb9, 0xe3, 0xee, 0x52, 0x91, 0xdf, 0xc2, 0x1b, 0xaf,
	0xfc, 0x49, 0x74, 0x49, 0x2e, 0x29, 0x6d, 0xa9, 0xf6, 0x76, 0xfe, 0x6c, 0x7f, 0xfe, 0x1c, 0xdb,
	0x81, 0xfd, 0x10, 0xc5, 0x35, 0x65, 0xa2, 0xcd, 0x38, 0x95, 0x94, 0xec, 0x2a, 0x13, 0x85, 0xf7,
	0x19, 0x8e, 0x2e, 0x38, 0x06, 0x12, 0x3f, 0xa0, 0xb8, 0xbe, 0x8c, 0x84, 0x0c, 0xa2, 0x31, 0xfa,
	0xf8, 0x23, 0x46, 0x21, 0xc9, 0x09, 0x58, 0x37, 0xe7, 0xe2, 0x82, 0x46, 0xdf, 0xa6, 0xdf, 0x1d,
	0xa3, 0x69, 0xb4, 0xf6, 0xfc, 0x12, 0x20, 0x4d, 0xa8, 0x8d, 0x69, 0x24, 0xf1, 0xa7, 0xec, 0x07,
	0x21, 0x3a, 0x95, 0xa6, 0xd1, 0xb2, 0xfc, 0x45, 0xc8, 0x3b, 0x01, 0x77, 0x1d, 0xb9, 0x60, 0x34,
	0x12, 0xe8, 0x35, 0xe0, 0x40, 0xe1, 0x2a, 0x32, 0x2f, 0xe8, 0x3d, 0x01, 0xbb, 0x84, 0xb2, 0x30,
	0x42, 0x60, 0x3b, 0x52, 0xfc, 0x46, 0xca, 0x9f, 0xbe, 0xbd, 0xdf, 0x06, 0xd8, 0x5d, 0xc6, 0x66,
	0x89, 0x1f, 0xcf, 0x0a, 0xb5, 0x87, 0xb0, 0x4b, 0x59, 0xbf, 0x0c, 0xcd, 0x2d, 0xd5, 0x85, 0x4a,
	0x12, 0x2c, 0x18, 0x6b, 0x95, 0x25, 0x40, 0x5c, 0x30, 0x63, 0x81, 0x3c, 0x2d, 0x51, 0x4d, 0x9d,
	0x85, 0x4d, 0x1e, 0x42, 0x6d, 0x1c, 0x0b, 0x49, 0xc3, 0xd1, 0x15, 0x9d, 0x24, 0xce, 0x76, 0xea,
	0x86, 0x0c, 0x7a, 0x4b, 0x27, 0x09, 0x39, 0x06, 0x6b, 0x82, 0x33, 0x94, 0x38, 0xa2, 0xcc, 0xd9,
	0x69, 0x1a, 0x2d, 0xd3, 0x37, 0x33, 0x60, 0xc0, 0xbc, 0xa7, 0xd0, 0x58, 0xd0, 0x98, 0x77, 0x73,
	0x0f, 0x76, 0x90, 0x73, 0xca, 0x73, 0x8d, 0x99, 0xa1, 0x3e, 0xd4, 0x30, 0x66, 0x8c, 0x72, 0x89,
	0x93, 0x01, 0x43, 0x1e, 0xc8, 0x29, 0x8d, 0x84, 0xfe, 0x2a, 0x7f, 0x0c, 0x38, 0x5e, 0xeb, 0xce,
	0x39, 0x5f, 0x43, 0x95, 0x32, 0xe1, 0x18, 0xcd, 0x6a, 0xab, 0xd6, 0x79, 0xd6, 0xce, 0x26, 0xdb,
	0xde, 0x90, 0xd1, 0x1e, 0x30, 0xd1, 0x8b, 0x24, 0x4f, 0x7c, 0x95, 0x58, 0x6a, 0xaa, 0x2c, 0x68,
	0x72, 0x5f, 0x80, 0xa9, 0xc3, 0x88, 0x0d, 0xd5, 0x1b, 0x4c, 0x72, 0xcd, 0xea, 0xa9, 0x72, 0xe6,
	0xc1, 0x2c, 0xd6, 0x1f, 0x34, 0x33, 0x5e, 0x56, 0xce, 0x0d, 0xef, 0x15, 0x90, 0xd5, 0xd2, 0xb7,
	0x65, 0xf0, 0x0e, 0x60, 0xbf, 0x37, 0xc7, 0x48, 0x16, 0xcd, 0xcf, 0xa1, 0xae, 0x81, 0xbc, 0xdd,
	0x33, 0x00, 0x54, 0xc8, 0x48, 0x26, 0x2c, 0x9b, 0x75, 0xbd, 0xd3, 0xd0, 0x5d, 0xa7, 0xb1, 0x1f,
	0x13, 0x86, 0xbe, 0x85, 0xfa, 0x49, 0x1c, 0xb8, 0x23, 0xe2, 0x30, 0x0c, 0x78, 0x92, 0x17, 0xd3,
	0xa6, 0xf2, 0x4c, 0x50, 0x06, 0xd3, 0x99, 0xc8, 0x87, 0xaf, 0xcd, 0xd3, 0x53, 0xb0, 0x0a, 0x2e,
	0x62, 0xc2, 0xf6, 0x65, 0xff, 0xdd, 0xc0, 0xde, 0x52, 0xaf, 0x4f, 0x5d, 0xbf, 0x6f, 0x1b, 0xc4,
	0x82, 0x9d, 0x9e, 0xef, 0x0f, 0x7c, 0xbb, 0xd2, 0xf9, 0x55, 0x85, 0x9a, 0xda, 0xdb, 0x21, 0xf2,
	0xf9, 0x74, 0x8c, 0xe4, 0x0b, 0x90, 0xd5, 0xbd, 0x27, 0x8f, 0xb4, 0xc6, 0xff, 0x1e, 0x9c, 0xeb,
	0x6d, 0x0a, 0xc9, 0xcf, 0x66, 0x8b, 0xbc, 0x01, 0x53, 0x5f, 0x09, 0x79, 0xa0, 0x33, 0x96, 0x4e,
	0xc9, 0x75, 0x56, 0x1d, 0x05, 0xc1, 0x7b, 0xa8, 0xa7, 0x9b, 0x59, 0x8e, 0xa7, 0x88, 0x5e, 0xbe,
	0x2a, 0xf7, 0x68, 0x8d, 0xa7, 0x20, 0xfa, 0x0a, 0x77, 0xd7, 0xac, 0x19, 0xf1, 0x36, 0xee, 0x60,
	0xc6, 0xfb, 0xf8, 0x16, 0x7b, 0xea, 0x6d, 0x91, 0x2e, 0xec, 0x0d, 0x25, 0xc7, 0x20, 0xcc, 0x96,
	0x80, 0xdc, 0xff, 0x67, 0xd0, 0x05, 0xdb, 0xe1, 0x32, 0xac, 0x09, 0xce, 0x8c, 0xab, 0xdd, 0xf4,
	0x8f, 0xf7, 0xfc, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xed, 0xf5, 0xd5, 0x64, 0x02, 0x05, 0x00,
	0x00,
}
