#!/bin/sh

# Run make target for meshery server
echo "Running make target for meshery server meshkit error duplicacy"
make error

# Run make target for mesheryctl
echo "Running make target for mesheryctl meshkit error duplicacy"
cd mesheryctl
make error

if [ $? -ne 0 ]; then
    echo "Aborting commit Meshkit Error Duplicacy found"
    exit 1
fi