#!/bin/sh

# Run make target for meshery server
echo "Running make target for meshery server meshkit error duplicacy"
output=$(make error)
output_length=${#output}

if [ $output_length -gt 1 ]; then
    echo "Aborting commit Meshkit Error Duplicacy found in Meshery Server ..."
    exit 1
fi

# Run make target for mesheryctl
echo "Running make target for mesheryctl meshkit error duplicacy"
cd mesheryctl
output=$(make error)
output_length=${#output}

if [ $output_length -gt 1 ]; then
    echo "Aborting commit Meshkit Error Duplicacy found in Mesheryctl ..."
    exit 1
fi