
    // This file is auto-generated by seedResources.setup.js
    // Do not edit this file manually
    export const Designs = {
  "Datadog seed content": {
    "id": "428fa922-c501-4774-b6c6-a1abc111bd21",
    "name": "Datadog seed content",
    "pattern_file": "{\"id\":\"00000000-0000-0000-0000-000000000000\",\"components\":null,\"name\":\"Datadog agent on k8's\",\"relationships\":null,\"schemaVersion\":\"\",\"version\":\"0.0.1\"}",
    "user_id": "2e246a4a-11e3-4b99-8c79-e42f8565e4be",
    "location": {},
    "visibility": "public",
    "catalog_data": {
      "published_version": "",
      "compatibility": null,
      "pattern_caveats": "",
      "pattern_info": "",
      "type": ""
    },
    "type": {
      "String": "Design",
      "Valid": true
    },
    "source_content": null,
    "updated_at": "2024-08-23T09:05:49.043444Z",
    "created_at": "2024-08-23T09:05:49.043441Z",
    "view_count": 0,
    "share_count": 0,
    "download_count": 0,
    "clone_count": 0,
    "deployment_count": 0,
    "expectations": {
      "noOfComponents": 2,
      "noOfConfigurableComponents": 2,
      "noOfAnnotations": 0,
      "noOfComponentsWithValidationIssues": 0
    }
  },
  "Design With Validation Errors": {
    "id": "6751f6f7-01e1-4563-90c4-077abeb0b215",
    "name": "Design With Validation Errors",
    "pattern_file": "{\"id\":\"00000000-0000-0000-0000-000000000000\",\"components\":null,\"name\":\"Design With Validation Errors \",\"relationships\":null,\"schemaVersion\":\"\",\"version\":\"0.0.1\"}",
    "user_id": "2e246a4a-11e3-4b99-8c79-e42f8565e4be",
    "location": {},
    "visibility": "public",
    "catalog_data": {
      "published_version": "",
      "compatibility": null,
      "pattern_caveats": "",
      "pattern_info": "",
      "type": ""
    },
    "type": {
      "String": "Design",
      "Valid": true
    },
    "source_content": null,
    "updated_at": "2024-08-23T09:05:49.307029Z",
    "created_at": "2024-08-23T09:05:49.307026Z",
    "view_count": 0,
    "share_count": 0,
    "download_count": 0,
    "clone_count": 0,
    "deployment_count": 0,
    "expectations": {
      "noOfComponents": 8,
      "noOfConfigurableComponents": 6,
      "noOfAnnotations": 2,
      "noOfComponentsWithValidationIssues": 1
    }
  }
};