name: Build Meshery Image

on:
  workflow_call:
    outputs:
      meshery-image:
        description: 'Name of the artifact'
        value: 'meshery-image' 

    secrets: {}

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: install/docker/Dockerfile
          tags: meshery-server:ci
          outputs: type=docker,dest=meshery.tar
  
      - name: Upload Docker artifact
        uses: actions/upload-artifact@v6
        with:
          name: meshery-image
          path: meshery.tar
