name: Build Server

on:
  workflow_call:
    outputs:
      meshery-image:
        description: 'Name of the backend artifact'
        value: 'meshery-image' 

    secrets: {}

jobs:
  build-backend:
    name: Backend build
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Build Docker image
        run: |
          docker build -f install/docker/Dockerfile -t meshery-server:ci .
  
      - name: Export Docker image
        run: |
          docker save meshery-server:ci -o meshery.tar
  
      - name: Upload Docker artifact
        uses: actions/upload-artifact@v6
        with:
          name: meshery-image
          path: meshery.tar
