name: Build Docs Preview

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, closed]
    paths:
      - '!**'
      - 'docs/**'
      - '.github/workflows/build-and-preview-docs.yml'
      - 'mesheryctl/doc/**'

permissions:
  contents: read

concurrency:
  group: preview-build-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-preview:
    runs-on: ubuntu-24.04
    env:
      HUGO_VERSION: 0.157.0

    steps:
      - name: Checkout PR code
        if: github.event.action != 'closed'
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Hugo CLI
        if: github.event.action != 'closed'
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install dart-sass
        if: github.event.action != 'closed'
        run: |
          sudo snap install dart-sass

      - name: Setup Node
        if: github.event.action != 'closed'
        uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: Install dependencies
        if: github.event.action != 'closed'
        run: |
          cd docs
          [[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true

      - name: Build PR preview
        if: github.event.action != 'closed'
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
          HUGO_PREVIEW: "true"
        run: |
          make docs-build-production BASE_URL="/"
          find docs/public -maxdepth 1 -type d -name 'v0.*' -exec rm -rf {} +
          cat > docs/public/robots.txt <<'INNER_EOF'
          User-agent: *
          Disallow: /
          INNER_EOF

      - name: Prepare Artifact Payload
        run: |
          mkdir -p pr_payload
          echo "${{ github.event.pull_request.number }}" > pr_payload/pr_number.txt
          echo "${{ github.event.action }}" > pr_payload/pr_action.txt
          if [ "${{ github.event.action }}" != "closed" ]; then
            cp -r docs/public pr_payload/public
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-preview-payload
          path: pr_payload
          retention-days: 1
