name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'archive/**'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages-deployment
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-24.04
    env:
      HUGO_VERSION: 0.157.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Node.js dependencies
        run: |
          cd docs
          [[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          make docs-build-production BASE_URL="/"
          cp docs/CNAME docs/public/CNAME
          touch docs/public/.nojekyll
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
          publish_branch: gh-pages
          keep_files: true
